### ISSUE TITLE
re:#972

### ISSUE THREAD

**Issue by 888845** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#1001]
### Suggestion Type

Other

### Suggestion

resend of #972 
how can I do it with resource packs?

**Comment by jonafanho** [comment]
Please ask for help on Discord, not here. Thanks.

**Comment by 888845** [comment]
thanks

**Comment by 888845** [comment]
> Please ask for help on Discord, not here. Thanks.

which channel mtr-support or mtr-questions
