### ISSUE TITLE
Connection previews don't flash when night vision is applied

### ISSUE THREAD

**Issue by valbuildr** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#1009]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

When connecting to rail nodes, the flashing of the connection preview doesn't happen when you have night vision.

https://github.com/user-attachments/assets/0df383b6-413a-42d2-9ad5-3fd2b2ef3b39

### Reproduction Steps

1. Apply night vision to yourself
2. Try to connect two nodes with a connector

### In-game Log and Crash Report

[latest.log](https://github.com/user-attachments/files/17928063/latest.log)

### Mod Loader

Fabric

### Minecraft Version

1.20.4

### Minecraft Transit Railway Version

4.0.0 beta 12

### Operating System

Manjaro Linux 24.1.2

### List of Mods or Modpack You Were Using

- Architectury (https://modrinth.com/mod/lhGA9TYQ)
- Athena (https://modrinth.com/mod/b1ZV3DIJ)
- Axiom (https://modrinth.com/mod/N6n5dqoA)
- BetterF3 (https://modrinth.com/mod/8shC1gFX)
- Chipped (https://modrinth.com/mod/BAscRYKm)
- Cloth Config v13 (https://modrinth.com/mod/9s6osm5g)
- Continuity (https://modrinth.com/mod/1IjD5062)
- CraterLib (https://modrinth.com/mod/Nn8Wasaq)
- Fabric API (https://modrinth.com/mod/P7dR8mSH)
- Indium (https://modrinth.com/mod/Orvt0mRa)
- Iris (https://modrinth.com/mod/YL57xq9U)
- Jade (https://modrinth.com/mod/nvQzSEkH)
- Joban Client Mod (https://modrinth.com/mod/lQqKCDhg)
- Lithium (https://modrinth.com/mod/gvQqBUqZ)
- MTR London Underground Addon (https://modrinth.com/mod/jrAXj11W)
- MTR Station Decoration Addon (https://modrinth.com/mod/station-decoration)
- Minecraft Transit Railway (https://modrinth.com/mod/XKPAmI6u)
- Mod Menu (https://modrinth.com/mod/mOgUt4GM)
- Placeholder API (https://modrinth.com/mod/eXts2L7r)
- ReFramed (https://modrinth.com/mod/jCpoCBpn)
- Reese's Sodium Options (https://modrinth.com/mod/Bh37bMuy)
- Resourceful Lib (https://modrinth.com/mod/G1hIVOrD)
- Simple RPC (https://modrinth.com/mod/ObXSoyrn)
- Simply Light (https://www.curseforge.com/projects/300331)
- Sodium (https://modrinth.com/mod/AANobbMI)
- Sodium Extra (https://modrinth.com/mod/PtjYWJkn)
- Xaero's Minimap (https://modrinth.com/mod/1bokaNcj)
- Xaero's World Map (https://modrinth.com/mod/NcUtCpym)

**Comment by valbuildr** [comment]
not fully sure if this works on windows, it probably does

**Comment by Kenny-Hui** [comment]
Should be fixed in the upcoming beta version!
