### ISSUE TITLE
Top 3 'Hide Arrival' checkboxes GUI not working on the vertical PIDS

### ISSUE THREAD

**Issue by valbuildr** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#1011]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

When in the config menu for a vertical PIDS, the top three checkboxes labeled as 'Hide Arrival' don't work.

https://github.com/user-attachments/assets/2c9a3d6c-e965-49ee-bdc0-cb7cabe8ea9f

### Reproduction Steps

1. Right-click on a vertical PIDS with a brush
2. Try to check one of the top three 'Hide Arrival' checkboxes

### In-game Log and Crash Report

[latest.log](https://github.com/user-attachments/files/18001711/latest.log)

### Mod Loader

Fabric

### Minecraft Version

1.20.4

### Minecraft Transit Railway Version

4.0.0 (beta 12)

### Operating System

Windows 11

### List of Mods or Modpack You Were Using

- [Architectury](https://modrinth.com/mod/lhGA9TYQ)
- [Athena](https://modrinth.com/mod/b1ZV3DIJ)
- [Axiom](https://modrinth.com/mod/N6n5dqoA)
- [BetterF3](https://modrinth.com/mod/8shC1gFX)
- [Chipped](https://modrinth.com/mod/BAscRYKm)
- [Cloth Config v13](https://modrinth.com/mod/9s6osm5g)
- [Continuity](https://modrinth.com/mod/1IjD5062)
- [CraterLib](https://modrinth.com/mod/Nn8Wasaq)
- [Fabric API](https://modrinth.com/mod/P7dR8mSH)
- [Indium](https://modrinth.com/mod/Orvt0mRa)
- [Iris](https://modrinth.com/mod/YL57xq9U)
- [Jade](https://modrinth.com/mod/nvQzSEkH)
- [Joban Client Mod](https://modrinth.com/mod/lQqKCDhg)
- [Lithium](https://modrinth.com/mod/gvQqBUqZ)
- [MTR London Underground Addon](https://modrinth.com/mod/jrAXj11W)
- [MTR Station Decoration Addon](https://modrinth.com/mod/station-decoration)
- [Minecraft Transit Railway](https://modrinth.com/mod/XKPAmI6u)
- [Mod Menu](https://modrinth.com/mod/mOgUt4GM)
- [Placeholder API](https://modrinth.com/mod/eXts2L7r)
- [ReFramed](https://modrinth.com/mod/jCpoCBpn)
- [Reese's Sodium Options](https://modrinth.com/mod/Bh37bMuy)
- [Replay Mod](https://modrinth.com/mod/Nv2fQJo5)
- [Resourceful Lib](https://modrinth.com/mod/G1hIVOrD)
- [Simple RPC](https://modrinth.com/mod/ObXSoyrn)
- [Simply Light](https://www.curseforge.com/projects/300331)
- [Sodium](https://modrinth.com/mod/AANobbMI)
- [Sodium Extra](https://modrinth.com/mod/PtjYWJkn)
- [Xaero's Minimap](https://modrinth.com/mod/1bokaNcj)
- [Xaero's World Map](https://modrinth.com/mod/NcUtCpym)

**Comment by Kenny-Hui** [comment]
Fixed in the upcoming beta
