### ISSUE TITLE
Cannot remove elevators/lifts that has no connections

### ISSUE THREAD

**Issue by birbpasha** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#1012]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

I moved a massive landscape to another place with worldedit but a tower that had MTR elevators just didn't disappear. I tried commands like /kill @e[type=mtr:lift_2_2_double_sided], /kill @e[sort=nearest,limit=1]. but the elevators won't disappear.
![image](https://github.com/user-attachments/assets/23d3ba46-f52a-4878-a066-6b30079f833a)

### Reproduction Steps

1. Create an elevator system in a tower or a building
2. Set the selection with air

The bug is now occured.

### In-game Log and Crash Report

It's in a server i don't own, can't access the log.

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Minecraft Transit Railway Version

4.0.0

### Operating System

Ubuntu 24.04.1 LTS

### List of Mods or Modpack You Were Using

Just worldedit, sodium, iris, sodium extra.

**Comment by RXTransit** [comment]
Just place an elevator floor track at its original position and break it,

WorldEdit only sees blocks, and not the things between like rails or elevators
