### ISSUE TITLE
Optifine shaders compatibility for 1.20.1

### ISSUE THREAD

**Issue by javierbentez** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#1016]
### Suggestion Type

Train visual/audio effects

### Suggestion

Hi, when using shaders, the textures are bugged and not visible correctly.

![2024-12-15_00 31 40](https://github.com/user-attachments/assets/4e21e169-590b-4f6c-82b4-26d1202d8693)

### Implementation Details and References

I'm using Sildur's Vibrant shaders

**Comment by Kenny-Hui** [comment]
Optifine is not supported as of MTR 4.0.
If you are on Forge, please switch to mods like [Rubidium](https://modrinth.com/mod/rubidium) and [Oculus](https://modrinth.com/mod/oculus) to achieve performance boost and shaders.
For fabric, switch to [Sodium](https://modrinth.com/mod/sodium) and [Iris](https://modrinth.com/mod/iris)
