### ISSUE TITLE
Modify the track model and texture

### ISSUE THREAD

**Issue by AIDA64S** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#125]
假如鐵軌不是一個平面而是斜坡，鐵軌浮在空中很難看，建議鐵軌的貼圖不在僅僅是兩根線，可以下面增加一層圖層，用灰色混凝土顏色(或者其他的顏色)填充，或者就像列車貼圖以及標誌貼圖那樣支持追加

**Comment by 566666666666789** [comment]
Suggested change: Modify the track model and texture @AIDA64S

**Comment by 566666666666789** [comment]
建议改成：修改轨道模型和贴图 @AIDA64S

**Comment by jonafanho** [comment]
This has been added via OBJ rail rendering.
