### ISSUE TITLE
列车进入打不开屏蔽门 The train could not open the platform door

### ISSUE THREAD

**Issue by ximengwhite** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#365]
列车进入打不开屏蔽门 The train could not open the platform door

![3U~G6)P5S7G%Q8T~7WS3FHX](https://user-images.githubusercontent.com/106060350/169942846-fdc3b598-a41f-4eb1-9a24-cc07b34cd6d7.png)

**Environment**

- Minecraft Version:1.16.5
- Installed Mods:
[【A模组清单】.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/8759330/A.txt)

**Additional Information**
Anything else you want to add?之前得到那个不能更改列车的bug在重启服务器后自行修复了
The bug that could not change the train was fixed by rebooting the server

**Comment by kettle-7** [comment]
@ximengwhite Yes, this is a client-server latency issue and can't be fixed.

**Comment by kettle-7** [comment]
It should re-sync when the train leaves a station though.

**Comment by ximengwhite** [comment]
@kettle-7 The platform door seemed glued to the platform and would not open whether the train was coming or not

**Comment by Ultimate-USA-YT** [comment]
As Kettle said, it is Client-Server Lag. Can not be Fixed.

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
