### ISSUE TITLE
接触网、第三轨、改进的票务系统以及屏蔽门端头门和自定义贴纸

### ISSUE THREAD

**Issue by XHG78999** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#367]
**Is your feature request related to a problem? Please describe.**
现在的车几乎没有任何能源来源，不管是接触网还是第三轨。
真·先进动力（雾
至于屏蔽门端头门，从外部需要用特定钥匙打开。
现实中，铁路票务系统可以购买单程票，同时每一个人都可以拥有多张交通卡。现有制度真的像大陆社保，一人一账户，交换还不方便。
对于不同的地域，贴纸样式一般不同（虽然MTR已经抢，啊不，走遍全中国导致其样式扩散开来），比如我使用railmapgen/RailMapGenerator（我参与了此项目的部分讨论，可以考虑看看，参考相关MTR风线路图生成）生成的上海风格（本人比较讨厌MTR风）图片，上传到图床后直接显示，不需要再使用ImageSign之类的模组进行覆盖。

**Describe the solution you'd like**
关于接触网和第三轨：模型等建议咨询bilibili上制作RealTrainMod追加的@CacPixel，相信他会很高兴给你一些关于接触网的obj文件的。
至于第三轨，可能需要自己建模了。
关于屏蔽门端头门：内部可以直接打开到外部，外部需要输入密码（放置时设定）
票务：可以按照距离计算车票消费，收取对应绿宝石发放一次性车票，手持车票过闸同时车票变为已进站状态，出站收走车票。车票不在目标车站出站将无法通过闸机。
每个人可以买多张交通卡，每张卡可以有不同的余额，同时可以随时退卡，余额扣除2%后以绿宝石比例返还。
现有售票机只售卖单程票，交通卡需要在专门的交通卡机（亦或是“自动加值机”，住在上海看到的描述）上购买，退卡与充值。
图片显示：刷子Shift+右键屏蔽门设置URL。

**Additional Information**

**Comment by CacPixel** [comment]
好家伙，我star了这个项目然后被github的邮件轰过来了。。。
“车票不在目标车站出站将无法通过闸机。”我觉得应该是两站路的价格高于票的余额才无法通过闸机（请去服务中心）还合理一点，大概的思路就是票的NBT有一项是余额，出站的时候判断卡内余额>=两站路设定的票价，true则收票，false则不能通过闸机。
哦另外我做的接触网都是mqo格式的，obj格式的话可能还要转。

**Comment by CacPixel** [comment]
> **Is your feature request related to a problem? Please describe.** 现在的车几乎没有任何能源来源，不管是接触网还是第三轨。 真·先进动力（雾 至于屏蔽门端头门，从外部需要用特定钥匙打开。 现实中，铁路票务系统可以购买单程票，同时每一个人都可以拥有多张交通卡。现有制度真的像大陆社保，一人一账户，交换还不方便。 对于不同的地域，贴纸样式一般不同（虽然MTR已经抢，啊不，走遍全中国导致其样式扩散开来），比如我使用railmapgen/RailMapGenerator（我参与了此项目的部分讨论，可以考虑看看，参考相关MTR风线路图生成）生成的上海风格（本人比较讨厌MTR风）图片，上传到图床后直接显示，不需要再使用ImageSign之类的模组进行覆盖。
> 
> **Describe the solution you'd like** 关于接触网和第三轨：模型等建议咨询bilibili上制作RealTrainMod追加的@CacPixel，相信他会很高兴给你一些关于接触网的obj文件的。 至于第三轨，可能需要自己建模了。 关于屏蔽门端头门：内部可以直接打开到外部，外部需要输入密码（放置时设定） 票务：可以按照距离计算车票消费，收取对应绿宝石发放一次性车票，手持车票过闸同时车票变为已进站状态，出站收走车票。车票不在目标车站出站将无法通过闸机。 每个人可以买多张交通卡，每张卡可以有不同的余额，同时可以随时退卡，余额扣除2%后以绿宝石比例返还。 现有售票机只售卖单程票，交通卡需要在专门的交通卡机（亦或是“自动加值机”，住在上海看到的描述）上购买，退卡与充值。 图片显示：刷子Shift+右键屏蔽门设置URL。
> 
> **Additional Information**

好家伙，我star了这个项目然后被github的邮件轰过来了。。。
“车票不在目标车站出站将无法通过闸机。”我觉得应该是两站路的价格高于票的余额才无法通过闸机（请去服务中心）还合理一点，大概的思路就是票的NBT有一项是余额，出站的时候判断卡内余额>=两站路设定的票价，true则收票，false则不能通过闸机。
哦另外我做的接触网都是mqo格式的，obj格式的话可能还要转。

**Comment by XHG78999** [comment]
> > **Is your feature request related to a problem? Please describe.** 现在的车几乎没有任何能源来源，不管是接触网还是第三轨。 真·先进动力（雾 至于屏蔽门端头门，从外部需要用特定钥匙打开。 现实中，铁路票务系统可以购买单程票，同时每一个人都可以拥有多张交通卡。现有制度真的像大陆社保，一人一账户，交换还不方便。 对于不同的地域，贴纸样式一般不同（虽然MTR已经抢，啊不，走遍全中国导致其样式扩散开来），比如我使用railmapgen/RailMapGenerator（我参与了此项目的部分讨论，可以考虑看看，参考相关MTR风线路图生成）生成的上海风格（本人比较讨厌MTR风）图片，上传到图床后直接显示，不需要再使用ImageSign之类的模组进行覆盖。
> > 
> > **Describe the solution you'd like** 关于接触网和第三轨：模型等建议咨询bilibili上制作RealTrainMod追加的@CacPixel，相信他会很高兴给你一些关于接触网的obj文件的。 至于第三轨，可能需要自己建模了。 关于屏蔽门端头门：内部可以直接打开到外部，外部需要输入密码（放置时设定） 票务：可以按照距离计算车票消费，收取对应绿宝石发放一次性车票，手持车票过闸同时车票变为已进站状态，出站收走车票。车票不在目标车站出站将无法通过闸机。 每个人可以买多张交通卡，每张卡可以有不同的余额，同时可以随时退卡，余额扣除2%后以绿宝石比例返还。 现有售票机只售卖单程票，交通卡需要在专门的交通卡机（亦或是“自动加值机”，住在上海看到的描述）上购买，退卡与充值。 图片显示：刷子Shift+右键屏蔽门设置URL。
> > 
> > **Additional Information**
> 
> 好家伙，我star了这个项目然后被github的邮件轰过来了。。。
> “车票不在目标车站出站将无法通过闸机。”我觉得应该是两站路的价格高于票的余额才无法通过闸机（请去服务中心）还合理一点，大概的思路就是票的NBT有一项是余额，出站的时候判断卡内余额>=两站路设定的票价，true则收票，false则不能通过闸机。
> 哦另外我做的接触网都是mqo格式的，obj格式的话可能还要转。

艹本人居然来了

这个单程票机制也行（其实是我打错了），但问题是人把车票丢了咋办？

话说什么时候可以考虑出站换乘了啊，真实MTR的出站换乘复杂的一批（见railmapgen/rmg#355中的讨论）

至于图片，我觉得可以远期，现在高版本只有ImageSign一个，然后因为最近gitee被强制审核代码所以咱们都没法拿来看看。。。。

**Comment by kettle-7** [comment]
For the caternary, it's being coded in at the moment but will take a while. We can't use Blender models though, MTR only works with Blockbench.

**Comment by XHG78999** [comment]
> For the caternary, it's being coded in at the moment but will take a while. We can't use Blender models though, MTR only works with Blockbench.

Emmm..... I know because the author of the net used the special .mqo format for RealTrainMod that it use NGTLib to load custom model. I only raise it, and also we can rebuild a Blockbench version and more pixel art.

**Comment by CacPixel** [comment]
> 

补票（逃
如果是头等那就等着被罚钱（doge

**Comment by CacPixel** [comment]
> > > **Is your feature request related to a problem? Please describe.** 现在的车几乎没有任何能源来源，不管是接触网还是第三轨。 真·先进动力（雾 至于屏蔽门端头门，从外部需要用特定钥匙打开。 现实中，铁路票务系统可以购买单程票，同时每一个人都可以拥有多张交通卡。现有制度真的像大陆社保，一人一账户，交换还不方便。 对于不同的地域，贴纸样式一般不同（虽然MTR已经抢，啊不，走遍全中国导致其样式扩散开来），比如我使用railmapgen/RailMapGenerator（我参与了此项目的部分讨论，可以考虑看看，参考相关MTR风线路图生成）生成的上海风格（本人比较讨厌MTR风）图片，上传到图床后直接显示，不需要再使用ImageSign之类的模组进行覆盖。
> > > **Describe the solution you'd like** 关于接触网和第三轨：模型等建议咨询bilibili上制作RealTrainMod追加的@CacPixel，相信他会很高兴给你一些关于接触网的obj文件的。 至于第三轨，可能需要自己建模了。 关于屏蔽门端头门：内部可以直接打开到外部，外部需要输入密码（放置时设定） 票务：可以按照距离计算车票消费，收取对应绿宝石发放一次性车票，手持车票过闸同时车票变为已进站状态，出站收走车票。车票不在目标车站出站将无法通过闸机。 每个人可以买多张交通卡，每张卡可以有不同的余额，同时可以随时退卡，余额扣除2%后以绿宝石比例返还。 现有售票机只售卖单程票，交通卡需要在专门的交通卡机（亦或是“自动加值机”，住在上海看到的描述）上购买，退卡与充值。 图片显示：刷子Shift+右键屏蔽门设置URL。
> > > **Additional Information**
> > 
> > 
> > 好家伙，我star了这个项目然后被github的邮件轰过来了。。。
> > “车票不在目标车站出站将无法通过闸机。”我觉得应该是两站路的价格高于票的余额才无法通过闸机（请去服务中心）还合理一点，大概的思路就是票的NBT有一项是余额，出站的时候判断卡内余额>=两站路设定的票价，true则收票，false则不能通过闸机。
> > 哦另外我做的接触网都是mqo格式的，obj格式的话可能还要转。
> 
> 艹本人居然来了
> 
> 这个单程票机制也行（其实是我打错了），但问题是人把车票丢了咋办？
> 
> 话说什么时候可以考虑出站换乘了啊，真实MTR的出站换乘复杂的一批（见railmapgen/rmg#355中的讨论）
> 
> 至于图片，我觉得可以远期，现在高版本只有ImageSign一个，然后因为最近gitee被强制审核代码所以咱们都没法拿来看看。。。。

补票（逃
如果是头等那就等着被罚钱（doge

**Comment by XHG78999** [comment]
新需求：可否考虑使得NPC自动过闸？拍摄相关短片可能需要这些。

**Comment by Mi6A16** [comment]
在現實裏，是按車站收費的

**Comment by pokOSlanx** [comment]
> 新需求：可否考慮使得NPC自動過閘？拍攝相關短片可能需要這些。

我记得jonafanho就说过不会做这东西（悲
至于你说的”公交卡“……我觉得改为”八达通“会更好，这样子加个八达通机或者八达通APP（bushi），再把八达通机绑定到玩家，就可以在服务器实现电子支付（doge

**Comment by XHG78999** [comment]
***@***.***做出来力（悲公交卡......其实和八达通差不多，（事内地称呼-------- 原始邮件 --------发件人： pokOSlanx ***@***.***>日期： 2022年12月27日周二 傍晚5:00收件人： jonafanho/Minecraft-Transit-Railway ***@***.***>抄送： XHG78999 ***@***.***>, Author ***@***.***>主    题： Re: [jonafanho/Minecraft-Transit-Railway] 接触网、第三轨、改进的票务系统以及屏蔽门端头门和自定义贴纸 (Issue #367)

新需求：可否考慮使得NPC自動過閘？拍攝相關短片可能需要這些。

我记得jonafanho就说过不会做这东西（悲
至于你说的”公交卡“……我觉得改为”八达通“会更好，这样子加个八达通机或者八达通APP（bushi），再把八达通机绑定到玩家，就可以在服务器实现电子支付（doge

**Comment by jonafanho** [comment]
Ticket system enhancements: tracked by #359 
Catenaries: added by [MTR Station Decoration](https://github.com/AIDA64S/MTR-Station-Decoration-Addon)
Third rail: can be added using OBJ models in 4.0.0
Thank you!

**Comment by pokOSlanx** [comment]
***@***.******@***.******@***.******@***.******@***.***
