### ISSUE TITLE
对于“站名（墙上）”方块的一些建议

### ISSUE THREAD

**Issue by ZiYueCommentary** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#396]
在之前的版本中， **站名（墙上）** 跟现在入口的站名方块不同，之前版本的文字不会受到挤压。

而在现在的版本中，这个方块变得和入口站名方块相似。

在有些情况下这会很不美观：

![QQ图片20220615211848](https://user-images.githubusercontent.com/63241389/173836705-3146eacc-7818-4b8b-9146-ef042a4787ea.png)

在之前的版本里，这个位置可以正常显示站名，而现在不行。

所以，我的建议是保留之前版本的方块，而改版之后的则用新的注册名，这样对于地图制作者也比较友好。

**Comment by ZiYueCommentary** [comment]
另外方块是3.0.1才改版，而3.0.1尚未发布。
建议在3.0.1发布之前解决这个问题，避免地图中出现的问题过多。

**Comment by DreamUniverse843** [comment]
看起来方块的加载逻辑直接发生了改变？
目前看，站名（墙上）的布设逻辑和车站名贴纸的逻辑一致了（摆多大的区域，渲染多大的区域）
可以把站名（墙上）分成两类，固定尺寸（与原始渲染方法一致）和可变尺寸（与现在新版方法一致）

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. You can now place multiple Station Name (Wall) blocks next to each other to make them longer. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
