### ISSUE TITLE
Add different door opening methods to custom models. 为自定义模型添加不同的开门方式。

### ISSUE THREAD

**Issue by Mira-LeafTown** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#406]
The current version of the custom model can only make hidden door and external door.
Please add sliding plug door (jiggle sliding plug door and right angle sliding plug door) to the custom model and have electric and pneumatic door opening methods, thanks.
现版本的自定义模型只能制作内藏门与外挂门。
请为自定义模型增加塞拉门 (微动塞拉门和直角塞拉门)，并且有电动和气动的开门方式，谢谢。

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. You can now specify the door X and Z offsets individually as well as the door animation type. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
