### ISSUE TITLE
Circular Tunnels

### ISSUE THREAD

**Issue by rares45** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#412]
**Is your feature request related to a problem? Please describe.**
The rectangular tunnels look great, but they aren't always realistic for metro tunnels.

**Describe the solution you'd like**
I'd like to see circular tunnels.

**Additional Information**
![image](https://user-images.githubusercontent.com/42469755/175764819-fc170509-7bd0-4db9-bffb-dd045eec6b6f.png)
The base has 3 cubes floor that will allow using the 3 blocks bridge item.

**Comment by Raft08** [comment]
You can use [this](https://www.curseforge.com/minecraft/mc-mods/london-underground)
It adds Circular Tunnels

**Comment by kettle-7** [comment]
They mean to have the tunnel wall, tunnel and bridge creator do circles

You can achieve this with the different tunnel creator sizes.

**Comment by Raft08** [comment]
Ow ok i see

**Comment by 596wjr** [comment]
maybe u can use a one-meter depot train(or what
你也许可以用一个一米的车厂列车

**Comment by jonafanho** [comment]
This can now be achieved using custom OBJ models for tunnels. Closing this for now, thanks.
