### ISSUE TITLE
MTR doesn't work with the Charm mod

### ISSUE THREAD

**Issue by Dakuro** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#420]
**Expected Behaviour**
Game launches normally

**Actual Behaviour**
Game crashes on startup

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Try to launch the game with both MTR and Charm

**Crash Report**
[crash-2022-07-02_17.51.21-client.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/9033262/crash-2022-07-02_17.51.21-client.txt)

**Environment**

- Minecraft Version: 1.19 with Quilt Mod Loader
- Installed Mods: [Charm](https://github.com/svenhjol/Charm)

**Comment by jakobneufeld** [comment]
@Dakuro I have tried to run MTR using Quilt, and it sometimes crashed with some mods. Try to do the same with Fabric. I do not know why, but Quilt and MTR somtimes do not work together smoothly.

**Comment by Dakuro** [comment]
As incredible as it sounds, MTR and Charm do work together when using Fabric instead of Quilt :/

Thank you for helping me with this
I will talk about this with the Quilt team to see if they can find the problem :)

**Comment by jonafanho** [comment]
Is it a Charm problem? Doesn't seem to be related with this mod.

**Comment by Dakuro** [comment]
I think it is a Quilt problem, but strangely it occurs only when using MTR and Charm together.

I'll ask Quilt team to investigate this.

**Comment by jakobneufeld** [comment]
MTR works with Quilt client and integrated server but not dedicated server. Do you know why @jonafanho? I tested this and cherbert I think tested this.
