### ISSUE TITLE
Improve the Resourcepack Creator

### ISSUE THREAD

**Issue by XHG78999** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#421]
**Is your feature request related to a problem? Please describe.**
Now the Resourcepack Creator decides a way to create custom models, but only can use by single model.
If we need trains like normal railway:
`|Head|-|Train|-|Train|-|Train|-|Train|-|Train|-|Train|`
or more complex:
`|Head|-|Powergen|-|Baggage|-|Train|-|Train|-|Dining|-|Train|-|Train|-|Train|`
In Metro, we also like to do rejoin, like as Shanghai Metro Line 16 before 2021:
`|SH16A01-Head|-|SH16A01|-|SH16A01-Head|-|SH16A01-Head|-|SH16A01|-|SH16A01-Head|`
We can do this by using whitelist and blacklist now, but it is soooooooo complex.
Sometimes, head and train are not do by same author, so we need to make them to single model.
If we need to feel 'Free' to use trains, author may do this:
```
Train_DF8B_25T.bbmodel
Train_DF8B_25G.bbmodel
Train_DF8B_25K.bbmodel
Train_DF8B_25T_CA.bbmodel
Train_DF8B_25G_CA.bbmodel
Train_DF8B_25K_CA.bbmodel
Train_DF8B_25T_WP.bbmodel
Train_DF8B_25G_WP.bbmodel
Train_DF8B_25K_WP.bbmodel
Train_DF8B_25T_CAWP.bbmodel
Train_DF8B_25G_CAWP.bbmodel
Train_DF8B_25K_CAWP.bbmodel
Train_DF8B_25T_GJ.bbmodel
Train_DF8B_25G_GJ.bbmodel
Train_DF8B_25K_GJ.bbmodel
Train_DF8B_25T_Green.bbmodel
Train_DF8B_25G_Green.bbmodel
Train_DF8B_25K_Green.bbmodel
Train_DF8B_25T_CA_Green.bbmodel
Train_DF8B_25G_CA_Green.bbmodel
Train_DF8B_25K_CA_Green.bbmodel
Train_DF8B_25T_WP_Green.bbmodel
Train_DF8B_25G_WP_Green.bbmodel
Train_DF8B_25K_WP_Green.bbmodel
Train_DF8B_25T_CAWP_Green.bbmodel
Train_DF8B_25G_CAWP_Green.bbmodel
Train_DF8B_25K_CAWP_Green.bbmodel
Train_DF8B_25T_GJ_Green.bbmodel
Train_DF8B_25G_GJ_Green.bbmodel
Train_DF8B_25K_GJ_Green.bbmodel
Train_SS3_NXD3.bbmodel
.......
```
It is so terrible to do these with many repeats in resourcepack creator, so we think we can add more free selects to do these.

**Describe the solution you'd like**
*Translating*
1. Creator can import more models, train length and connector are all set whitelist and blacklist.
2. Change "Train" to "EMU", add "Locomotive" and "Car" type.
3. Add three types "EMU","Locomotive","Car" to the siding rail.
4. Custom Grouping: Like editing sign, we can list the train types we can use, use '+' to add to the group, and we can use '<''>' to move the position by hovering the train.
5. Add the preview menu, show by name like this:`|SS3|-|XL25G|-|YZ25G|`
6. The preset group can replace the custom group.
7. More flexible length like 20.5.(Useful to China B-Type/C-Type Train)
8. [NOT NECESSARY] Add catenary generator to generate catenary on the rail like tunnel creator.
9. [NOT NECESSARY] Every EMU train can use single grouping, or can use preset groups, like:
```
- SP1900 Head
- SP1900 Middle
- SP1900 First-class
- SP1900 Normal
- SP1900 Middle and First-class (need ＞5 trains)
- MLR Head
- ......
```

**Additional Information**
***This issue is copy from https://www.mtrbbs.top/forum.php?mod=viewthread&tid=324 , some infomation there are written by myself.***

**Comment by jonafanho** [comment]
In 4.0.0, you can now make each individual car as a separate model. I will make another resource pack creator in the future, so I will close this for now. Thanks!
