### ISSUE TITLE
Cull trains

### ISSUE THREAD

**Issue by squid233** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#432]
**Is your feature request related to a problem? Please describe.**
Performance decreased when there are many trains. All trains within render distance are rendered even if the player can't see them.

**Describe the solution you'd like**
Cull invisible trains.

**Additional Information**
Give a bounding box to trains and culling by the frustum from the player.

**Comment by ZitexZ** [comment]
This would be very helpful. Especially with Shaders the performance drops massively.

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this if you still encounter this issue with 4.0.0, thanks!
