### ISSUE TITLE
Some suggestions for custom model rendering settings. 一些为自定义模型渲染设置所想的建议。

### ISSUE THREAD

**Issue by Mira-LeafTown** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#439]
Please add more rendering settings just like
Render: Train Moving
Render: Train Stopped
Render: In Depot
Render: Back to Depot
请添加更多渲染设置，就像
渲染：当列车移动时
渲染：当列车停顿时
渲染：当列车在车辆段时
渲染：当列车回车辆段时

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
