### ISSUE TITLE
与机械动力冲突

### ISSUE THREAD

**Issue by Dr-WeiAL** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#440]
在机械动力0.5之前会导致动态结构无法显示，在0.5会直接崩溃
https://github.com/Fabricators-of-Create/Create/issues/426

**Comment by jonafanho** [comment]
I will close this for now since the code has changed a lot in 4.0.0. Please reopen if this issue still persists in 4.0.0, thanks!
