### ISSUE TITLE
Xaero's World Map Incompatibility

### ISSUE THREAD

**Issue by sleepysapph** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#487]
**Expected Behaviour**
Be able to open Xaero's World Map and when I close it, the trains are where they would be if I hadn't opened the map

**Actual Behaviour**
A massive desync occurs. In multiplayer, when opening Xaero's World Map, MTR on client side thinks the game is pausing as if in singleplayer. It's not a Xaero's issue as it doesnt happen with mobs, only MTR vehicles, and Xaero himself has confirmed that it's nothing on his end. However, the player and train are kind-of still moving on serverside so there's a dysync after closing the map. Cable Cars and trains aren't where they actually are

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Install MTR on a server
2. Install Xaero's World Map on clientside
3. Go to a Cable Car station (is most pertinent and noticable there)
4. Press M to open Xaero's World Map
5. Close it
6. Try to board a Cable Car

**Environment**

- Minecraft Version: 1.16.5 Fabric on 0.11.3

**Comment by WerySkok** [comment]
Same behaviour on Forge 1.18.2

**Comment by Big-Cake-jpg** [comment]
Same issue on Fabric 1.16.5 & Fabric 1.18.2

**Comment by XHG78999** [comment]
> **Expected Behaviour** Be able to open Xaero's World Map and when I close it, the trains are where they would be if I hadn't opened the map
> 
> **Actual Behaviour** A massive desync occurs. In multiplayer, when opening Xaero's World Map, MTR on client side thinks the game is pausing as if in singleplayer. It's not a Xaero's issue as it doesnt happen with mobs, only MTR vehicles, and Xaero himself has confirmed that it's nothing on his end. However, the player and train are kind-of still moving on serverside so there's a dysync after closing the map. Cable Cars and trains aren't where they actually are
> 
> **Reproduction Steps** Steps to reproduce the behaviour:
> 
> 1. Install MTR on a server
> 2. Install Xaero's World Map on clientside
> 3. Go to a Cable Car station (is most pertinent and noticable there)
> 4. Press M to open Xaero's World Map
> 5. Close it
> 6. Try to board a Cable Car
> 
> **Environment**
> 
> * Minecraft Version: 1.16.5 Fabric on 0.11.3

Same behavior of JourneyMap.
