### ISSUE TITLE
Change elevator chime / Make a custom elevator chime

### ISSUE THREAD

**Issue by chortle3** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#521]
**Hello MTR mod developers,
I want a feature that you can change the elevator chime (or ding sound)**

1. Use a brush to click on any floor on an elevator
2. There's a new box called "Ding/Chime Sounds", click on it
3. Type the custom sound like this: minecraft:custom_music
4. Adjust the volume, pitch or speed
5. Click Save when your done
6. Now, your elevator's chime/ding sound is now with the custom sound!

**Comment by boiii3** [comment]
I totally agree with your post!

If you want, you can look at my suggestion: https://github.com/jonafanho/Minecraft-Transit-Railway/issues/598

**Comment by jonafanho** [comment]
Tracked in #598
