### ISSUE TITLE
Add track hiding options

### ISSUE THREAD

**Issue by moluoxuezha** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#531]
MTR is a good mod that has many type of public transports，such as trains ，boats and cables.
BUT,if the mod add track hiding options that make the track of a line disappear but doesnt affecting 
to  the line‘s operation,it can be more type of transport:  like  Monorails，Planes  or Buses.
       SO, please _add the  track hiding options_, I  think it will be useful to many players.

**Comment by moluoxuezha** [comment]
just like this plane ，it just cant  make the track disappear.

**Comment by moluoxuezha** [comment]
l

**Comment by moluoxuezha** [comment]
like this

**Comment by Ultimate-USA-YT** [comment]
Are you Replying to Yourself?

**Comment by faelBrunnoS** [comment]
No need to hide the tracks!
You can place the rails wherever you want and then adjust the OFFSET X,Y,Z
With this you can hide the tracks on the other side of the block or wherever you want.
![image](https://user-images.githubusercontent.com/83606488/198885631-b7f5f59a-e8bb-47d0-a15f-d43891689ff2.png)

**Comment by kettle-7** [comment]
you can actually do the same with rails and custom trains, there's a rail offset thingy

**Comment by moluoxuezha** [comment]
where is the rail offset thingy？i  cant find it

**Comment by faelBrunnoS** [comment]
> where is the rail offset thingy？i  cant find it
Use the Elevator Refresh item on the elevator track. 
And make the adjustment on the XYZ.

**Comment by faelBrunnoS** [comment]
The elevator will not disappear.  You'll take the tracks and place them wherever you want, then use the Refresher to change the rendering position of the elevator!  The elevator will be rendered according to what you configure in the menu that appears after pressing the right button on the elevator track using the Refresher!

So you will hide the trail in any corner!  There is no way to make the trail invisible!  But there's a way to hide behind blocks!

**Comment by kettle-7** [comment]
That's a lot of exclamation marks !
But I think what you're talking about is putting the tracks somewhere away from the elevator shaft

**Comment by faelBrunnoS** [comment]
> That's a lot of exclamation marks ! But I think what you're talking about is putting the tracks somewhere away from the elevator shaft

It's to do what I did in the image above!
There in the example, I placed the rail on one side of the block and made the elevator appear on the other side of the block!
So the track doesn't appear, because I'm going to cover it with blocks!

**Comment by kettle-7** [comment]
yeah but it sounds like @moluoxuezha means to do this with the rails the trains run on. it is technically possible with the same method but it involves a custom train model and you could just use /setblock and a debug stick to make boat nodes instead, which are invisible anyway

**Comment by XHG78999** [comment]
I have a solution.
Setup a route as normal, and then remove all rail nodes expect depot line. It should works if you don't flush the route.

**Comment by jonafanho** [comment]
Tracks can now be hidden in 4.0.0 by modifying the track models.
