### ISSUE TITLE
Walking through walls

### ISSUE THREAD

**Issue by rabrunos** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#532]
I have a problem that allows me to walk through the wall when the elevator is going up or down.

I don't take damage or anything like that.
I disabled all other mods and left only the Elevator, but the problem continued.
So it's not conflict with any mod.

Minecraft 1.19.2
Fabric 0.14.10

![ezgif com-gif-maker](https://user-images.githubusercontent.com/83606488/198886213-4adfb65e-3075-4d8c-a8f8-dc41dc863377.gif)

**Comment by saleem0915** [comment]
Did you check to see if you were in spectator mode?

**Comment by faelBrunnoS** [comment]
> Did you check to see if you were in spectator mode?

It's in the GIF!

**Comment by kettle-7** [comment]
> Did you check to see if you were in spectator mode?

people on spectator don't have a health bar...

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
