### ISSUE TITLE
Floor Button

### ISSUE THREAD

**Issue by rabrunos** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#533]
It would be nice to have buttons that select the floor for the elevator to go to instead of having to press Z.
Since there's a way to place blocks in the elevator shaft, the button would stay there without anything getting in the way.
See Example:

![image](https://user-images.githubusercontent.com/83606488/198886837-c3d2b98b-e744-4d2a-b381-72d55c49b59f.png)

But if this is the way the buttons are implemented, it would be nice if the panel didn't have depth, that it was like a "sheet of paper" glued to the wall, so it wouldn't have that elevation disturbing the vision as in the image above.

It could be something really simple, just with the buttons with the numbers inside them.

Suppose it has 5 floors.
The panel has 5 buttons.
If you are on Floor 3, Button 3 has a highlighted green light to indicate which floor you are on.
You press the 5 button, the green one goes out of the 3 button and the 5 button has a highlighted red light to indicate which floor you are going to.
Upon reaching the 5th floor, the light changes to green.

**Comment by saleem0915** [comment]
I like this idea!

**Comment by jonafanho** [comment]
Thanks for the suggestion. I think a separate menu has been created on purpose so that there wouldn't be any space constraint. Imagine if someone creates an elevator with 100 floors; I don't think it would look good to fit 100 buttons on a panel.

**Comment by rabrunos** [comment]
I understand your point, but I think it's still a valid idea, not for 100 floors as you said, but most players will create 10 floors at most, so it would be interesting to have a panel perhaps with a maximum of 10 floors or any other maximum, and then if the player wants more than the maximum, then it would be mandatory to use the menu!
But I, for example, would create a few elevators for my small base, just a few floors, and I'm sure many players would do the same!
And then a few more buttons would be better than opening the menu!

Obviously, I don't want to be so arrogant as to say what your mod needs or doesn't need, I'm just explaining my idea!
But I'm not currently playing Minecraft, so maybe my words are worthless haha
