### ISSUE TITLE
[Bug] resource pack creator is unable to be used

### ISSUE THREAD

**Issue by CKFA** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#536]
As title mentioned, the tool for creating new train cannot be used. 

Not thing is showing on the screen as following.
(MTR-fabric-1.16.5-3.0.1.jar)

![image](https://user-images.githubusercontent.com/59402813/200135122-2aa8ba0f-3778-4741-99a7-60d1995656d6.png)

Also, in 1.19.2 3.1.0 fabric version, when i press the + button, the game will be crashed.

Please fix it. Thanks.

Here is the crash report:
![image](https://user-images.githubusercontent.com/59402813/200135601-229218c2-9de7-46d4-a6d5-17386562cf42.png)

---- Minecraft Crash Report ----
// Don't do that.

Time: 2022-11-06 02:33:55
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_630.method_2851(float, float, float)" because "this.modelPart" is null
	at mtr.mappings.ModelMapper.render(ModelMapper.java:83)
	at mtr.model.ModelTrainBase.renderOnce(ModelTrainBase.java:77)
	at mtr.client.DynamicTrainModel.lambda$render$4(DynamicTrainModel.java:173)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at mtr.client.DynamicTrainModel.lambda$render$5(DynamicTrainModel.java:167)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at mtr.client.DynamicTrainModel.render(DynamicTrainModel.java:87)
	at mtr.model.ModelTrainBase.render(ModelTrainBase.java:49)
	at mtr.client.ResourcePackCreatorProperties.render(ResourcePackCreatorProperties.java:215)
	at mtr.screen.ResourcePackCreatorScreen.render(ResourcePackCreatorScreen.java:495)
	at net.minecraft.class_757.handler$bfb000$renderLevel(class_757.java:3020)
	at net.minecraft.class_757.method_3188(class_757.java:1068)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mtr.mappings.ModelMapper.render(ModelMapper.java:83)
	at mtr.model.ModelTrainBase.renderOnce(ModelTrainBase.java:77)
	at mtr.client.DynamicTrainModel.lambda$render$4(DynamicTrainModel.java:173)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at mtr.client.DynamicTrainModel.lambda$render$5(DynamicTrainModel.java:167)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at mtr.client.DynamicTrainModel.render(DynamicTrainModel.java:87)
	at mtr.model.ModelTrainBase.render(ModelTrainBase.java:49)
	at mtr.client.ResourcePackCreatorProperties.render(ResourcePackCreatorProperties.java:215)
	at mtr.screen.ResourcePackCreatorScreen.render(ResourcePackCreatorScreen.java:495)
	at net.minecraft.class_757.handler$bfb000$renderLevel(class_757.java:3020)
	at net.minecraft.class_757.method_3188(class_757.java:1068)

-- Affected level --
Details:
	Chunk stats: 1521, 1021
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,4,224), Section: (at 0,4,0 in -3,0,14; chunk contains blocks -48,-64,224 to -33,319,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 3806 game time, 3806 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, KCR pack

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 925166592 bytes (882 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: unknown
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c8d
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Graphics card #1 name: Intel(R) HD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x591b
	Graphics card #1 versionInfo: DriverVersion=31.0.101.2111
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30766.36
	Virtual memory used (MB): 22267.75
	Swap memory total (MB): 6328.50
	Swap memory used (MB): 1389.07
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 6.3.49
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19
		fabric-api: Fabric API 0.64.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.0+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.2+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.32+70efcffe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.6+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.9+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.17+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.14+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.12+c0ae659d90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.14+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.2+70efcffe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-tree-chopper: Fabric Tree Chopper 0.8.10
			cloth-config: Cloth Config v8 8.2.88
				cloth-basic-math: cloth-basic-math 0.6.1
			fabric-language-kotlin: Fabric Language Kotlin 1.8.4+kotlin.1.7.20
				org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
				org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
				org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
				org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
				org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
				org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
				org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
				org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
				org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
				org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
				org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
			fiber: fiber 0.23.0-2
			fiber2cloth: Fiber To Cloth 4.0.0
		fabricloader: Fabric Loader 0.14.10
		flymod: Fly Mod ${version}
		java: OpenJDK 64-Bit Server VM 17
		jsblock: Joban Client Mod 1.19.2-1.1.5-hotfix-1
		londonunderground: MTR London Underground Addon 1.19.2-3.1.0-1.2
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		morecommands: MoreCommands 4.0
		mtr: Minecraft Transit Railway 1.19.2-3.1.0
		squaremap: squaremap 1.1.6
			adventure-platform-fabric: adventure-platform-fabric 5.4.0-SNAPSHOT
				net_kyori_adventure-api: adventure-api 4.11.0
				net_kyori_adventure-key: adventure-key 4.11.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.1.0
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.11.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.11.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.11.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.11.0
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			cloud: Cloud 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-core_: cloud-core 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-services_: cloud-services 1.8.0-SNAPSHOT
				fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
				io_leangen_geantyref_geantyref: geantyref 1.3.13
			cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.8.0-SNAPSHOT
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
	Launched Version: fabric-loader-0.14.10-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/KCR pack (incompatible)
	Current Language: English (United Kingdom)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	Server Running: true
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable

**Comment by kettle-7** [comment]
You either have a folder without any parts or a part that's not inside a folder, both of these cause crash

**Comment by jonafanho** [comment]
The Resource Pack Creator item will be reworked in 4.0.0. Thanks.
