### ISSUE TITLE
增加紅石控制月台門的特性

### ISSUE THREAD

**Issue by pokOSlanx** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#552]
就像#59 所提到的那樣，**_使用紅石電路控制月台門_**真的有必要。
就比如在列車發生什麼恐怖情況（比如軌行區起火，有人在列車範圍內投放某些有毒藥劑，比如瞬間傷害藥水），有時候列車關門了，而前面區間的列車還沒有離開，列車只能停在車站待避。這時候打開月台門完全可以逃出來，但是模組只准許列車到站後才會打開月台門。而等到列車到達下一站，人都快要沒了。而且列車停穩後還有一段時間才能打開車門。萬一遊戲是極限模式或者沒打開死亡不掉落，這樣子的話就真的太恐怖了。

額外添加一個：**_在軌行區側點擊月台門可以直接打開_**
再比如上面的問題，有時候列車關門了，而前面區間的列車還沒有離開，列車只能停在車站待避，這時候如果有人投放藥物，人們還可以通過月台門逃出來。
或者某個人手滑不小心長按了下車熱鍵，就會被困在軌行區。被困在軌行區的話就只能等下一班列車。可是有些多人聯機的列車間隙並不能像港鐵那樣2分鐘一班（有時候列車到站間隙可以達到10分鐘），這樣子打開月台門走出來就顯得非常有必要了。

**Comment by YYLWZDXPGD** [comment]
我觉得应该直接使用驾驶室或者仪表板来调整会更好一点吧，或者添加一种新的物件，用红石很难操控吧

**Comment by YYLWZDXPGD** [comment]
呃，谁玩MTR会开极限模式啊喂，要么创造，要么生存好吗
不过你们的服务器都不是选取人给他权限而是直接打开权限的吗？

**Comment by jonafanho** [comment]
Duplicate of #59
