### ISSUE TITLE
Catenary & Wire of railway

### ISSUE THREAD

**Issue by Forest103** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#56]
### The main point of this Request:

1. add Overhead Line (Catenary)
2. add Pantograph
3. add Utility pole

As I know the electrical train is use the electricity from the:
1. Overhead Line (Catenary)
2. 3rd rail
3. 4th rail

 And MTR is using the Overhead Line (Catenary) to give electricity to the train.

# Point 1 - add Overhead Line (Catenary)

Overhead Line (Catenary) is a wire that is fixed in the air by Utility pole.

There are **3** type of Overhead Line, MTR have use two of them.

They are:
1. Chain suspension
2. Rigid suspension

### Chain suspension
The chain suspension connects the conductor and the load-bearing wire with a suspension cable, which solves the problem of small span and hard spots in simple suspension. Therefore, it is used extensively in urban rail transit and long-distance, high-speed, and large-span electrified railways.

The picture of Chain suspension in real life:
![image](https://user-images.githubusercontent.com/83854276/120081377-f11f2900-c0ef-11eb-82f5-84311d2f8cff.png)

There is a important thing you are requires to know, in order to not broke the contact shoe of Pantograph, Chain suspension is set up as a "z".
The follow picture can help you to understand it.
![Catenary Z](https://user-images.githubusercontent.com/83854276/120092471-97e1e480-c145-11eb-8746-b261ca6e36c7.png)

### Rigid suspension
Rigid suspension is a new type of suspension in which hard metal bars (usually copper bars) replace soft wires. With the development of material science and structural mechanics , rigid suspension takes advantage of the large contact area and low resistance of 3rd rail or 4th rail supply , and overcomes the shortcomings that the rail is too heavy to be suspended. When urban rail transit runs from an underground route to an over ground route, it can directly transition to chain suspension without changing trains.

The picture of Rigid suspension in real life:
![After Edit](https://user-images.githubusercontent.com/83854276/120081131-6c7fdb00-c0ee-11eb-9a75-71817ff1ac3c.png)

The Pantograph will sticky to the contact wire of Overhead Line (Catenary)

# Point 2 - add Pantograph

Pantograph is an apparatus mounted on the roof of an electric train to collect power through contact with an overhead line (Catenary).
***However please don't think it is Trolley pole, they are two different thing, Pantograph is the next generation of Trolley pole***

### Pantograph normal have two state, one is raised and other is lowered.
- When raised, the contact shoe of Pantograph will sticky to the contact wire of Overhead line (Catenary)
- When lowered, the contact shoe of Pantograph will lower down and not sticky to the contact wire of Overhead line (Catenary)

The follow is the picture of Pantograph in real life

### Sp1900 - In raised

![image](https://user-images.githubusercontent.com/83854276/120079352-faa39380-c0e5-11eb-9fdb-8f73886d2cc4.png)

# Point 3 - add Utility pole
A utility pole is a column or post used to support overhead lines (Catenary) and various other public utilities, such as electrical cable, fiber optic cable, and related equipment such as transformers and street lights.

In railway, Utility pole is used to support overhead lines (Catenary).

# More Resource

The video show Chain suspension & Pantograph & Utility pole
https://youtu.be/N_9IA5GMqfU
### Please be mind this video is not make by me.

# A word want to tell you

Catenary & Wire of railway, is a difficultly thing. It not something can easily to understand as 1+1=2.
I hope you will not get too fatigue on this topic.

**Comment by jonafanho** [comment]
Thank you for this detailed suggestion! Since this is not a core feature, I might add it when I have more time in the future. Thank you for posting links to other resources as well.

**Comment by jonafanho** [comment]
I think this feature has been done pretty well by the [MTR Station Decoration](https://github.com/AIDA64S/MTR-Station-Decoration-Addon) mod. At this moment I think it would be better to leave it as a separate mod.
