### ISSUE TITLE
希望自動隧道建築速度可調

### ISSUE THREAD

**Issue by mike-brown8** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#564]
**Is your feature request related to a problem? Please describe.**
當我建築隧道和隧道地面時，我是用模組裏的隧道（墻壁和挖掘）建築工具和隧道地面建築工具，可是由於我在伺服器中，它構建的及其緩慢，通常一條數公里（數千個格）的3*4隧道需要構建約3到6分鐘，可是我如果使用WorldEdit進行構建，僅需求30秒鐘左右，這個設定浪費了我的時間并且沒有充分利用服務器性能。

**Describe the solution you'd like**
希望能夠添加自動隧道墻壁、自動隧道開掘和自動橋梁工具的建築速度調節功能。并且伺服器操作員（OP）可以通過指令的方式修改建築速度且不需要重新啓動伺服器。

**Additional Information**
順便提一句，若是隧道墻壁的上面可以有兩層就好了，這樣開鑿穿過河流不會顯示滴水動畫。

我是一名使用簡體中文的Minecraft玩家，若Issue中有些許語法錯誤或用詞不當，請諒解。感謝您創造這個mod。

**Comment by 52PD** [comment]
见了好几个建议加快桥梁建设速度的，建议加快隧道建设速度的还是头一次😂。

不过看了一下MTR论坛那边的解释，加快桥梁/隧道速度目前来讲估计是行不通吧。。。（论坛那边解释把桥梁建造器速度设成的现在这种速度是为了防止内存突然过大而导致突然崩溃）即使是要加入可调建造速度估计最快速度也就只会设到现在这么快🤔

**Comment by XHG78999** [comment]
> 见了好几个建议加快桥梁建设速度的，建议加快隧道建设速度的还是头一次😂。
> 
> 不过看了一下MTR论坛那边的解释，加快桥梁/隧道速度目前来讲估计是行不通吧。。。（论坛那边解释把桥梁建造器速度设成的现在这种速度是为了防止内存突然过大而导致突然崩溃）即使是要加入可调建造速度估计最快速度也就只会设到现在这么快🤔

内存突然过大？估计是内存泄漏
不愧是Bugjump，区块加载问题一堆

**Comment by 52PD** [comment]
> 内存突然过大？估计是内存泄漏
> 不愧是Bugjump，区块加载问题一堆

大概率是这种😂（话说好久不见啊）

**Comment by XHG78999** [comment]
> > 内存突然过大？估计是内存泄漏
> > 不愧是Bugjump，区块加载问题一堆
> 
> 大概率是这种😂（话说好久不见啊）

要么可以像之前的Real-Time Scheule强制装前置（MemoryLeakFix之类的）或者直接弄个钩子造16格F3+A一回，强制重置内存

**Comment by mike-brown8** [comment]
MemoryLeakFix是个好主意

**Comment by mike-brown8** [comment]
还有人注意到我所提出的双层隧道顶的需求吗？

**Comment by 52PD** [comment]
> 还有人注意到我所提出的双层隧道顶的需求吗？

这个估计因为为什么异议所以就没人提了吧😂
