### ISSUE TITLE
Add new show style for route sign to only show route information|增加只顯示線路名稱的路線牌樣式

### ISSUE THREAD

**Issue by kinegratii** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#572]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

As we known, the heading of route sign show the destination of a platform.This means a route sign may link a platform and is placed near a platform.
目前，路線牌的頂部顯示的是站臺編號和路線的目的地，這意味著一個路線牌通常是和一個站臺相關聯的，放置的地方通常是靠近一個站臺。

But if I put the route sign on the entrance of a station or transfer area, a route sign contains line name is more needful.
如果在其他地方放置路線牌時（比如地鐵站入口，換乘區域的多個路線牌），更需要的是路線名稱，而不是具體的站臺。

A new show style can be added, which contains these changes. (See last route sign in demo picture)

1) the heading show the route name,not the destination.And no arrow is not shown.
2) the route that train alrealy travelled show the normal color, not grey color.

建議添加新的顯示樣式（參見示例圖的最後一個路線牌）：
1) 頂部顯示的是路線名稱，而不是站臺和目的地。不顯示箭頭。
2) 列車已經行駛的線路按正常的線路顏色著色，而不是變灰。

User Operation:right click with brush to toggle this style.
用戶操作：使用刷子右鍵切換。

Demo Picture

![2022-12-13_00 41 4600](https://user-images.githubusercontent.com/9875406/207264485-9ea3663f-371a-4f8d-8400-04dd470aa3fc.png)

**Additional Information**

No.

**Comment by 52PD** [comment]
出现了，非现实中港铁出现的风格请求😂（港铁不会在地铁出入口和换乘通道内摆线路牌）
不过话说如果要加个显示线路名的线路图的话我觉得在你的建议下再加个在现有版本中把站台号换成线路名的会更合适一些。毕竟有些时候可能会遇到换乘通道换乘的其中一条线路只能去其中一个方向这种情况（虽然很罕见）

**Comment by pokOSlanx** [comment]
> 出现了，非现实中港铁出现的风格请求😂（港铁不会在地铁出入口和换乘通道内摆线路牌） 不过话说如果要加个显示线路名的线路图的话我觉得在你的建议下再加个在现有版本中把站台号换成线路名的会更合适一些。毕竟有些时候可能会遇到换乘通道换乘的其中一条线路只能去其中一个方向这种情况（虽然很罕见）

没有吧，其实这港铁也是有的
比如蓝田地铁站1、2月台（废话，蓝田就两月台）就是大大的“觀塘綫Kuwn Tong Line”
但是很少，反正目前我只发现在蓝田、调景岭有……
蓝田是在月台，调景岭是在大堂
并且在香港铁路大典也有用到这种格式（）但毕竟那不是港铁

**Comment by jonafanho** [comment]
Duplicate of #397
