### ISSUE TITLE
Some display bugs of Japanese text

### ISSUE THREAD

**Issue by ChihyuenWang** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#576]
**Expected Behaviour**
N/A

**Actual Behaviour**
Some Japanese text in this MOD doesn't display properly.

**Reproduction Steps**

1.The Japanese text of "Use custom MTR fonts" option can't be displayed properly, because it's too long.
2.The Japanese introductory text for all "Tunnel Wall Creator" items can't be displayed properly, because the line break "\n" doesn't seem to be working.

**Crash Report**
N/A

**Screenshots**
![Snipaste_2022-12-16_15-25-34](https://user-images.githubusercontent.com/12523783/208046888-5fa84573-6f6f-42a1-9176-e1cf1997b80b.png)
![Snipaste_2022-12-16_15-25-52](https://user-images.githubusercontent.com/12523783/208046903-bfd216ba-07d3-4004-8f09-433fe0226e88.png)
![Snipaste_2022-12-16_15-26-11](https://user-images.githubusercontent.com/12523783/208046911-a1b9fa55-ed91-4137-a2f7-d55c5f4bfe02.png)

**Environment**

- Minecraft Version: 1.19.2
- Installed Mods:Minecraft Transit Railway v1.19.2-3.1.11

**Additional Information**
N/A

**Comment by XHG78999** [comment]
Maybe it isn't a bug. Looks like you are Japanese? You can replace it to some shorter words on the offical Crowdin.

**Comment by mull1111** [comment]
3つ目の画像のバグは、マインクラフトの問題です。
1.19.3で修正されています。
最新版にしてください。

The bug in the third image is a Minecraft issue.
It has been fixed in 1.19.3.
Please make sure you have the latest version.

**Comment by mull1111** [comment]
また、私なりに、１つめと２つ目の画像の、文字を減らしました。
MTRフォントを使用する。（対応していない場合もあります）
としました。
少し短くなっているはずです。

Also, in my own way, I reduced the text in the first and second images.
Use MTR font. (In some cases, this may not be supported.) I also reduced the text in the first and second images.
I have changed the font to
It should be a little shorter.

**Comment by mull1111** [comment]
MTRフォントを使用する。（一部のコンピューターでは使えません）
も、いれました。

Use MTR fonts. (not available on some computers) is also included.

**Comment by mull1111** [comment]
もしくは、マインクラフトのビデオ設定から、GUIのサイズを小さくしてください。（1や2のサイズを推奨します）

Alternatively, go to the video settings in Minecraft and reduce the size of the GUI. (size 1 or 2 is recommended)

**Comment by XHG78999** [comment]
> もしくは、マインクラフトのビデオ設定から、GUIのサイズを小さくしてください。（1や2のサイズを推奨します）
> 
> Alternatively, go to the video settings in Minecraft and reduce the size of the GUI. (size 1 or 2 is recommended)

He'd like to have a better using on some small computer, like my HP Elitebook with a 1380x720 small screen.

**Comment by jonafanho** [comment]
Seems like this is caused by long translations on Crowdin. I will close this for now, as I am reworking some of the translations and GUI screens.
