### ISSUE TITLE
More features for planes: Landing gears, jetways, more planes, Airport utilities

### ISSUE THREAD

**Issue by chortle3** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#618]
**Hello MTR Mod.**

I would like to add more features for planes for the MTR Mod.

**1. Landing Gears**
In the mod, the planes don't have landing gears, shown here.
![landing gears a320](https://user-images.githubusercontent.com/94771839/216224314-1c63d01e-563b-4bc4-9861-cb0450a64ef5.png)
I would like to add so that if planes are on the ground, the landing gears are shown.
During taxiing and takeoff, the landing gears are shown, after takeoff, the landing gears will be retracted, then when landing, the landing gears show up.

**2. Jetways**
You need to add Plane Platforms to Minecraft Transit Railway.
1. Make a jetway (could be any block or just Airstairs)
2. Use the Platform Station Rail to make the plane stop at the gate!
3. Place 3 plane platforms in the exit of the jetway that leads to the plane (max height 3 blocks)
4. Enjoy!
![Hanoi_jetway](https://user-images.githubusercontent.com/94771839/216234362-bfb42e46-1c04-49d3-8714-

bee190be290a.png)

**3. Add more planes + edit the A320 to add Business Class**

Add more planes to MTR Mod and add Business Class to A320.

**A320-200**
2-2 business class configuration
2-2 economy class configuration

**1. B737-800**
2-2 business class configuration
2-2 economy class configuration

**2. A330-300**
1-2-1 business class configuration
2-3-2 economy class configuration

**3. B757-200ER**
2-2 business class configuration
3-3 economy class configuration

**4. B787-8**
1-2-1 first class configuration
1-2-1 business class configuration
2-4-2 economy class configuration

**5. B777-300ER**
1-2-1 first class configuration
1-2-1 business class configuration
2-4-2 economy class configuration

**6. A350-900**
1-2-1 first class configuration
1-2-1 business class configuration
2-4-2 economy class configuration

4. Plane / airport utilities
Add airport utilities for MTR Mod.

1. Airport Signs
You can enter text and icons and add more lines. Text lines can be added up to 3.
![2bcrkr1](https://user-images.githubusercontent.com/94771839/216241294-c93e6a2b-7b0e-4583-809c-eb4cf1ae2b50.png)

2. Airport PIDS
This shows all the flights on the gates (or platforms), departures and arrivals.
![arrival-and-departure-screens-at-terminal-3-at-lester-b-pearson-international-DT5K50](https://user-images.githubusercontent.com/94771839/216241799-ad7436e0-ad14-486b-96fe-c03b26c498d3.jpg)
![MUCFIDS](https://user-images.githubusercontent.com/94771839/216241806-040632e0-5d45-4e00-9828-ef2b239caef4.jpg)

3. Airport Ticket Check-In, Airport Ticket entrance/arrival
This allows you to get airport tickets with emeralds or money.
1. Build a check-in/go to the check-in counters
2. Buy a ticket of any flight
3. Go enter the airport with your ticket (Airport Ticket Enterance)
4. Exit with your airport ticket when arrival (Airport Ticket Arrival)
5. Done!

I think you can add more features! Thanks!

**Comment by 52PD** [comment]
> 3. Add more planes + edit the A320 to add Business Class

Once again, stop asking for adding new vehicles (both trains, planes, or other transit vehicles).👎

If you want more transit vehicles types, create resource pack by yourself. 

If you don’t know how to create resource pack or really want Jonathan add vehicles you want to the mod officially, support him on Patreon.

**Comment by Neon4UltraPlays** [comment]
> If you want more transit vehicles types, create resource pack by yourself.
> 
> If you don’t know how to create resource pack or really want Jonathan add vehicles you want to the mod officially, support him on Patreon.

I can't believe you are so rude to me, trying to reject my suggestion. I am just adding ideas when you are trying to ruin people's ideas. Try to be considerate.

**Comment by Neon4UltraPlays** [comment]
> > 👎 If you want more transit vehicles types, create resource pack by yourself.
> > If you don’t know how to create resource pack or really want Jonathan add vehicles you want to the mod officially, support him on Patreon.
> 
> I can't believe you are so rude to me, trying to reject my suggestion. I am just adding ideas when you are trying to ruin people's ideas. Try to be considerate.

**Comment by Neon4UltraPlays** [comment]
> 
> Once again, stop asking for adding new vehicles (both trains, planes, or other transit vehicles).👎
> 
> If you want more transit vehicles types, create resource pack by yourself.
> 
> If you don’t know how to create resource pack or really want Jonathan add vehicles you want to the mod officially, support him on Patreon.

I can't believe you are rude to me and others. I am just making ideas when you are flotting around ruining people's suggestions. Try to be more considerate!

**Comment by 52PD** [comment]
> I can't believe you are rude to everyone and others. They are just making ideas when you are flotting around ruining people's suggestions. Try to be more considerate!

Making ideas not mean to give something is impossible or not real or breaking rules, OK?

First, no matter on Discord or MTRBBS, it already mentioned that only Patreon supporter can ask for adding new vehcles.

Second, why don't you think the reason there is a tool called resource pack creater?

Third, considerate doesn't mean can accept everything, especially some breaking the rules, understand?

**Comment by jonafanho** [comment]
Other than the plane requests, the other items seem to be purely cosmetic. Closing this for now.
