### ISSUE TITLE
Incline lifts

### ISSUE THREAD

**Issue by valbuilds** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#634]
**Is your feature request related to a problem? Please describe.**
No, but it's a feature to increase realism and customizability.

**Describe the solution you'd like**
Putting lifts on escalators saves space and time! Here's some examples.
> *Source: [https://www.fourway.co.uk/](https://www.fourway.co.uk/)*
![img1](https://www.fourway.co.uk/img/dynamic/news/9/image2_DSC_0882.JPG)

>*Source: [https://www.railway-technology.com/](https://www.railway-technology.com/)*
![img2](https://www.railway-technology.com/wp-content/uploads/static-progressive/nri/railway/news/Crossrail%20incline%20lift.jpg)

> *Source: [https://www.malaymail.com](https://www.malaymail.com)*
![img3](https://media2.malaymail.com/uploads/articles/2021/2021-08/InclinedElevatorTokyo_250821.jpg)

**Comment by jonafanho** [comment]
This is now possible in 4.0.0, thanks!
