### ISSUE TITLE
How to repeat instructions?

### ISSUE THREAD

**Issue by Twistybees** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#644]
Where is the button to repeat instructions forever? I did it once before and now I can't find the button to save my life.

**Comment by kettle-7** [comment]
The first platform of your first route must be the same platform rail as the last platform of your last route in the train instructions, otherwise the button does not show.

**Comment by turtlegarden** [comment]
Yes, the first platform of the first route in the instructions must be the same as the last platform of the last route.
