### ISSUE TITLE
Cargo Loader/ Unloader Upgrades

### ISSUE THREAD

**Issue by lhwi** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#645]
Hi Jon, I’ve noticed that in the MTR Transit mod, there’s a few blocks currently not being used, ie Cargo Loaders/Unloaders. I do have a few suggestions.

1. Create a chest item, that can be used to store items that you wish to transport.

2. Allow the player to input its final destination as long as it’s connected to a line

3. Create a path finding AI that can send the item to the final destination like how the trains can find their next stop. If there’s no connections available, it’ll just say something like “unable to deliver”

I just see a lot of potential with cargo loaders in this mod.

**Comment by kettle-7** [comment]
Is this not the current function of cargo loaders  anyway ?

**Comment by lhwi** [comment]
Unfortunately, it doesn’t function in ways that I described it.

**Comment by jonafanho** [comment]
I think I want to group this with #586 as general cargo enhancements/rework.
