### ISSUE TITLE
Elevator door closing

### ISSUE THREAD

**Issue by michelle1574** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#649]
**Is your feature request related to a problem? Please describe.**
It would look real when elevators close doors after 10-30 seconds.
**Describe the solution you'd like**
After 10-30 seconds, elevator doors (inner and outer) close and to open it back, click the call button. And from inside, click a keyboard button to open it.

**Additional Information**
This would improve the realtinityness of the mod. But there should be an option after how much seconds the elevator doors close.
Like 0 seconds = Never

**Comment by jonafanho** [comment]
This should be added in 4.0.0, thanks!
