### ISSUE TITLE
add Door and Car number

### ISSUE THREAD

**Issue by kester0312** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#668]
**Is your feature request related to a problem? Please describe.**
I always don't know the Car or Door number.For example,the long of the platform is 12 Car but the train is only have 8 Car so stand at 12 Car will miss the train.

**Describe the solution you'd like**
add the Door and Car number sticker at platform gate/door or on the floor with no platform door/gate.

**Additional Information**
the sticker on the platform gate:
![platform  door ](https://user-images.githubusercontent.com/99643504/233831154-49192fae-04f7-457f-ba80-27561c9b7114.png)
the sticker on the platform door:
![platform  door](https://user-images.githubusercontent.com/99643504/233831218-d72ac806-5f0d-4e03-9c20-03f86f478cf1.png)
the sticker example:
![螢幕擷取畫面 2023-04-23 172353](https://user-images.githubusercontent.com/99643504/233831312-488eb134-c16e-4621-9d6d-09795804f1a4.png)
the sticker photoshop by myself on the platform:
![a fake photo](https://user-images.githubusercontent.com/99643504/233831353-7ed85916-0d63-4411-a40c-615185dde7ea.png)

**Comment by jonafanho** [comment]
This can be manually added using other mods like [Slideshow](https://github.com/teaconmc/SlideShow). Since you can have multiple train types running on a line with different car/door numbers, it will be hard to implement this.
