### ISSUE TITLE
建議mod添加新功能/It is recommended to add new functions to the mod（Google Translate, it is inevitable that there will be some mistakes.）

### ISSUE THREAD

**Issue by YYLWZDXPGD** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#671]
1.票價改進
目前的計算公式對學生不友好，建議改成：入閘閘區+出閘閘區，這樣更方便理解。
2.更好的頭等
頭等不應該只是一個擺設，應該增加詳細的代碼片段（自定義數據包）
比如，可以這樣
“first_class”:true，此字段若為真則開啓頭等，若為假（false）則不開啓頭等）
“cars”:8，此字段固定這種列車必須為幾節車廂
“first_class_car”:5，此字段設置頭等車廂在第幾節（車頭始終為1）
“first_class_texture”:     ，此字段為頭等車廂的單獨紋理
“first_class_dollars”:114，此字段為頭等車廂額外收費幾美元，不管怎樣，只要進入了頭等車廂，就會扣費。
1. Ticket price improvement

The current calculation formula is not friendly to students. It is recommended to change it to: entry gate area + exit gate area, which is more convenient to understand.

2. Better first class

The first class should not be just a decoration, but a detailed code fragment (custom data package) should be added.

For example, it can be like this.

"First_class": true, if this field is true, it will start, etc. If it is false, it will not start, etc.)

"Cars": 8, this field must be several cars to fix this kind of train.

"First_class_car": 5, this field sets the first-class carriage in which section (the front is always 1)

"First_class_texture": , this field is the separate texture of the first-class carriage

"First_class_dollars": 114, this field charges an extra few dollars for first-class cars. Anyway, as long as you enter the first-class car, the fee will be deducted.

**Comment by Ultimate-USA-YT** [comment]
The Ticket Formula Currently is Better as it uses Absolute Value. Negative Zones Exist

**Comment by Gzline4-24hc** [comment]
增加一条
头等车厢门数不一样所以添加这个字段
“first_class_doors”:[false,true,false,true,false]如果为真则有门，如果为假则是窗户。
Add one
The number of first-class carriage doors is different, so add this field.
”First_class_doors“: [false,true,false,true,false] If it is true, there is a door, and if it is false, it is a window.
