### ISSUE TITLE
显卡驱动错误导致的蓝屏会导致存档内部的线路消失

### ISSUE THREAD

**Issue by Yexiaowei11** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#674]
显卡驱动错误导致的蓝屏会导致存档内部的线路消失，复制覆盖存档内的MTR文件恢复偶尔无法恢复
求解决方式

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
