### ISSUE TITLE
关于屏蔽门上方线路图的风格

### ISSUE THREAD

**Issue by Yexiaowei11** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#679]
新功能：
屏蔽门上方线路图的风格 (其他城市【通过设置修改】)

**Comment by RedsXi** [comment]
个人觉得其他mod做出来比较好，因为这个Mod主要模仿的是港铁

**Comment by Yexiaowei11** [comment]
我想的是可通过材质包修改风格

**Comment by RedsXi** [comment]
官方不知道会不会做，我研究下怎么搞（
&nbsp;


RedsXi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月14日(星期天) 中午1:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jonafanho/Minecraft-Transit-Railway] 关于屏蔽门上方线路图的风格 (Issue #679)





 
我想的是可通过材质包修改风格

**Comment by pokOSlanx** [comment]
首先你要明白的是这个模组模的是港铁
（模组没用地铁宋和华康宋我不同意（不是）

**Comment by jonafanho** [comment]
Duplicate of #196
