### ISSUE TITLE
餘額計分板嘅另外一個用處

### ISSUE THREAD

**Issue by pokOSlanx** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#684]
**Is your feature request related to a problem? Please describe.**
目前來講鐵路餘額入錢用嘅係綠寶石，但係一個玩家如果佢真係挖到綠寶石嗰話佢都有D唔太可能搭鐵路了
就好比你買咗車，你平時就唔會去搭港鐵了（要係油費俾得起嘅話）
但係現在貿然更改嘅話就肯定會對服務器造成不公平嘅影響，所以解決方法如下：

**Describe the solution you'd like**
係Minecraft入面，綠寶石仲有另外一個用途——同村民交易。係現實嘅港鐵入面每個車站都會有中銀仲有另外一個唔知道係乜嘢銀行的櫃員機。
按照上面嘅思路，在模組中可以加入一個叫“櫃員機”嘅功能性方塊。當用戶點擊櫃員機嘅時候可以將用戶選定嘅餘額從計分板扣除，轉換為綠寶石返還俾玩家。（不過噉樣嘅話餘額就有D似銀行卡了）
雖然哩個嘢可以用其他模組實現⋯⋯但係將佢加入到模組裡面會比較方便（如果唔係港鐵點解仲要支持WeChat Pay HK？）
或者⋯⋯讓村民可以收“八達通”並且加入“八達通機”物品？（但係噉樣就有D高級了）

**Additional Information**
毋圖片或者附件等

另外，哩個模組做的係真係好——佢令服務器的軌道交通更加方便。
@jonafanho

**Comment by jonafanho** [comment]
Duplicate of #359
