### ISSUE TITLE
新的方块

### ISSUE THREAD

**Issue by YYLWZDXPGD** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#686]
最近東鐵線月台門工程，我覺得這些也能加進遊戲里
1.金屬地板（月台方塊），可以放置月台閘門上去，適用於即將安裝屏蔽門的車站
![IMG_4194](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/d9c653ef-2221-4b01-a52d-33a7590ba1b7)
2.方大製造月台閘門（中間車廂）
![IMG_4192](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/c02afe7a-1499-4adb-a241-8f7f4969f05b)
![IMG_4198](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/079c87c8-ef4c-460d-b470-d579c8e3181f)
（可以自定義邊緣顏色）
3.方大製造車頭屏蔽門
![IMG_4196](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/651ee4f9-a6c3-4783-8d43-9d68476007f8)
4.方大製造預留屏蔽門（尾端）（可以自定義告示）
![IMG_4195](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/d3f1c111-c1b1-4387-976e-6320f41fd5f1)
5.玻璃擋板（尾端）
![IMG_4193](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/24fc09f1-5c69-4991-8fbc-d490fe7939ac)
6.東鐵線尖沙咀支線屏蔽門
![IMG_4197](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/7ee1177b-90d4-42a7-9628-539ef9f57a9e)
希望能加進遊戲
@jonafanho

**Comment by YYLWZDXPGD** [comment]
我已经在做了，可以加进游戏里吗？
@jonafanho

**Comment by YYLWZDXPGD** [comment]
这是东铁线金属地板半成品，因为下面白线实在太难对齐了，哪个大神来做一下吧！
This is a semi-finished metal floor of the East Railway wire, because the white line below is too difficult to align. 
[IMG_4495](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/911b3469-cfd4-4a9c-943b-6bbf823ef585)

**Comment by YYLWZDXPGD** [comment]
我不是很会写java，谁会也帮忙写一下吧

**Comment by YYLWZDXPGD** [comment]
我最近要去香港，我还是直接拍照吧
I'm going to Hong Kong soon. I'd better take pictures directly.

**Comment by jonafanho** [comment]
Duplicate of #196
