### ISSUE TITLE
Some requests for the MTR mod

### ISSUE THREAD

**Issue by CowSheep72** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#706]
**Is your feature request related to a problem? Please describe.**
I don't like that i can go outside of an 802 during operation. For others, no.

**Describe the solution you'd like**
1. Revamped 802
2. REMOVED
3. A MTR style map in-game

**Additional Information**
1. Revamp the 802 to have its floor more inside
2. REMOVED
3. Make an item showing the entire system(in game, different from the online map)

**Comment by YYLWZDXPGD** [comment]
ERL platfrom door is in #686

**Comment by jonafanho** [comment]
Thanks for your suggestions.

802: This has been fixed in 4.0.0.
System map in-game: This will cause huge performance issues especially if you have a large network. The online system map was created for this exact purpose.
