### ISSUE TITLE
Support for 1.7.10 and 1.12.2

### ISSUE THREAD

**Issue by diyamomd45** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#709]
I have a Minecraft Server with many Mods that are Important to our Server and we need automatic Trains very bad and this frustrates us.

Please make a Version of MTR for 1.7.10 and 1.12.2 because many good Mods that people like are on these Versions. 

Thank you very much. 
Have a Good Day
Sincerely Diyamomd

**Comment by cherbert** [comment]
No. 

And more than that - It's simply not possible. This mod uses functionality that didn't exist in those versions of Minecraft.

**Comment by Ultimate-USA-YT** [comment]
As Cherbert Said, We will Not Port to Version Before 1.16.5, One Reason is that John already has Lots of Work Being Done just to Keep Support of the Versions this Mod Supports

**Comment by Kenny-Hui** [comment]
No plan to port to anything older than 1.16 at the moment
