### ISSUE TITLE
Make ticket currency configurable.

### ISSUE THREAD

**Issue by shantih19** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#711]
Hi,
I really like the ticket system, but I'd love if there was a way to set a currency to use instead of emeralds (and maybe even set the exchange rates).
Is there already a way to do it that I may be missing?

**Comment by jonafanho** [comment]
Duplicate of #359

**Comment by ajh123** [comment]
@jonafanho 

Definitely not a duplicate of #359, #359 is about changing the shape of fare zones, this suggestion is about changing the item used to pay.
