### ISSUE TITLE
停站较多的长线路不能刷新路线 | Can't create the path of a long route

### ISSUE THREAD

**Issue by NTC2-MEMZ** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#715]
**Expected Behaviour**
在铁路仪表板中点击“刷新路线”后能立即成功创建路线
Create path successfully as soon as clicking "Refresh Path" in Railway Dashboard

**Actual Behaviour**
A clear and concise description of what actually happened.
点击“刷新路线”后，一直显示“正在刷新路线”，“刷新路线”按钮保持不能点击的状态
"Generating path" was always displayed after clicking "Refresh Path". "Refresh Path" kept unable to click

**Reproduction Steps**
Steps to reproduce the behaviour:

1.创建一条停站较多的长线路（出现问题的是轻轨线，长约3500格，停站18个，且与其他线路共用小部分路轨）
2.创建车厂并编辑指令，点击“刷新路线”按钮
1.Create a long route with a few stations. (light rail line, 3500 blocks long, 18 stations, shares some of track)
2.Create a depot, edit instructions and click"Refresh Path"

**Crash Report**
Attach a crash report to the issue.

**Screenshots**
https://img1.imgtp.com/2023/07/06/YRq5kGW1.png

**Environment**

- Minecraft Version: 1.17.1
- Installed Mods: Fabric API 0.46.1
                            Joban Client Mod 1.2.2
                            Lithium 0.7.5
                            Modmenu 2.0.17
                            MTR 3.2.2 Hotfix-1
                            MTR LU Addon 3.2.0-1.11
                            Phosphor 0.8.0
                            Sodium 0.3.4 build 13
                            Xaero's Minimap 23.5.0
                            Xaero's Worldmap 1.30.5

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
