### ISSUE TITLE
Pleasell me how to get OVERHEAD WIRES and PANTOGRAPHS please!!! im on singleplayer 1.19.4

### ISSUE THREAD

**Issue by thingy108** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#717]
please tell me how to get pantographs like in your lets play

**Comment by Ultimate-USA-YT** [comment]
Some Trains in https://discord.com/channels/763273460465270816/953329579567767572 have Pantographs

**Comment by kettle-7** [comment]
PLEASE TURN OFF CAPS LOCK WHEN WRITING ISSUE TITLES

**Comment by Kenny-Hui** [comment]
Overhead Wires are provided by the [Station Decoration](https://modrinth.com/mod/station-decoration) mod
Pantographs are usually custom trains made by the community, where the Pantograph is embedded to the model of the custom train.
