### ISSUE TITLE
Encountered an error during the sided_setup event phase [1.19] [PLEASE HELP]

### ISSUE THREAD

**Issue by rvglx** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#718]
I´m trying to add this mod to play with friends on a server, however when I'm starting the game I get this error message. Can someone please help me know what to do?
 Thanks

![Screenshot 2023-07-10 020709](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/139109009/8b2d9aa2-8940-4fee-8db4-6794d2d2811c)

Crash Report:
[crash-2023-07-10_02.06.39-fml.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/11998996/crash-2023-07-10_02.06.39-fml.txt)

Latest:
[latest.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/11998965/latest.log)

**Comment by kettle-7** [comment]
Do you have the latest 1.19.0 version of Architectury installed ?

**Comment by Tangerine2831** [comment]
Hi, So this is a ton of months later and I'm not really good with coding in the slightest. But I'm having the same issue as this person and me and my friend are trying to add this mod to our small personal mod pack, yet we can't get around this error message. If you have any tips or tricks, all knowledge will be appreciated.  And as you said, I have the Architectury api 1.19.0. So the most updated version.

**Comment by Kenny-Hui** [comment]
MTR 3.0.1 for 1.19.0 expects an older Forge version (**41.0.4**), w/ Architectury API **5.6.21**
Newer MTR version no longer supports 1.19.0, as such you are advised to update your Minecraft Version
