### ISSUE TITLE
这个模组的改进|Improvement of this mod.

### ISSUE THREAD

**Issue by YYLWZDXPGD** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#720]
# 中文
1.应该给所有的列车添加编号，而不是只给线路编号
例如：G114（喜），D3603,C8986,T18,Z35
G=高铁，D=动车，C=城际，T=特快，Z=直达
2.应该添加更多的列车
就是懒得做追加包而已，这么做是为了让MTR模组的高铁更丰富（毕竟广深港抢钱铁路也是港铁的）
3.高铁的站台显示屏
自动检测站台号、以及列车在当前显示屏是第几车还有列车编号和到达时间。
![IMG_4708](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/1428564a-5fbd-4686-975c-74bab072380c)
![IMG_4709](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/d13881b8-be82-4c84-819f-e8282e5d2506)
![IMG_4681](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/f3c95666-d7f4-4287-98bc-47079906f52d)
（没有加上地标，作者自己加罢）
呵呵，它结合了现实和齐齐玩服务器啊（登福浦和奥斯跛）

# English
1. All trains should be numbered instead of just giving line numbers
For example: G114, D3603, C8986, T18, Z35
G=Gaotie（high-speed rail）, D=Dongche（high-speed train）, C=Chengji（intercity）, T=Tekuai（express）, Z=Zhida（direct）
2. More trains should be added
I'm just lazy about making additional packages. I'm doing this to make the MTR module's high-speed rail more diverse (after all, the Guangzhou Shenzhen Hong Kong high-speed railway is also owned by MTR)
3. Platform display screen of high-speed rail
Automatically detect the platform number, as well as the number of trains on the current display screen, as well as the train number and arrival time.
![IMG_4708](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/0766023a-9f26-43f4-9436-6562a2445b8c)
![IMG_4709](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/90a516d7-fa6d-4000-a5be-59a25902ce7b)
![IMG_4681](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/128379352/2495d255-4fbe-4850-88a4-e55eeaeca239)
（Ha ha, it combines reality and let's play server together.）
(I forgot to put the display screen on the landmark. Let the author make his own logo.)

**Comment by YYLWZDXPGD** [comment]
# Pids附加篇 Pids add-on

**Comment by Jeffreyg1228** [comment]
高铁站 PIDS 的设计，可以参考下面 Lyt 的作品：
![铁道站台发车信息导视优化（旧版）](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/45725157/c87cf35d-976d-43c3-8a52-ae8646534c35)

**Comment by YYLWZDXPGD** [comment]
> 1. 个人认为给线路编号作为车次就足够了。
> 2. 高铁相关功能（包括港铁动感号列车）早在 2021 年底就已完成，处于等待发布阶段，见 [[Pending Train Model Review] CRH380A Vibrant Express #242](https://github.com/jonafanho/Minecraft-Transit-Railway/pull/242)。不过模组作者短期内可能没有发布计划。
> 3. 高铁站 PIDS 的设计，可以参考 [Lyt 的作品](https://weibo.com/1419044843/JtwJupshf)：
> 
> ![铁道站台发车信息导视优化（旧版）](https://user-images.githubusercontent.com/45725157/257022096-c87cf35d-976d-43c3-8a52-ae8646534c35.png)

呃，我做的是香港显示屏看清楚好吗

**Comment by YYLWZDXPGD** [comment]
如果这样，那么joban模组就要加大量字段了
如果采用我的：(屑中之屑的我不会弄代码片段，请自行脑补）
“hkhsr_pids_img”:{ 
“example_hkhsrpids”:{
“pids_text”:”下方告示”
剩下的明天再做了，我要睡了
