### ISSUE TITLE
Passenger Information Display System problem

### ISSUE THREAD

**Issue by freesomebodywh** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#725]
hello, ive been wondering, when i created routes from Place 1 to Place 2, and from Place 2 to Place 1 on my friends server, on the destination display at Place 1, where the depot is, it doesn't show every train that will depart to Place 2, but only the one that is awaiting at the depot, so trains coming from Place 2 dont display on the other platform, that there will be a train back to Place 2. Help.

**Comment by cherbert** [comment]
It's just the way it's coded. To avoid it you should make it so every train in your schedule has it's own siding. Just like in real life.

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this if you still encounter this issue with 4.0.0, thanks!
