### ISSUE TITLE
Lift Dore's and Displays are buggy in 1.20.1 fabric (alpha version of mod)

### ISSUE THREAD

**Issue by justinsanjp** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#727]
**Expected Behaviour**
Dore's should be open normally and blocks that placed/ destroyed are be placed or distroyed.

**Actual Behaviour**
Dore's don't open /coloses, blocks are buggy
And updates only after a rejoin or go to nether and back

**Reproduction Steps**
Steps to reproduce the behaviour:
Just build a lift and you have these errors.

1.

**Crash Report**
Attach a crash report to the issue.
No crashes 

**Screenshots**

**Environment**

- Minecraft Version: 1.20.1
- Installed Mods: MTR Alpha for 1.20

**Additional Information**
Anything else you want to add?

**Comment by Migu52** [comment]
In addition i have problems removing blocks. I need to select the remove elevator connector and then add block and then i can remov the block with the remove elevator connector. Why is that?

**Comment by kettle-7** [comment]
These are all known bugs with the 1.20 build. It will take a while before it's ready for a proper release. Also Jonathan is focusing more on the Minecraft Mappings project so not as much attention is going here.

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
