### ISSUE TITLE
Update Modern Elevators and Escalators

### ISSUE THREAD

**Issue by ShenxPresent** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#728]
**Is your feature request related to a problem? Please describe.**
Could you please update Modern Elevators and Escalators to the current MRT version? The memery leak bug on old version make it not playable mod at the most of time.

**Describe the solution you'd like**
Just a simple upadate if you could do it easily.

**Comment by Kenny-Hui** [comment]
Modern Elevators and Escalators is no longer being developed.
You are advised to switch to the MTR Mod for the latest bug-fixes and improvements, the world file should be compatible with each other.
