### ISSUE TITLE
Heeeeelp

### ISSUE THREAD

**Issue by OmenaYT20** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#734]
**Expected Behaviour**
I Play minecraft version 1.19.4 and i cant

**Actual Behaviour**
it dosnt let me play the mod

**Reproduction Steps**
Steps to reproduce the behaviour:

1.something

**Crash Report**
Not Crashed

**Screenshots**
I dosent have any

**Environment**

- Minecraft Version: 1.19.4
- Installed Mods: Minecraft Transit Railway

**Additional Information**
New version of then

**Comment by Ultimate-USA-YT** [comment]
Do you have Arcutectury (Forge) Or Fabric API (Fabric) Instaler?

**Comment by Ultimate-USA-YT** [comment]
I Ment Instaled

**Comment by OmenaYT20** [comment]
i cant find version 1.19.4 Arcutectury

**Comment by OmenaYT20** [comment]
Still i cant play the mod

**Comment by kettle-7** [comment]
![image](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/64388266/4cb2553b-a42d-4eef-bd82-7b5a6c269cd3)
You mean like this ? 

https://cdn.modrinth.com/data/lhGA9TYQ/versions/8y4xVR6z/architectury-8.2.89-forge.jar

**Comment by Kenny-Hui** [comment]
Please re-open with appropriate screenshot (Such as what is displayed on your screen) and Minecraft Log if the problem still exist, it is not possible to diagnose without any of these information.
