### ISSUE TITLE
Make the other dashboards craftable!

### ISSUE THREAD

**Issue by whiteeagle1985** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#736]
**Is your feature request related to a problem? Please describe.**
I'm very frustrated that you can only obtain the boat, cable car, and aircraft dashboards via creative. I play in survival, so not being able to craft those dashboards limits what I can build in the mod.

**Describe the solution you'd like**
Please add crafting recipes for the other dashboards, either with other materials, or by converting the train dashboard to the others.

**Additional Information**
I'd prefer this to be added to the 1.19.2 version and above, as that's what version I'm using for my Swag's Creative Building modpack.

**Comment by kettle-7** [comment]
If it gets added to one version it gets added to all

**Comment by whiteeagle1985** [comment]
> If it gets added to one version it gets added to all

Fair enough. I just thought I'd mention what version I'm playing on.

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this if you still encounter this issue with 4.0.0, thanks!
