### ISSUE TITLE
Can't get the mod to work

### ISSUE THREAD

**Issue by Nouser1976** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#739]
**Expected Behaviour**
Trains and routs appear as in the explanatory youtube video. My son is young but following each step. I am computer illiterate.

**Actual Behaviour**
He follows the youtube video. The routes are recognized, he can't find a starting square, and it's not adding stations/titles to those stations to the routes. The train will spawn, but won't navigate. He says it doesn't know where to go. It's minecraft 1.19.3, and the right mod file to my knowledge (chose it on forge).

**Reproduction Steps**
Steps to reproduce the behaviour: He loaded the mod and followed the youtube video. Win 10 computer, 16 gb ram, laptop with ryzen 5, and radeon graphics in case it matter. It doesn't crash so there isn't a crash report.

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version:1.19.3
- Installed Mods:Minecraft transit railway

**Additional Information**
Anything else you want to add? I hope this is enough. I really don't understand minecraft, the 1000 versions and all of this. My son can't generate emails like this. Too young, but he is very good at following the steps on youtube.

**Comment by kettle-7** [comment]
can't find a starting square ?

Has he placed down a platform rails long enough to fit the train ?

**Comment by jonafanho** [comment]
Has this been resolved? Please reopen if you haven't figured it out yet.
