### ISSUE TITLE
Added additional inbound sound files that reported errors on the server

### ISSUE THREAD

**Issue by Kino0208** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#740]
我为模组添加了额外的音效文件 并确保格式正确 且在单人模式下可以正常被广播器播放   但放在服务端上会报错 无法选择保存音频至广播器

为此我又打算为其他用不上的音效 以替换文件名字的方式放进模组里

以上操作都经过了sounds. json重新添加 并且确认过名字与格式没有问题

但是在服务端上运行 使用音频依旧报错！
------------------------------------------------------------------------------------------------------------------------------------------------
I added extra sound files to the module and made sure that they were formatted correctly and could be played by the broadcaster in single player mode, but when placed on the server there was an error and no option to save audio to the broadcaster

For this reason, I decided to replace the file name in the mod for other sound effects that I didn't need

The above operations have been re-added by sounds.json and the name and format have been confirmed

But running on the server using audio still reports errors!
[latest.log](https://github.com/jonafanho/Minecraft-Transit-Railway/files/12388076/latest.log)

**Comment by DreamUniverse843** [comment]
能提供一下 json 文件吗
似乎命名空间路径里有非法字符？
![image](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/53889721/9e5fd032-05a3-4b53-be99-a9d61a5e1146)

**Comment by Kino0208** [comment]
Of course. Sorry, it took me so long to see the message and reply to you.
Here is the json file
[sounds.json](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/files/13797756/sounds.json)

The following is a sound asset
[sounds.zip](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/files/13797758/sounds.zip)
Due to size restrictions, only the assets I added are included here.

**Comment by Kenny-Hui** [comment]
Minecraft by default does not allow Capital Letter as an identifier, you should name your sound `10line_xihaian` instead of `10line_XiHaiAn`.
This is a limitation imposed by Minecraft itself (And it doesn't work here on singleplayer either).
I suspect some mod you have installed on your client bypassed this limitation, for it to work universally your sound id must be lower case.
