### ISSUE TITLE
Add the following server fix version to download pages

### ISSUE THREAD

**Issue by Jissee** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#741]
I have built a version that can run on 1.20.1 forge server. You can add this file to the download pages if it is possible.
我编译了一个1.20.1forge服务器修复版，可以的话加到下载页里.

https://wwtm.lanzouq.com/iM3du1625p3i

**Comment by Jissee** [comment]
@kettle-7 Could you please have a look at this file I have built?

**Comment by DreamUniverse843** [comment]
建议你直接开 Pull Request 去把你的代码提交合并请求，而不是直接丢一个二进制文件。

I suggest you could open a pull request to merge your code into the repo instead of just giving a binary file.

**Comment by kettle-7** [comment]
Yeah sending binary files is a great way to make people think you're up to no good lol

**Comment by kettle-7** [comment]
but 1.20.x will be supported in 4.0.0; i don't think there's plans to support servers with 3.x and 1.20.x

**Comment by Kenny-Hui** [comment]
MTR 3.2.2 hotfix-2 for Forge should have fixed the issue
