### ISSUE TITLE
1.19.4 crash by connecting rail node to rail node using iron rail connector

### ISSUE THREAD

**Issue by nintendoroblox** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#744]

**Comment by Ultimate-USA-YT** [comment]
Can You Provide more Detail?

**Comment by nintendoroblox** [comment]
I was like watching the tutorial of the mod (0:25-1:40) and it told me to put the rail node and another rail node to the other side. Then I used the iron rail connector to connect the rail node but then my client had crashed and I got an error code 1 either I might have used the wrong version or it's the forge client 
![Screenshot 2023-08-27 114904](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/143301332/4960df5f-2375-4f32-86f5-1d066897c1ec)

https://github.com/jonafanho/Minecraft-Transit-Railway/assets/143301332/e0eb89e7-a0f6-4f10-b456-e2199964f240

**Comment by kettle-7** [comment]
Do you have the actual crash report ?

**Comment by nintendoroblox** [comment]
[crash-2023-08-27_19.17.55-fml.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/12448947/crash-2023-08-27_19.17.55-fml.txt)

**Comment by kettle-7** [comment]
It seems like either Java, Architectury or Forge itself is outdated. Make sure to update Java to the latest 1.17.x version and Forge and Architectury to the newest versions of each for 1.19.4.

**Comment by Kenny-Hui** [comment]
MTR 3.2.0 is not compatible with Minecraft 1.19.4, please update to 3.2.1 or above.
