### ISSUE TITLE
Faster Bridge Creators or More Tunnel/Wall Creators

### ISSUE THREAD

**Issue by hakuorai** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#747]
Using bridge creators on vertically stacked rail tracks is actually an efficient way to build bridges or tunnels in any shape I want. However, as bridge creators work too slowly, I have to replace them with tunnel/wall creators despite their height. 

So would you please optimize the bridge creators or simply add tunnel wall creators in other sizes like 3x1 or even 3x0? I believe that will help making building much easier & more fun.

(BTW, I was surprised at the speed difference between tunnel/wall and bridge creators, as I've thought they work in similar ways🤔.)

**Comment by kettle-7** [comment]
Sadly the bridge creators are about as fast as they can be without issues, especially if you're using slabs as the ballast. I would like to see other tunnel / bridge creator sizes such as width 1 etc though. I might work on that myself once my exams are over.

**Comment by anonymusdennis** [comment]
my solution was to call the tick function 100 times on tick instead of only once henc increasing build speed 
this might not be a beautifl solution but at least by including an option in the config this would make sense to implement anyways

**Comment by kettle-7** [comment]
> this is not true as i compiled the mod myself just to introduce this feature. the only problem was that by making it instant the serverlagged for a second. Other than that I found no issue

exactly you found an issue
that might not matter on a smaller server but if the let's play or any other big server slowed to a crawl or even crashed whenever someone wanted to make a tunnel or bridge we have a massive problem on our hands

**Comment by anonymusdennis** [comment]
then make it at least an config option

**Comment by anonymusdennis** [comment]
come on
