### ISSUE TITLE
Only Minecart in mod

### ISSUE THREAD

**Issue by sadrainbow123** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#749]
i installed it and i only have the minecart, how do i fix it?

**Comment by sadrainbow123** [comment]
version 1.20

**Comment by Ultimate-USA-YT** [comment]
How long is your Siding? If it is Less than 11 Meters (Blocks), Only Minecarts Spawn

**Comment by JiaqiYi** [comment]
your depot rail (yellow) must be longer than 12 meters.or there will only spawn minecart .to like reallife,please make it 152 meters long.

**Comment by Kenny-Hui** [comment]
Please make sure your siding is long enough to fit a train carriage
You can refer to the [Wiki](https://wiki.minecrafttransitrailway.com/mtr:trains) for the length required for each train to spawn.
