### ISSUE TITLE
Screen Door behavior/ 屏蔽门问题

### ISSUE THREAD

**Issue by FlySandwich4** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#755]
**Expected Behaviour** 
fabric 1.20.1 mtr mod : 
The Screen Door of the railway should work fine after placement

**Actual Behaviour** 
Screen Doors can not open or close automatically (when train arrives). It can not open or close even I complete the whole screen door block by right clicking it. I tried different things and sometimes the screen door recover and work with no reason.
屏蔽门不能正常的启动或关闭, 放置后只有一小部分并且需要用右键点击补全, 补全后也无法正常开门, 在进行随机操作后有几率可以正常开门

**Reproduction Steps**
Steps to reproduce the behaviour:
place the screen door where the train door opens, with platform block
放置屏蔽门在地铁/火车门的地方, 有站台

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version: 1.20.1 Fabric
- Installed Mods: Iris Shader, Sodium, Farmer's Delight, Fabric API, Dynmap, JEI

**Additional Information**
Anything else you want to add?

**Comment by Ultimate-USA-YT** [comment]
MTR for 1.20 and 1.20.1 is Extremely Buggy currently

**Comment by FlySandwich4** [comment]
Hi. After testing, I found that when I get away from the screen doors (out of its rendering positions) and get back, the screen door might recover. Also, when i close the server, wait 1 min, and reopen it. The screen doors recover after I get into the game. 

So, I am guessing the rendering related function has bug, like AABB getRender function in the DoorBase Class, or some functions else. I am not sure branch 1.20.x is the current branch for fabric MTR mod for 1.20.1 but I guess there is something wrong with the rendering function.

If you could give me some documentation or implementation way of this mod, I can contribute to fix this bug. Now, I can not understand the code structrue so much. Thank you so much for reading.

**Comment by Ultimate-USA-YT** [comment]
Uhh...
I'm a Dumb Dragon. I don't understand the mod code

**Comment by kettle-7** [comment]
> Hi. After testing, I found that when I get away from the screen doors (out of its rendering positions) and get back, the screen door might recover. Also, when i close the server, wait 1 min, and reopen it. The screen doors recover after I get into the game.
> 
> So, I am guessing the rendering related function has bug, like AABB getRender function in the DoorBase Class, or some functions else. I am not sure branch 1.20.x is the current branch for fabric MTR mod for 1.20.1 but I guess there is something wrong with the rendering function.
> 
> If you could give me some documentation or implementation way of this mod, I can contribute to fix this bug. Now, I can not understand the code structrue so much. Thank you so much for reading.

Thanks for the offer! It's a bit difficult though to justify fixing the bug in the current MTR version as version 4.0.0 will be released soon anyway and due to a change in how the mod renders things in that version the bug would likely be fixed there anyway.

**Comment by MilBuuket** [comment]
looks like mtr is a bug king
