### ISSUE TITLE
Adding a function to enforce a certain platform belongs to a station accurately.

### ISSUE THREAD

**Issue by DreamUniverse843** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#757]
When we have 2 stations which have overlapped regions, if we create platform in these region we could usually get unexpected problems.

For example, we have a Railway Station and a Subway Station which is under the Railway Station. In real life they're always overlapped, and now if we have a platform number 1 in the overlapped region, the station name performed usually switches between the two stations. However, we usually hope the platform 1 belongs to the Railway Station, or Subway Station.

Could MTR add this function to solve the problem? Or how could we solve it?(Is MTR has a priority to process the platform belongs to which station in overlapped region?)

![image](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/53889721/313c8016-3601-4aee-b1aa-4b93f6518b16)
For example, in this picture, **Xinting Station**(Railway Station area) and **Xinting Railway Station**(Subway Station area) are overlapped. How could we manually define the platform belongs to which station accurately?
In current MTR mod, the platform shows either **Xinting Station** or **Xinting Railway Station**, even self-switching and is unstable to maintain a certain station name.

**Comment by DreamUniverse843** [comment]
*Here's the content translated to Chinese(Simplified).
*这是此 Issue 内容的中文翻译对照。

当我们在两个车站的重叠部分新建站台时，站台和车站的所属关系会遇到各种奇奇怪怪的问题。

例如，我们在 MTR 内定义一个火车站和一个地铁站，且这个地铁站位于火车站正下方，类似**北京火车站**和**地铁北京站**的关系，这一布局在现实生活中非常常见。但是，如果我们在重叠区域新建站台，这个站台上显示的车站名称经常在两者间反复跳跃。很显然我们更希望让站台精确地属于某个车站而非反复横跳。

MTR 能否添加例如站台属于哪个车站之类的配置解决此问题？或者我们能否通过特定配置解决问题？或者 MTR 在处理类似情形时使用的是怎么样的一个优先级策略?

**Comment by jonafanho** [comment]
Related to #359
