### ISSUE TITLE
[Forge 1.19.2] Crash on boat depot creation

### ISSUE THREAD

**Issue by dagobertdu94** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#764]
**Expected Behaviour**
The marked area in the boat dashboard shouldn't crash the game, and let me create a new boat depot.

**Actual Behaviour**
The game crashed right after I marked an area for my boat depot.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Open boat dashboard and go to the Depots tab
2. Create a new depot and mark the area for it (_after marking the game will crash_)

**Crash Report**
https://pastebin.com/r0dZMMZ1

**Screenshots**

**Environment**

- Minecraft Version: 1.19.2 (_Forge 43.3.0_)
- Installed Mods: _listed at the end of the crash report_

**Additional Information**
Anything else you want to add?

**Comment by dagobertdu94** [comment]
EDIT: I found out that it isn't caused by the depot itself or its creation.
It seems that either the depot rail or the vehicle on that depot rail is causing the problem.
But I don't know why...

**Comment by blabla-bla12345** [comment]
Hi, I have the same issue. Have you already solved it?

**Comment by dagobertdu94** [comment]
> Hi, I have the same issue. Have you already solved it?

No, I couldn't solve it yet...

**Comment by Kenny-Hui** [comment]
Incompatibility with **MrCrayFish Framework** mod as FakeBoat passes `world` as `null`
https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/blob/87c987f660dac35832bb9373c7d7da8bd31e2abc/common/src/main/java/mtr/render/JonModelTrainRenderer.java#L246

Offending code no longer exists in upcoming MTR versions.

**Comment by dagobertdu94** [comment]
> Incompatibility with **MrCrayFish Framework** mod as FakeBoat passes `world` as `null`
> 
> https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/blob/87c987f660dac35832bb9373c7d7da8bd31e2abc/common/src/main/java/mtr/render/JonModelTrainRenderer.java#L246
> 
> Offending code no longer exists in upcoming MTR versions.

So it will be fixed for Forge 1.19.2 with the next update?
That would be great.

**Comment by dagobertdu94** [comment]
But now I have a technical question, why is it only occuring for boats and not even for trains and planes?
Or are trains and planes just ignored by the Framework mod?

**Comment by Kenny-Hui** [comment]
Pretty sure boat uses the vanilla Minecraft boat for the rowing animation, which is why it tries to create a fake vanilla boat entity
While trains and planes don't have any vanilla animation

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
