### ISSUE TITLE
Compability with Xaero's World Map

### ISSUE THREAD

**Issue by CokeStudios** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#770]
**Is your feature request related to a problem? Please describe.**
When I open the world map in the train, the player actually stopped, so does the train. (Visually)
When I close the world map, the player and the train will be 'teleported' into the position they should be.

**Describe the solution you'd like**
When I open the world map in the train, I can see that I'm moving, like in Journeymap.

**Comment by Kenny-Hui** [comment]
Related to #487
