### ISSUE TITLE
Route Display Just showing black 

### ISSUE THREAD

**Issue by curtbrad2019** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#772]
**Expected Behaviour**
the route Signs all of them are meant to show the trains stations and end station

**Actual Behaviour**
when assigning thr train to the route Signs or placing the platform doors that has the route on it just shows black please see pictures below 

**Reproduction Steps**
Steps to reproduce the behaviour: none 

1.

**Crash Report**
No Crash Report

**Screenshots**
I
![Train Selection Sreen](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/68022558/25968443-b323-4be9-a4f0-69af543773cf)
![Route Sign Standing](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/68022558/4bc030e8-ac0c-40f3-a95d-ebaf2bec42db)

**Environment**

- Minecraft Version:1.19.4 Fabric
- Installed Mods: Fabric API, jei, Joban Client, MRT Fabric, MRT LU Addon Fabric, MTR NTE, Worldedit, Xaeros Minimap
-

**Additional Information**
Just Need to know how i can get them to work

**Comment by jonafanho** [comment]
This can happen if the dynamic texture resolution is set too high in the mod settings. Also, please check if this issue still persists in 4.0.0. Feel free to reopen if that's the case.
