### ISSUE TITLE
Córas Iompair Éireann 8100 Class EMU

### ISSUE THREAD

**Issue by Vincent392** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#774]
**Is your feature request related to a problem? Please describe.**
The feature isn't related to a problem, I just want to see Irish trains in this mod.

**Describe the solution you'd like**
This EMU being added into the mod, Since the CIÉ8100 Class is probably the most iconic DART, and when I mean DART I'm not talking about the Dallas DART, I'm talking about the the Dublin DART.

**Additional Information**
The EMUs have had several variations since 1983 (A year before the EMUs were put into passenger service), so I'll leave images of said variations here.
![image](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/90470156/d31531b5-dc43-4199-ae90-c9209fd0ec84)
test train variation (1983- Sometime 1984)
![image](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/90470156/906f8604-04b1-4312-84b9-1544c9cb58ad)
Pre-Refurb A (1984- Sometime 2000)
![image](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/90470156/8e69017b-a141-4c40-898d-0c2f34940406)
Pre-Refurb B (sometime 2000-2006)
![image](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/90470156/0579a751-4856-44db-841b-37a23efe731c)
DART 25 (2009-2015 or so)
![image](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/90470156/11e1d764-cea4-4a2f-959f-e580ba22ceb3)
Current (2013-Present)

Also
[CIE8100Class.docx](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/files/13378673/CIE8100Class.docx)
I have a document on the EMU.

Should mention,
My skills on making trains for this mod suck.

**Comment by Ultimate-USA-YT** [comment]
Please don't Suggest Trains! Either Pay for the Diamond Rail Patrion or Model it Yourself!
