### ISSUE TITLE
Debugging tools

### ISSUE THREAD

**Issue by DeenOConnor** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#776]
**My problem**
Trains don't work and i have no idea why. I have 2 very short and almost identical railroads, one works, one doesn't. There isn't a clear and understandable reason for this, and the dashboard isn't mad at me, so i really can't see any way to identify the issue and figure out how to fix it. Later i built another small road with just 2 stations in a survival world and it just doesn't work at all. The dashboard says it can't find a path from the depot to the first station, but they're linked properly, and once again i don't understand what the issue is.

**My solution**
A dashboard with an assortment of tools for troubleshooting and possibly (i'd really like this option) an option to manually construct a path by linking rail nodes that the dashboard would accept wothout a question. Tools should at least consist of a log of a path creation to see where and why it fails (or doesn't), a path viewer that would outline where and how trains navigate and a measuring tool to make sure trains fit. Also, among those tools, i'd like to see an option to manually control a train with no restrictions, because now to my understanding there must be a path that the train should be able to follow automatically, but since this doesn't work, at least let me drive it manually.

**Additional Information**
These tools could help identify bugs and possibly even find workarounds. I think a lot of players would benefit from their existence, and they could be a very helpful learning tool to understand the logic of the trains better.

**Comment by cherbert** [comment]
Share you world and I bet I can find the issue in 5 seconds.

**Comment by jonafanho** [comment]
This has probably fixed in 4.0.0. Please verify and reopen this issue as needed.
