### ISSUE TITLE
[Fabric 1.20.1] The game cannot launch while using the mod

### ISSUE THREAD

**Issue by JoeJoe511777** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#778]
I was using fabric 1.20.1. When I launch the game with the mod, it failed to launch and said exit code 1. When I delate the mod, the game works normally.

Here’s my mod list:
Fabric API 0.91.0+1.20.1
Sodium 0.5.3
Iris Shaders 1.6.10 for Minecraft 1.20.1
Mod menu v7.2.2 for 1.20.1
Continuity 3.0.0-beta.4+1.20.1
Indium 1.0.27 for Minecraft 1.20.x/Sodium 0.5.3/Fabric API 0.89+
Minecraft Transit Railway FABRIC-1.20-3.2.2-hotfix-1
Joban Client Mod [1.20] v1.2.2

By the way, I was playing it in single player, not in the server.
Can you fix it please?

**Comment by kettle-7** [comment]
When the game closes it will come up with a window that has a button saying "view crash report", that's the actual useful information that we can use to help you

and exit code of 1 can be absolutely anything at all

**Comment by JoeJoe511777** [comment]
I think it’s the problem of the mod. The game works fine when I delate the mod.

**Comment by JoeJoe511777** [comment]
It looks like this:
![IMG_1058](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/152083511/3041d895-cdfc-4dd4-86e5-a282d5ea30e6)

**Comment by JoeJoe511777** [comment]
I’ve tried to reinstall Minecraft, reinstall Java and update all my drivers. It’s still crashing.

**Comment by JoeJoe511777** [comment]
Also, I was using JDK 21 and Windows 11.

**Comment by kettle-7** [comment]
for 1.16.5 and older you need to use jre 8 and for all newer versions jre 17 is required

**Comment by JoeJoe511777** [comment]
I’m in 1.20.1, doesn’t work even with jre 17

**Comment by JoeJoe511777** [comment]
Or is it the problem of Joban mod?

**Comment by JoeJoe511777** [comment]
When I delete MTR, I also deleted Joban mod

**Comment by Kenny-Hui** [comment]
Not enough information, please re-open if the problem persists in MTR 4
