### ISSUE TITLE
Game crashes with description "Initializing game"

### ISSUE THREAD

**Issue by NBGReal** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#783]
Here's the log: https://mclo.gs/5QbGwaj
My mod list:
![Screenshot 2023-12-08 191017](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/79307418/6a79412b-b4bd-458b-9674-a98c6963592a)

**Comment by CokeStudios** [comment]
Upgrade NTE, MSD, MTR mod to the newest version.

**Comment by Kenny-Hui** [comment]
Update the Station Decoration mod to the latest version
