### ISSUE TITLE
Mod loads up (seen in mod menu) but doesn't show up in the inventory UI

### ISSUE THREAD

**Issue by MellowMallow01** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#784]
**Expected Behaviour**
Mod to show a tab on the 2nd page of inventory UI

**Actual Behaviour**
It doesn't show in the 2nd page of inventory UI

**Reproduction Steps**
I have other mods that take up the 2nd page like Adorn, Automobility (This one might be causing the problem, but not sure), McCaw's Furniture, Immersive Aircrafts and Handcrafted. MTR was showing up when some of the above mods were not there, but ones the above mods are installed, it doesn't come up

**Environment**

Minecraft Version 1.20.1 (fabric loader version 0.15.1
Total 38 mods are installed but none affected this mod's behaviour before, only when some more mods were added to the 2nd page, this mod didn't show up in the inventory UI.

**Comment by Ultimate-USA-YT** [comment]
1.20.1 has the items in the Vanilla Tabs. And its not recomended yet

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
