### ISSUE TITLE
Allow non-player entity to board the train

### ISSUE THREAD

**Issue by JiaqiYi** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#787]
when a player(animal)try to get into the train when the door has bee closed,they will stan “in”the train,but when the train moves,they will still there.How strange !
the train cannot board any animal.When they tryto get into the train they will fal l down.
I canno put any block in the train and the block outside can go into the train.How strange!

**Comment by jonafanho** [comment]
Duplicate of #307
