### ISSUE TITLE
Solucion Bug MTR  with Ad Astra, Beyond Earth or Space Dimension

### ISSUE THREAD

**Issue by BichoMESP** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#790]
Solution until fixed in the mod

Example for Ad-Astra and Starwars Planets mod´s. Not all dimensions.

Datapack URL

https://github.com/BichoMESP/bug-mtr

**Comment by BichoMESP** [comment]
Ad Astra, with Forge version 1.20.1-1.15.16, I think has solved this problem.

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
