### ISSUE TITLE
[BUG] Cargo Loader/Unloader doesn't load/unload for stopped vehicles

### ISSUE THREAD

**Issue by CaptainAngle** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#792]
**Expected Behaviour**
When vehicle is stopped, over a cargo loader/unloader with stopped vehicles only selected, the train loads everything from the chest adjacent to the loader/unloader

**Actual Behaviour**
Nothing gets loaded onto the train, unless moving vehicles are allowed. If moving vehicles are allowed, it only picks up 2 items.
**Reproduction Steps**
Steps to reproduce the behaviour:
1. Build a simple line with 2 platforms.
2. Add a cargo loader with a chest under a platform
3. Add a cargo unloader with a chest under another platform
4. Place a stack of items in the loader's chest
5. Configure the loader to only work with stopped vehicles using a brush
6. Nothing comes to the chest by the unloader, nothing is picked up from the loader

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version: 1.20.1
- Installed Mods:
![image](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/35032968/16b16f47-a1e1-4303-a12a-449f43e238f1)

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
Grouped with #586 for cargo improvements/rework
