### ISSUE TITLE
Potential client-crashing conflict with Botarium

### ISSUE THREAD

**Issue by Fureniku** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#794]
**Expected Behaviour**
The game to not crash when opening a creative menu while MTR and Botarium are installed

**Actual Behaviour**
When Botarium 1.20.1-2.2.1 is installed alongside MTR 3.2.2-hotfix-2 and Architectury 9.1.12, the game crashes instantly on pressing E to open the inventory in creative mode.

Not tested in survival mode or on other versions. These are the latest versions of all mods.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Install the latest MTR, Botarium and Architectury on Forge 1.20.1
2. Load into a new creative gameworld
3. Attempt to open your inventory

**Crash Report**

[crash-2024-01-05_00.04.07-client.txt](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/files/13836549/crash-2024-01-05_00.04.07-client.txt)

**Screenshots**

https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/856762/9418bab0-3e8c-4952-85b3-ff8db931e898

**Environment**

- Minecraft Version: 1.20.1, Forge 47.2.0
- Installed Mods:
  - Botarium 1.20.1-2.2.1
  - Architectury 9.1.12
  - MTR 3.2.2-hotfix-2

**Additional Information**
This was initially reported to Botarium as they're the first-linked mod in the stack, but they are saying it's caused by MTR.
Original ticket: https://github.com/terrarium-earth/Botarium/issues/28

**Comment by kieran-s** [comment]
I had a similar issue running survival, it didn't always crash (sometimes did), but it lagged for a good 20 seconds when opening the inventory. Same errors as in the linked Botarium ticket.

**Comment by NoaHimesaka1873** [comment]
If there won't be 4.0 for 1.20.1 (there seems to be some chance), please at least backport this fix.

**Comment by Barry23333** [comment]
> ~If there won't be 4.0 for 1.20.1 (there seems to be some chance), please at least backport fix for this issue.~
> 
> Yeah, I just ported 4.0.0 to 1.20.1. Problem solved!

I found out that 4.0.0 version has only 1.20.4 version. I just want to know is there any way to port it to 1.20.1? Thank you!

**Comment by Kenny-Hui** [comment]
It has already been ported, just not made it into an official beta release yet.
You can use the [latest artifacts](https://nightly.link/Minecraft-Transit-Railway/Minecraft-Transit-Railway/actions/runs/9308152094) for 1.20.1.

However I have to mention that MTR 4 is in Beta, and the latest artifacts is even more experimental than the beta builds. Unless MTR is absolutely required for your gameplay, for average users it's recommended to stay on MTR 3 until MTR 4 officially comes out

**Comment by Barry23333** [comment]
Gotcha! Thank you so much!

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!

**Comment by dagobertdu94** [comment]
> This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!

@jonafanho 
Would it be possible to fix it in v3.2.2 Hotfix-2 because I can't merge my existing railways when updating to 4.0.0 without causing weird problems and somewhen the trains just stop driving without anything blocking them, but the game isn't crashing in any way and somehow it doesn't seem to log anything.
And creating a new world is no solution because we and my friends don't want to start with nothing again, and I need MTR for our connections between cities and we wanted to expand a little bit into space with Ad Astra too.

Or I could try to fix it myself if you tell me where in the repository I can find the code from v3.2.2 Hotfix-2.
If I don't misunderstand the error, the method just needs to return a non-null value and it should work...

**Comment by LokeYourC3PH** [comment]
> > This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
> 
> [@jonafanho](https://github.com/jonafanho) Would it be possible to fix it in v3.2.2 Hotfix-2 because I can't merge my existing railways when updating to 4.0.0 without causing weird problems and somewhen the trains just stop driving without anything blocking them, but the game isn't crashing in any way and somehow it doesn't seem to log anything. And creating a new world is no solution because we and my friends don't want to start with nothing again, and I need MTR for our connections between cities and we wanted to expand a little bit into space with Ad Astra too.
> 
> Or I could try to fix it myself if you tell me where in the repository I can find the code from v3.2.2 Hotfix-2. If I don't misunderstand the error, the method just needs to return a non-null value and it should work...

I had hoped for this too since the DB Train Pack is still stuck on MTR 3.2.2, but since this fix was never ported to 3.2.2, the option is either going with MTR 4 and this fix, or remove Botarium related mods and stay on 3.2.2

Blerg, I hate incidents like these 😫
