### ISSUE TITLE
Odd route maps

### ISSUE THREAD

**Issue by Trendysaucer795** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#795]
I expected to have a normal route map

Instead, the route map ended up looking odd

Steps to reproduce the behaviour:

1. Make some stations and connect them with several lines
2. Make a route map sign that uses several of those lines
3. See the odd looking route map

- Minecraft Version: 1.18.2
- Installed Mods: Too many to list
![IMG_20240105_135615196](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/115903645/c278b8db-d781-4ee4-a020-1c2f98d315f0)

**Comment by Leoparking** [comment]
看起来很正常啊，我的还只有一条线呢，你的都有交叉和折角，看上去很高大上啊
