### ISSUE TITLE
Workflow failed

### ISSUE THREAD

**Issue by YYLWZDXPGD** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#796]
Changing the workflow of Java files always fails, the error is"Process completed with exit code 1"
For example [#1473](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/actions/runs/7428988219)

**Comment by CokeStudios** [comment]
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:70: error: cannot find symbol

> Task :fabric:compileJava
		PLATFORM_JP_1 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_1"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_1
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:71: error: cannot find symbol
		PLATFORM_JP_1_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_1_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_1_INDENTED
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:72: error: cannot find symbol
		PLATFORM_JP_2 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_2"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_2
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:73: error: cannot find symbol
		PLATFORM_JP_2_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_2_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_2_INDENTED
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:74: error: cannot find symbol
                PLATFORM_JP_3 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_3"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
                ^
  symbol:   variable PLATFORM_JP_3
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:75: error: cannot find symbol
		PLATFORM_JP_3_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_3_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_3_INDENTED
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:76: error: cannot find symbol
		PLATFORM_JP_4 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_4"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_4
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:77: error: cannot find symbol
		PLATFORM_JP_4_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_4_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_4_INDENTED
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:78: error: cannot find symbol
		PLATFORM_JP_5 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_5"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_5
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:79: error: cannot find symbol
		PLATFORM_JP_5_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_5_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_5_INDENTED
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:80: error: cannot find symbol
		PLATFORM_JP_6 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_6"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_6
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/Blocks.java:81: error: cannot find symbol
		PLATFORM_JP_6_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_6_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_6_INDENTED
  location: class Blocks
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/fabric/src/main/java/org/mtr/mod/BlockEntityTypes.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
12 errors

> Task :fabric:compileJava FAILED

> Task :forge:compileJava
 > Running 'rename'
Stopping at requested step: /home/runner/.gradle/caches/forge_gradle/mcp_repo/de/oceanlabs/mcp/mcp_config/1.17.1-20210706.113038/joined/rename/output.jar
[02:[58](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/actions/runs/7428988219/job/20217011469#step:8:59):13] [main/INFO]: Writing debug log file accesstransform.log
[02:58:13] [main/INFO]: Access Transformer processor running version 8.0.7+8.0.7+master.43473d43
[02:58:13] [main/INFO]: Command line arguments [--inJar, /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/fg_cache/net/minecraftforge/forge/1.17.1-37.1.1/forge-1.17.1-37.1.1-injected.jar, --outJar, /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/fg_cache/net/minecraftforge/forge/1.17.1-37.1.1_mapped_official_1.17.1/forge-1.17.1-37.1.1_mapped_official_1.17.1.jar, --logFile, accesstransform.log, --atFile, /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/resources/META-INF/accesstransformer.cfg, --atFile, /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/_atJar_4/parent_at.cfg]
[02:58:13] [main/INFO]: Reading from /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/fg_cache/net/minecraftforge/forge/1.17.1-37.1.1/forge-1.17.1-37.1.1-injected.jar
[02:58:13] [main/INFO]: Writing to /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/fg_cache/net/minecraftforge/forge/1.17.1-37.1.1_mapped_official_1.17.1/forge-1.17.1-37.1.1_mapped_official_1.17.1.jar
[02:58:13] [main/INFO]: Transformer file /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/resources/META-INF/accesstransformer.cfg
[02:58:13] [main/INFO]: Transformer file /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/_atJar_4/parent_at.cfg
[02:58:13] [main/WARN]: Found existing output jar /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/fg_cache/net/minecraftforge/forge/1.17.1-37.1.1_mapped_official_1.17.1/forge-1.17.1-37.1.1_mapped_official_1.17.1.jar, overwriting
[02:58:16] [main/INFO]: JAR transformation complete /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/fg_cache/net/minecraftforge/forge/1.17.1-37.1.1_mapped_official_1.17.1/forge-1.17.1-37.1.1_mapped_official_1.17.1.jar
Creating SRG -> MCP TSRG
Note: SpongePowered MIXIN Annotation Processor Version=0.8.5 (MixinGradle Version=0.7.38)
Note: Supported obfuscation types: ObfuscationServiceMCP supports [notch] ObfuscationServiceFG3 supports [searge]
Note: Loading searge mappings from /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/createMcpToSrg/output.tsrg
Note: Writing refmap to /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/tmp/compileJava/compileJava-refmap.json
Note: Writing refmap to /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/tmp/compileJava/compileJava-refmap.json
Note: Writing searge composite mappings to /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/tmp/compileJava/compileJava-mappings.tsrg
Note: Writing refmap to /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/tmp/compileJava/compileJava-refmap.json
Note: Writing refmap to /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/tmp/compileJava/compileJava-refmap.json
Note: Writing searge composite mappings to /home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/build/tmp/compileJava/compileJava-mappings.tsrg
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:70: error: cannot find symbol
		PLATFORM_JP_1 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_1"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_1
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:71: error: cannot find symbol
		PLATFORM_JP_1_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_1_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_1_INDENTED
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:72: error: cannot find symbol
		PLATFORM_JP_2 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_2"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_2
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:73: error: cannot find symbol
		PLATFORM_JP_2_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_2_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_2_INDENTED
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:74: error: cannot find symbol
                PLATFORM_JP_3 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_3"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
                ^
  symbol:   variable PLATFORM_JP_3
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:[75](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/actions/runs/7428988219/job/20217011469#step:8:76): error: cannot find symbol
		PLATFORM_JP_3_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_3_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_3_INDENTED
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:[76](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/actions/runs/7428988219/job/20217011469#step:8:77): error: cannot find symbol
		PLATFORM_JP_4 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_4"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_4
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:[77](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/actions/runs/7428988219/job/20217011469#step:8:78): error: cannot find symbol
		PLATFORM_JP_4_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_4_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_4_INDENTED
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:[78](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/actions/runs/7428988219/job/20217011469#step:8:79): error: cannot find symbol
		PLATFORM_JP_5 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_5"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_5
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:[79](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/actions/runs/7428988219/job/20217011469#step:8:80): error: cannot find symbol
		PLATFORM_JP_5_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_5_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_5_INDENTED
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:[80](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/actions/runs/7428988219/job/20217011469#step:8:81): error: cannot find symbol
		PLATFORM_JP_6 = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_6"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), false)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_6
  location: class Blocks
/home/runner/work/Minecraft-Transit-Railway/Minecraft-Transit-Railway/forge/src/main/java/org/mtr/mod/Blocks.java:[81](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/actions/runs/7428988219/job/20217011469#step:8:82): error: cannot find symbol
		PLATFORM_JP_6_INDENTED = Registry.registerBlockWithBlockItem(new Identifier(Init.MOD_ID, "platform_jp_6_indented"), () -> new Block(new BlockPlatform(BlockHelper.createBlockSettings(false), true)), CreativeModeTabs.STATION_BUILDING_BLOCKS);
		^
  symbol:   variable PLATFORM_JP_6_INDENTED
  location: class Blocks

**Comment by Kenny-Hui** [comment]
Must declare the variable at the bottom before use in Blocks.java (OP seems to have resolved the issue)

**Comment by YYLWZDXPGD** [comment]
![IMG_5902](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/128379352/8d4d40e5-b3ec-4e6a-a953-4d4343ad6822)
I found the reason for the problem. I need to update Gradle. I don't have permission to change the Gradle file directly. Please you (contributor) can make changes.
