### ISSUE TITLE
Game crashes unexpectedly on client side

### ISSUE THREAD

**Issue by SteveA666** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#797]
**Expected Behaviour**
I was in my own server I built, at a station waiting for the train to come and get on, testing the new route I built. In theory I should ride the train on the line just fine.

**Actual Behaviour**
The game crashes and I can never get back into the server

**Reproduction Steps**
Steps to reproduce the behaviour:
I don't really know, I just created a new route with shared stations with other routes.
Then I teleported to the shared station, with 3 trains entering the station simultaneously.
The the game suddenly crashes without any warning.

**Crash Report**
[crash-2024-01-06_11.30.38-client.txt](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/files/13866998/crash-2024-01-06_11.30.38-client.txt)

**Environment**

- Minecraft Version: 1.19.4 fabric 0.14.21
- Installed Mods:
fabric-api: Fabric API 0.86.1+1.19.4
			fabric-api-base: Fabric API Base 0.4.28+737a6ee8f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.29+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.9+10ce000ff4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.8+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.38+10ce000ff4
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+0eee1254f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.31+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.10+10ce000ff4
			fabric-commands-v0: Fabric Commands (v0) 0.2.48+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.58+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.14+10ce000ff4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+6d727b51f4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.17+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.5.1+26f09d40f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.49+10ce000ff4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.17+10ce000ff4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+4b6b93f0f4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.56+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.35+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.21+10ce000ff4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.10+8400c67ef4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.35+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.33+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.19+10ce000ff4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.32+10ce000ff4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.36+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.5+53c11dadf4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.44+10ce000ff4
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+3a1ea2f1f4
			fabric-models-v0: Fabric Models (v0) 0.4.1+a0255436f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.5+10ce000ff4
			fabric-networking-v0: Fabric Networking (v0) 0.3.45+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.1.1+d63b52eaf4
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+86d48884f4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.12+10ce000ff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+95ae8716f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.4.1+a0255436f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+07902599f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.42+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.32+10ce000ff4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.25+10ce000ff4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.45+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.5+10ce000ff4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.3+10ce000ff4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+8400c67ef4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.49+10ce000ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.24+10ce000ff4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.11+10ce000ff4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+7bf81db9f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.3.0+1b5f819af4
		fabricloader: Fabric Loader 0.14.21
		iris: Iris 1.6.6
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.7
			journeymap-api-fabric: JourneyMap API 1.19.4-1.9-fabric-SNAPSHOT
		jsblock: Joban Client Mod 1.2.2+mc1.19.4
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.3.1
		msd: MTR Station Decoration Addon 1.19.4-3.2.2-1.3.4-enhancement-1
		mtr: Minecraft Transit Railway 1.19.4-3.2.2
		mtrsteamloco: Nemo's Transit Expansion 1.19.4-0.3.3
		sodium: Sodium 0.4.10+build.24
		tcwm: Reality City Construction 1.19.4-1.0.0-unofficial-7-SNAPSHOT-2-Fix-1
		worldedit: WorldEdit 7.2.14+6360-094b734

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
