### ISSUE TITLE
在服务器中安装此MOD导致服务器根本无法启动(1.20.2)

### ISSUE THREAD

**Issue by Leoparking** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#799]
**Expected Behaviour**
服务器正常启动，并且玩家可以进入多人游戏游玩

**Actual Behaviour**
报错信息表明在加载Minecraft Transit Railway (mtr)模组时发生了错误。关键的错误信息是java.lang.NoClassDefFoundError: org/apache/http/HttpEntity，指示缺少org.apache.http.HttpEntity类。

根据报错信息，可以看到在org.mtr.mod.Init.init方法中出现了错误。该方法位于MTR-forge-1.20.2-4.0.0-beta-1.jar文件中。具体错误原因可能是由于缺少org.apache.http.HttpEntity类导致无法创建模组实例。

**Reproduction Steps**
首先把MTR放入任何一个1.20.2的forge服务端，然后启动服务器，过不了多久报错并终止程序

**Crash Report**
[crash-2024-01-24_11.22.33-fml.txt](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/files/14032232/crash-2024-01-24_11.22.33-fml.txt)
[latest.log](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/files/14032234/latest.log)

**Screenshots**
<img width="915" alt="image" src="https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/141799770/378af8fe-a573-44ea-b109-1c6fe8ad5caf">
<img width="896" alt="image" src="https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/141799770/ba20c820-2d06-4912-86de-cb8a1afbd7db">
<img width="706" alt="image" src="https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/141799770/848e0bc4-5506-46bc-b766-742d2d8bd402">
<img width="861" alt="image" src="https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/141799770/75a5b3f2-bccd-44d7-ab31-dbdef078c9a1">

**Environment**

- Minecraft Version:1.20.x
- Installed Mods:MTR-forge-1.20.2-4.0.0-beta-1、architectury-10.0.17-minecraftforge

**Additional Information**
不只是1.20.2，1.20和1.20.1的版本曾经也有同样的错误（经测试1.20.1mohist服务端目前已没有该问题）

**Comment by jonafanho** [comment]
This should be fixed in the latest version of 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!

**Comment by Leoparking** [comment]
> 这应该在最新版本的 4.0.0 中修复。如果您在 4.0.0 中仍然遇到此问题，请重新打开此错误，谢谢！

并没有看到4.0.0的版本
<img width="545" alt="image" src="https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/141799770/1b517862-ea37-44ac-ad5e-33992e6774f7">
只有3.2.2

**Comment by jonafanho** [comment]
@Leoparking it's on [Modrinth](https://modrinth.com/mod/minecraft-transit-railway/versions), not CurseForge

**Comment by Leoparking** [comment]
> @Leoparking it's on [Modrinth](https://modrinth.com/mod/minecraft-transit-railway/versions), not CurseForge

安装了4.0.0beta 8，但这个版本仍存在缺失功能，比如手动驾驶不见了（钥匙没了），资源包创建器没了，服务端应该更新吗
