### ISSUE TITLE
Trains take several minutes to start running

### ISSUE THREAD

**Issue by cat1554** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#803]
**Expected Behaviour**
Trains should immediately start running on a path.

**Actual Behaviour**
Trains take several minutes to start running along a path.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Create a route
2. Assign depot to a path

**Crash Report**
n/a

**Environment**

- Minecraft Version: 1.20.4 Fabric
- Installed Mods: MTR 4.0.0 Beta 3

**Additional Information**
Depot lists also remain on the "Path not generated" message.

**Comment by CaptainAngle** [comment]
Hit refresh pash and clear vehicles, this is something you can find details in the tutorials

**Comment by Kenny-Hui** [comment]
Should be fixed on the latest version
