### ISSUE TITLE
方块与物品放置使用异常，会变来变去

### ISSUE THREAD

**Issue by Leoparking** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#813]
**Expected Behaviour**
列车仪表盘可以打开使用，方块可以正常放在地上，不会消失，不会变成其他样子······

**Actual Behaviour**
拿着列车仪表盘对着地面右键打不开GUI，而是出现一个屏蔽门，放置屏蔽门会立刻变成另一个门，放置什么变成另一个什么

**Reproduction Steps**
首先获得一个1.19.4的服务器存档，然后其他不变，仅更换服务端核心和MOD为1.20.1的版本，然后启动服务器，加入游戏

1.

**Crash Report**
没崩溃

**Screenshots**
我有视频

https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/141799770/f2f2a8fe-87c9-4a05-ad65-5d14c03a6769

**Environment**

- Minecraft Version:1.20.1
- Installed Mods:[铁路前置]architectury-9.1.12-forge    [我的世界铁路] MTR-forge-1.20.1-3.2.2-hotfix-2

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
I'm guessing this is because the client and server versions of the mod are mismatching. Please verify and reopen this issue if needed. I would also suggest testing in 4.0.0 as well, thanks.
