### ISSUE TITLE
假猪BUG

### ISSUE THREAD

**Issue by Leoparking** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#814]
https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/141799770/4966183f-3755-4ace-a055-92b1ac8dcf46

先启动任意版本的BungeeCord服务端，再启动Mohist 1.20.1-550服务端（带MTR模组），如果使用不带MTR模组的客户端（有forge47.1.0）进入服务器就会被假猪困扰

**Comment by Leoparking** [comment]
经测试，这个“猪”的本体是mtr:seat实体，使用循环命令方块循环kill mtr:seat即可解决

**Comment by Ultimate-USA-YT** [comment]
`mtr:seat` is used to Render the Trains and Can't be Killed.

**Comment by Leoparking** [comment]
> `mtr:seat` is used to Render the Trains and Can't be Killed.

可以，我在服务器出生点区块里放置了循环命令方块，持续的检测和杀死mtr:seat，并不会影响列车运行，玩家也不再被假猪困扰

**Comment by Kenny-Hui** [comment]
MTR expects both client and server to have the mod installed, anything else are not a supported configuration

**Comment by dddddgz** [comment]
不是bug吧，本来mtr就要求client和server都要有，client装上它就行了
btw，mtr列车的碰撞箱奇奇怪怪的，都在很大一片空白区域（f3+b）

**Comment by Leoparking** [comment]
> 不是bug吧，本来mtr就要求client和server都要有，client装上它就行了
> btw，mtr列车的碰撞箱奇奇怪怪的，都在很大一片空白区域（f3+b）

这就是BUG，只不过客户端装了MOD可以隐藏掉这个BUG实体而已

**Comment by Leoparking** [comment]
> 不是bug吧，本来mtr就要求client和server都要有，client装上它就行了
> btw，mtr列车的碰撞箱奇奇怪怪的，都在很大一片空白区域（f3+b）

mtr:seat原本在很早之前的版本已经移除了(建议先看看MC百科)，而在现版本出现这个不得而知，并且指令/kill该实体不会影响交通工具的运行

**Comment by Leoparking** [comment]
> 不是bug吧，本来mtr就要求client和server都要有，client装上它就行了
> btw，mtr列车的碰撞箱奇奇怪怪的，都在很大一片空白区域（f3+b）

如果你同时安装了瞄准信息显示(比如《玉🔍》，有时候你会在旁观者模式下发现屏幕顶部闪动出现mtr:seat的实体标签(没有贴图，也没有生命值)

**Comment by dddddgz** [comment]
这个大概是设置了不显示mtr:seat实体的吧，我这边试了1.19.2fabric的，kill了列车就没了

所以mtr:seat大概是给列车提供渲染，所以碰撞箱奇奇怪怪

**Comment by Leoparking** [comment]
> 这个大概是设置了不显示mtr：seat实体的吧，我这边试了1.19.2fabric的，kill了列车就没了
> 
> 所以mtr：seat大概是给列车提供渲染，所以碰撞箱奇奇怪怪

Fabric啊···我一直用的forge架构的，加载器不一样确实是有不同之处，forge清除这个实体是不影响的，应该是作者先做fabric再做forge复制粘贴的原因了

**Comment by dddddgz** [comment]
应该是你说的这样吧，还有一点，显示猪和刷怪笼道理一样，生物默认是猪
