### ISSUE TITLE
在服务器里列车和飞机的渲染距离能不能远一点？

### ISSUE THREAD

**Issue by Leoparking** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#819]
_![5XZ~QICT$X`HYLGCUTUSWUD](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/141799770/2332c7a0-a08f-47a9-827b-bfd5e329f479)_

《世界名画》
列车或者飞机总是在40格以外就隐藏了，导致出现“两节车厢跑”的奇观。但是这非常影响拍摄

在单人游戏里很远就能看到。
为什么服务器里就不行？而且我视距也很大，玩家能看到16个区块呢

**Comment by Ultimate-USA-YT** [comment]
Try Checking the Dashboard's "Options" Menu

**Comment by NiuBoss123** [comment]
这不是跟服务器设置有关吗，有必要提一个issue？

**Comment by Emerald-Rail** [comment]
请在`server.properties`修改视距

**Comment by Leoparking** [comment]
> 尝试检查仪表板的“选项”菜单

你这个是最佳答案，其它都是胡说
问题可以关闭了

**Comment by zbx1425** [comment]
> 你这个是最佳答案，其它都是胡说 问题可以关闭了

Issues 不是问答版，想用问答版的话去更合适的平台。
您可以关闭 Issue。

**Comment by Leoparking** [comment]
> 请在`server.properties`修改视距

眼瞎?
![Screenshot_2024-05-07-12-37-16-537_com.github.android-edit.jpg](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/141799770/96a93fa1-6ff8-4775-ae21-04c19265f652)

**Comment by Leoparking** [comment]
> 這不是跟 server.properties 有關係？有必要提一個issue？

眼瞎?![Screenshot_2024-05-07-12-37-16-537_com.github.android-edit.jpg](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/141799770/7776c3ee-baee-4079-8734-72e0239b2da0)

**Comment by NiuBoss123** [comment]
> > 這不是跟 server.properties 有關係？有必要提一個issue？
> 
> 眼瞎?![Screenshot_2024-05-07-12-37-16-537_com.github.android-edit.jpg](https://private-user-images.githubusercontent.com/141799770/328389117-7776c3ee-baee-4079-8734-72e0239b2da0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTYzMjYsIm5iZiI6MTcxNTE1NjAyNiwicGF0aCI6Ii8xNDE3OTk3NzAvMzI4Mzg5MTE3LTc3NzZjM2VlLWJhZWUtNDA3OS04NzM0LTcyZTAyMzliMmRhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwODEzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTZkMjdkMDFiZTRhOTViOWJlMDM0ODg3NWE1YTZlODVjZWZkN2QxZjlmNWFkOTJhOGQzOTM1NDZiZDBhZTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nd1xMU9B3EjRHDpcM7qIBigbPYR-Uq5UgfzUyZGG8t4)

@Leoparking 玩家可以指代任何一位遊戲的實際遊玩者，我可以理解為是某一位玩家的情況，而這位玩家的列車顯示是什麼情況我不得而知
另外你沒有給出任何有關於設置和日誌頁面，issue 的默認文字你或許都沒看吧
我個人還是那句話，“有必要提一個issue？”，而且這個issue 5天前就關閉，沒人再跟進，妳卻還要給兩個消息回復“眼瞎”，我不理解是出於什麼目的，看你 GitHub 給的社交媒體鏈接裡面的 Bilibili 賬號是被封禁的，想必也是發生了什麼事情才會這樣的吧

**Comment by Leoparking** [comment]
> > > 這不是跟 server.properties 有關係？有必要提一個issue？
> > 
> > 眼瞎?![Screenshot_2024-05-07-12-37-16-537_com.github.android-edit.jpg](https://private-user-images.githubusercontent.com/141799770/328389117-7776c3ee-baee-4079-8734-72e0239b2da0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTYzMjYsIm5iZiI6MTcxNTE1NjAyNiwicGF0aCI6Ii8xNDE3OTk3NzAvMzI4Mzg5MTE3LTc3NzZjM2VlLWJhZWUtNDA3OS04NzM0LTcyZTAyMzliMmRhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwODEzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTZkMjdkMDFiZTRhOTViOWJlMDM0ODg3NWE1YTZlODVjZWZkN2QxZjlmNWFkOTJhOGQzOTM1NDZiZDBhZTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nd1xMU9B3EjRHDpcM7qIBigbPYR-Uq5UgfzUyZGG8t4)
> 
> @Leoparking 玩家可以指代任何一位遊戲的實際遊玩者，我可以理解為是某一位玩家的情況，而這位玩家的列車顯示是什麼情況我不得而知
> 另外你沒有給出任何有關於設置和日誌頁面，issue 的默認文字你或許都沒看吧
> 我個人還是那句話，“有必要提一個issue？”，而且這個 issue 5天前就關閉（還是你要求關閉的），沒人再跟進，你卻還要給兩個消息回復“眼瞎”，我不理解是出於什麼目的，看你 GitHub 給的社交媒體鏈接裡面的 Bilibili 賬號是被封禁的，想必也是發生了什麼事情才會這樣的吧

所以你还是觉得这个跟server.properties有关对不😅那我还要多说什么，你觉得就这样觉得呗 看你一句句不离老掉牙繁体字，想必也是来自于神威无敌自由♂民主的偉大中華民國吧🤣👉🏻👈🤔

**Comment by zbx1425** [comment]
……对于真正想知道这个到底是怎么回事的人

列车显示与否有两个距离限制
一个是客户端视距+MTR 设置里“列车渲染距离到客户端视距比例”
另一个是服务器只会至多发送 128 格（16 区块的长度）内的列车数据到客户端（ https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/blob/87c987f660dac35832bb9373c7d7da8bd31e2abc/common/src/main/java/mtr/data/TrainServer.java#L38 ），这是在代码里写死的，不随服务器视距设定改变

总之，把客户端视距和 MTR 设置里那个选项拉高，可以看到至多大致 128 格（16 区块）的列车，再远的列车目前 MTR 是不会同步的了所以没办法看到
