### ISSUE TITLE
Cant Find path no matter what

### ISSUE THREAD

**Issue by Jamesthecreator1** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#823]
**Expected Behaviour**
I tried Making a route between My two stations depot at the Front of the route And a completely straight rail path of course i expected it to Recognize the Path and let me run trains.

**Actual Behaviour**
It did not Find the path no matter what I tried I tried Changing the rails to something different I changed the size of the depot i changed the platforms but nothing's worked

**Reproduction Steps**
Steps to reproduce the behaviour:

1.Build two stations in a straight line with a depot at the start 

2. Configure the Depot and stations to Work correctly

3.Make the route Between the depot and the two stations

4.See the Depot failing to recognize the path 

**Environment**

- Minecraft Version:1.18.2 Forge 
- Installed Mods:Create with a whole lot of Addons, Public transport mod , Decocraft

**Comment by CaptainAngle** [comment]
Maybe give us a screenshot of your layout while holding a rail connector and a screenshot of all related items in the railway dashboard; we don't have enough info to figure this out yet.

**Comment by Kenny-Hui** [comment]
Not enough information, please provide the layout of the track
