### ISSUE TITLE
Please update the latest version of Gradle

### ISSUE THREAD

**Issue by YYLWZDXPGD** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#826]
![IMG_5902](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/128379352/cce1edf2-2e11-4d7a-a0c8-fe89a22b944a)

**Comment by Kenny-Hui** [comment]
Please pull the latest commit (https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/commit/6e38502c18675cc281f32024d3be9f2e2b990c5d), which has already bumped the gradle version.
