### ISSUE TITLE
Airbus not detected

### ISSUE THREAD

**Issue by vrw93** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#827]
I install this mod because i want to play with airplane but the plane but in my case Airbus A320 not detected(i can select the air bus in airplane dasboard only show a warning triangle beside the title of airbus).Please Help me im new. i use 1.19.4. this the screenshots
![Annotation 2024-03-31 171918](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/103785143/d58cb2e2-e608-404a-82f2-2b4cbb89a1eb)

**Comment by Kenny-Hui** [comment]
The length of an A320 in the mod is 30 blocks, please make a siding that is 30 blocks or longer than that for the plane to have enough space to spawn.

**Comment by vrw93** [comment]
Ah,i see thank you
