### ISSUE TITLE
pids显示线路名

### ISSUE THREAD

**Issue by JiaqiYi** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#837]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...
当建设火车站类型的车站时显示终点的pids 给乘客带来麻烦
**Describe the solution you'd like**
pids 如此显示:朱山线(线路) 旭日(车站) 2min
**Additional Information**

**Comment by Emerald-Rail** [comment]
港铁本来就不显示路线名

**Comment by Ultimate-USA-YT** [comment]
Modular PIDS Is In Development.

**Comment by NiuBoss123** [comment]
港鐵由於沒有直通的情況因而沒有顯示路綫名稱的情況，個人建議這個提議給到 [DistrictOfJoban/Joban-Client-Mod](https://github.com/DistrictOfJoban/Joban-Client-Mod) 那邊來做個拓展
