### ISSUE TITLE
更改强制下车方式

### ISSUE THREAD

**Issue by JiaqiYi** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#840]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...

**Describe the solution you'd like**
玩家习惯性按shift。
鹅这么做在坐车时带来麻烦。
希望将强制下车改为一个无需权限的命令。
**Additional Information**

**Comment by NiuBoss123** [comment]
印象之中目前采取的是長按一段時間的 `shift`，感覺現有的已經足夠了（而且我記得是無需任何權限的）
