### ISSUE TITLE
Cable Cars won't stop spawning

### ISSUE THREAD

**Issue by izShelby** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#842]
**Expected Behaviour**
Cable car depots should have a maximum number of cars that they spawn

**Actual Behaviour**
Cable cars never stop spawning, start bunching up at station.

**Reproduction Steps**
1. Set up cable car line.
2. Watch as the siding keeps spawning cable cars every 10 seconds or so
3. After several minutes the stations are clogged.

**Crash Report**
---

**Screenshots**

![Here we see a CCCF (cable car clusterfuck)](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/2027320/3014fd58-3e13-48b8-8e62-ee7f8228d5c5)
![Another depiction of a cable car mating ritual.](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/2027320/10c79a37-223e-4212-8f86-3100428526ae)
![More cable car conga lining. My frames were suffering at this point](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/2027320/9c6169fb-55f6-4383-9fc5-033cc0da7c18)
This is after about five minutes of letting them run.

**Environment**

- Minecraft Version: 1.19.4
- Installed Mods: A lot. I don't think this issue is related to mod interaction. I'll provide the list if it turns out I'm wrong.

**Additional Information**
I love the mod and so does everyone else on the server. The trains work a treat, unfortunately the cable cars aren't really usable how they are.

**Comment by balazskis12** [comment]
Hey, are you sure that you haven't turned "Repeat Instructions Forever" on? 
I was only able to recreate the issue after turning it on.

**Comment by izShelby** [comment]
I'm unsure what you mean, because cable car depots do not have this option:
![???](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/2027320/29617d73-74f9-44c3-bd47-c8cbebc51d84)

(vs rail depots:)
![rail depot with the option](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/2027320/da711a3f-2be1-4294-946f-10431e722ddf)

**Comment by balazskis12** [comment]
They only have the option if the first and last stops are the same. Idk how but it appeared for me

**Comment by Kenny-Hui** [comment]
Please clarify the MTR version, is this on 3.2.2?

**Comment by izShelby** [comment]
> Please clarify the MTR version, is this on 3.2.2?

Ah, apologies. Yes, I'm on 3.2.2-hotfix1.

**Comment by jonafanho** [comment]
Do you have just one depot per cable car line? Cable cars are only meant to have one depot per line and the cars shouldn't stop spawning. Please reopen the issue if you are still encountering this in 4.0.0-beta-8.

**Comment by Jbelligol** [comment]
Ok can somebody please explain how to fix this issue bc I have 0 clue on how to fix this i let it run and with in 5 mins when the first cable car takes a full round then another one spawns in to create a big traffic can someone find a solution and let me know asap?
