### ISSUE TITLE
Question about the level crossing in front of the station

### ISSUE THREAD

**Issue by issues-linux** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#843]
Hello, I very like this mod, but I have one question about track crossing before station.
You can see below the track scheme:
![mtr_station_scheme](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/169305212/5856d273-e863-4c6b-a1c7-efc05555671c)

Since it is a terminus station and it is not possible to make a turntable behind it because there is not enough space behind it, I would like to do it as follows: in front of the station I would place a track crossing and when the first train is on track 1, the switch would be "switched" so that the second train would go to track 2, and vice versa. 

Is it possible to do it this way?
Thank you in advance for your reply.

**Comment by Kenny-Hui** [comment]
Not at the moment.
The way MTR currently works internally is that it predetermines the exact path it needs to take, which is what the Generate Path process is for. It is not possible to intermediately change the path the train is taking.

A workaround is to make 2 route (One to Platform 1, One to Platform 2) and 2 depot for the 2 route respectively, then schedule the train departure to alternate between the two depot (Usually via real-time schedule).

However this only works well under the assumption that you can fully predict the journey time. If the train can get stopped midway for an unknown period of time, the ordering may be messed up.
