### ISSUE TITLE
接触网and 轨道

### ISSUE THREAD

**Issue by JiaqiYi** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#844]
Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...1.20.1没有接触网mod,啊啊啊啊啊啊啊啊

**Describe the solution you'd like**
将msd 模组包含进mtr 内
**Additional Information**
希望默认轨道变成即将发布的立体轨道功能,并在存档升级时自动替换为立体轨道

**Comment by jonafanho** [comment]
MSD exists as a separate addon so the core mod won't be cluttered with literally everything related to railways. Also, 3D rails have been added to the main mod in 4.0.0.
