### ISSUE TITLE
[4.0.0] Elevator model invisible and not interactable.

### ISSUE THREAD

**Issue by Lumi1323** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#851]
**Expected Behavior**
The elevator model would appear.

**Actual Behavior**
The elevator model was invisible.

**Reproduction Steps**

1. Make a elevator track.
2. Create elevator using the Refresher.
3. Elevator does not show up. Nor is interactable. (It still allows you to configure it.)

**Environment**

- Minecraft Version: 1.20.4
- Installed Mods: 4.0.0 MTR Preview Modpack.

**Comment by jonafanho** [comment]
I think this is now resolved, can you please verify?

**Comment by Kenny-Hui** [comment]
Should be resolved as of latest beta release
