### ISSUE TITLE
Compibility With Create Mod

### ISSUE THREAD

**Issue by Jeyzhen** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#853]
I have met a problem with the latest action bulid on github
MTR (1.20.1 Version) doesn't match the Create mod, which appears that if the Create mod enabled the train and the rails won't display
even I change the model of the rails with the brush

**Comment by Kenny-Hui** [comment]
Latest MTR Build appears to have fixed this (Fabric 1.20.1)
![image](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/28094366/3418b6ab-6782-491e-92ed-e96a8a0fc66f)

**Comment by Qha821** [comment]
Thanks and it seems that the problem have solved
