### ISSUE TITLE
a new railway system map?

### ISSUE THREAD

**Issue by HeyCrab3** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#855]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
i just used Vue to enhanced the railway map few days ago and it works very well
so i think we can have a better railway system map

**Additional Information**
u can visit live demo at [here](http://localboost.heycrab.xyz:5174)

**Comment by sparrowhe** [comment]
From 4.0.0, MTR is using new web railway system map https://github.com/Minecraft-Transit-Railway/Transport-Simulation-Core/tree/555558f6e005ca3c171abbdc06ca376c73dd223f/buildSrc/src/main/resources/website

It is written in Angular and MTR 3.3.0 seems no longer upgrade.

**Comment by HeyCrab3** [comment]
> From 4.0.0, MTR is using new web railway system map https://github.com/Minecraft-Transit-Railway/Transport-Simulation-Core/tree/555558f6e005ca3c171abbdc06ca376c73dd223f/buildSrc/src/main/resources/website
> 
> It is written in Angular and MTR 3.3.0 seems no longer upgrade.

nooo i have 0 experience to write Angular

**Comment by jonafanho** [comment]
The online system map is still a work in progress. Are there any specific changes you would like to see? Otherwise, I will close this issue, thanks.
