### ISSUE TITLE
Trains dont have hitboxes

### ISSUE THREAD

**Issue by StartsWithF** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#858]
**Expected Behaviour**
I can enter the train and the doors open and close

**Actual Behaviour**
The trains dont have any hitboxes and the doors dont open or close

**Reproduction Steps**

1.Just spawn a train like usual

**Crash Report**
Attach a crash report to the issue.

**Screenshots**
![Minecraft Screenshot 2024 06 15 - 13 56 50 35](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/172902235/1e528e18-fdb0-4e57-a2ba-6f22c28f8f46)

https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/172902235/08700d45-d6eb-417b-bf2c-2ed7a992609c

**Environment**

- Minecraft Version: 1.19.4
- Installed Mods: Fabric, fabric-api-0.87.2+1.19.4, MTR-fabric-1.19.4-3.2.2-hotfix-1

**Additional Information**
Anything else you want to add?

**Comment by Ultimate-USA-YT** [comment]
Have you watched the Tutorials?

**Comment by Kenny-Hui** [comment]
Please refer to the [video](https://www.youtube.com/playlist?list=PLp0jZgheSlXv_vjilwnbrOtdbmgvz1VkC) or [text](https://wiki.minecrafttransitrailway.com/mtr:getting_started) tutorial on how to operate and get your train running.
