### ISSUE TITLE
Probably bug on separate ways

### ISSUE THREAD

**Issue by ForTyxx13** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#863]
**Actual Behaviour**
A clear and concise description of what actually happened.
I haven't been able to fix this problem for some time. I have a rail path that needs to split to go to 2 different stations. I'm trying to get my train to go to the right (Joined picture) but it doesn't work. I tried to change the nodes, the speed limit, the continuity of the rail but nothing works. How to fix this problem ?
**Reproduction Steps**
Steps to reproduce the behaviour:

1.

**Crash Report**
Attach a crash report to the issue.
No crash report

**Screenshots**
![Desktop Screenshot 2024 06 17 - 15 12 29 18](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/121829181/55a2783d-61fe-4b38-89f2-458ae181d2ca)

**Environment**

- Minecraft Version: 1.16.5
- Installed Mods: SecurityCraft, MrCrayFish's Mods, EconomyInc, Create, SignPost 

**Additional Information**
Anything else you want to add?
No

**Comment by jonafanho** [comment]
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!
