### ISSUE TITLE
game crashed after I changed the rendering options of train texture

### ISSUE THREAD

**Issue by ferityCat** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#867]
**Environment**

The game crashed immediately whenever I entered the game with  my old hp laptop, since I changed the rendering options of train texture.
The java crash report file is uploaded.

Plz help me to get my saves back.

- Minecraft Version: 1.19.4
- Installed Mods: mtr 1.19.4 fabric
- 
[hs_err_pid17212.log](https://github.com/user-attachments/files/15942348/hs_err_pid17212.log)

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
Which rendering option did you change? Also, please confirm if you are still encountering this issue in 4.0.0.

**Comment by kettle-7** [comment]
If you changed the dynamic texture resolution, you can use the Mod Menu mod
to access settings for the individual mods, and in the options menu for mtr
you can change it back to 2 or 3 which tends to make text readable while
also not being too demanding

**Comment by ferityCat** [comment]
Last time, I changed the "Minecraft Transit Railway Options" -> "Dynamic texture resolution" to 11, then crashed.
Now I update the 4.0.0 version and reload the mod, then I enter the game successfully.  And I find that the maximum level is 7 this time. 
Thank you .
