### ISSUE TITLE
Trapped in Elevator if Doors Not Added

### ISSUE THREAD

**Issue by Dickovski** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#868]
**Expected Behaviour**

**Actual Behaviour**
A clear and concise description of what actually happened.

**Reproduction Steps**
Steps to reproduce the behaviour:

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version:
- Installed Mods:

**Additional Information**
Anything else you want to add?

**Comment by Dickovski** [comment]
Just downloaded MTR for Forge 1.20.1  Great to see the escalator and elevator mod.  I've found that, if you do not add doors on each floor, you become trapped in the elevator on floors without a door, even trying to teleport out doesn't work!  The only way is to go back to a floor with the doors or to break the floor track for that floor which kills the elevator cabin and it has to be created again.

**Comment by jonafanho** [comment]
Have you tried holding shift to exit out of the elevator? Also, this is probably resolved in 4.0.0 (the shift behaviour), so please let me know if you are still encountering this.

**Comment by Dickovski** [comment]
Thanks very much for the help.  I have tried to install 4.0.0 as I realise it may have many fixes but so far it only causes Minecraft to crash.  I need to look into what might be causing this, loads of other mods loaded so it may take a while to figure out what it could be.  I am looking forward to getting it working as I really like your mod.

**Comment by Dickovski** [comment]
It looks like it was World Edit causing the issue, I rarely use it so I removed it.  Now I can use MTR 4.0.0 which is great.  Thanks again for this really useful mod.
