### ISSUE TITLE
加载资源包慢

### ISSUE THREAD

**Issue by JiaqiYi** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#870]
**Expected Behaviour**
包应该快速加载
**Actual Behaviour**
A clear and concise description of what actually happened.
加载几个obj 列车和轨道包后未响应卡在mojang 加载页面约1-2分钟
启动游戏也在minecraft progress 几乎满的时候卡好久
**Reproduction Steps**
Steps to reproduce the behaviour:

1.

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**
i5-8500u
8g 内存分配
- Minecraft Version:1.20.1forge
- Installed Mods:mtr4.0.0b8 msd,jcm,和一大堆

**Additional Information**
Anything else you want to add?

**Comment by HanXiaozeng** [comment]
同感 加装CR系列动车组后加载时很慢！！
The same feeling is very slow when loading after installing CR series EMUs!!

**Comment by jonafanho** [comment]
This should be resolved in the latest 4.0.0 beta, thank you!
