### ISSUE TITLE
I have this error reported

### ISSUE THREAD

**Issue by EMAMESH** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#885]
**Expected Behaviour**
when I start the game with the mtr mod version 4.0.0 it gives me this error.

**Reproduction Steps**
Steps to reproduce the behaviour:

1.start the game with the mtr mod version 4.0.0
2.wait 1 minute
3.he give the error

**Crash Report**
ERROR: -1

**Screenshots**
![ERROR -1](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/87384293/7fb428ec-9def-4822-91fb-f7e73242aa29)

**Environment**

- Minecraft Version:1.20.1
- Installed Mods: total 7 mods :
![MODS](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/87384293/47ce1287-ac4e-4a33-a37f-ccf941fd9e4a)

Please answer me!

**Comment by Kenny-Hui** [comment]
Much of NTE's functionality such as OBJ rendering and track customization has been integrated to MTR 4, with more to come later.

NTE is not compatible with MTR 4.

**Comment by jonafanho** [comment]
Also for the future, please do not just post the "error code: -1" screen as it is useless for us to diagnose the issue. Please post logs and crash reports instead, found in `.minecraft/logs` or `.minecraft/crash-reports`.

**Comment by Kenny-Hui** [comment]
Worth considering remaking the issue template to take advantage of the new GitHub form so we can put descriptions and be more stricter, but that's for another time

**Comment by EMAMESH** [comment]
thank you guys , at least for next time I'll know
