### ISSUE TITLE
装饰物件模型可见性问题

### ISSUE THREAD

**Issue by JiaqiYi** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#888]
**Expected Behaviour**
无论看向那里,msd 提供的接触网架都应该显示
**Actual Behaviour**
A clear and concise description of what actually happened.
当装饰物件方块不在视野中时,整个模型不渲染
**Reproduction Steps**
Steps to reproduce the behaviour:

1.安装1.20.1forgemtr4.0.0b8+jcm+msd+embeddium
2 视频设置,perfomance,关掉block face culling 和only 什么 viviable textures(我自己几个可能导致问题的设置
3 正常摆放一个装饰物件接触网柱子
4 使装饰物件从视野内消失,但柱子本体看着
5 柱子(悲伤的)整个不见了
**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version:1 20.1forge
- Installed Mods:mtrb8,jcm msd embeddium ,还有一大堆

**Additional Information**
Anything else you want to add?

**Comment by pokOSlanx** [comment]
MSD的问题你应该反馈到MSD啊！
点击链接一站直达：https://github.com/AIDA64S/MTR-Station-Decoration-Addon/issues/new

**Comment by jonafanho** [comment]
Yes, I believe it would be better to post this to the MSD GitHub directly. Thanks.
