### ISSUE TITLE
Rails disappear

### ISSUE THREAD

**Issue by Natanoid92** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#894]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported in the [Issues page](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exist in the latest version of the MTR Mod.
- [X] I have tested this in the official version of MTR, not a modified/custom/unofficial build.

### Describe the Bug

After leaving the server and later joining: Rails not present, only the connectors are hanging around.

### Reproduction Steps

1. Rails building on the server
2. Depot created. Lines created. Trains run. 
3. Leave servers.
4. Join server: depot gone, lines gone, rails gone.

(Rails not present, only the connectors are hanging around.)

### In-game Log/Crash Report

[latest.log](https://github.com/user-attachments/files/16044613/latest.log)

### Mod Loader

Forge

### Minecraft Version

1.20.1

### MTR Version

4.0.0-beta.8

### Operating System

Windows 11

### List of mods/modpack you were using

![Modlist](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/174252003/23f90dc6-6f04-4da5-87a3-9447384d0e38)

### Extra Informations

Minecraft runs at Version 1.20.1 and Forge 47.3.0 on a Server.

**Comment by HENSOLO-PSD** [comment]
I have that exact same issue. Is it because we're on the latest forge update ?

**Comment by jonafanho** [comment]
Can you please attach logs? Thanks.

**Comment by carlonox** [comment]
I have this exact issue too!

**Comment by IceRainMango** [comment]
I have this problem too! I opened the mtr folder show that the file are still there, but in the server the depot, rail, line are all gone...
Everytime I restart the server and anything I had set were all disappeared. 希望有解決之道, 非常感恩。
version 1.19.2 forge 43.4.2

**Comment by nuclearxmoose** [comment]
EVERYONE I FOUND THE ISSUE,  you need to download the MTR file from their website NOT THE ONE LISTED ON CURSEFORGE,    After this, i can reset my server and the rails stay on the server

**Comment by ALEX8989YT** [comment]
The site also has links to morinth and curseforge, but there is such an error there

**Comment by Kenny-Hui** [comment]
The particular issue reported by OP should be fixed in the latest mod version. If the issue still persists with beta-12, please open a new issue, thanks~
