### ISSUE TITLE
"Path not generated At least two platforms required in depot instructions!" Will appear at any time

### ISSUE THREAD

**Issue by SadEPa28** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#898]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported in the [Issues page](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exist in the latest version of the MTR Mod.
- [X] I have tested this in the official version of MTR, not a modified/custom/unofficial build.

### Describe the Bug

The error "Path not generated At least two platforms required in depot instructions!" appears at all times and the train path cannot be set.
![image](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/159880091/77e24b09-0e2c-4286-b6d7-5cddb558115c)
![image](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/159880091/406fde9e-fdc2-4dc2-bd7f-2a8bce5a8833)
![image](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/159880091/ca4f6b5a-c342-4736-a7b8-8fbdce862f17)
![image](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/159880091/a0262203-2e72-4001-b342-cc21b1ce069e)

### Reproduction Steps

1. Create a railway system
3. Follow the normal steps to set up train paths

### In-game Log/Crash Report

[latest.log](https://github.com/user-attachments/files/16058013/latest.log)

### Mod Loader

Fabric

### Minecraft Version

1.20.4

### MTR Version

4.0.0

### Operating System

Windows 11

### List of mods/modpack you were using

adastra-fabric-1.20.4-1.16.5.jar
adorabuild-structures-2.6.0-fabric-1.20.4.jar
alloy-forgery-2.1.4+1.20.3.jar
animatica-0.6.1+1.20.4.jar
architectury-11.1.17-fabric.jar
athena-fabric-1.20.4-3.3.2.jar
audioplayer-fabric-1.20.4-1.10.2.jar
auto-clicker-fabric-84.0.1.jar
autopath-mc1.20.4-1.5.jar
Axiom-3.0.0-for-MC1.20.4.jar
azurelib-fabric-1.20.4-2.1.13.jar
balm-fabric-1.20.4-9.0.9.jar
bclib-3.30.1.jar
bettercommandblockui-0.5.2-1.20.3.jar
betterendrod-1.1.0.jar
betterladdersmod-1.20.x-No-3D-Model.jar
bigger_end_cities-1.20.4-1.0.4.jar
blendium-1.0.1+mc1.20.x.jar
Bookshelf-Fabric-1.20.4-23.0.8.jar
borderless-mining-1.1.9+1.20.2.jar
botarium-fabric-1.20.4-3.2.2.jar
BuildingWands-mc1.20.4-2.6.9-release.jar
camerautils-fabric-1.20.4-1.0.9.jar
capes-1.5.3+1.20.2-fabric.jar
cardinal-components-api-5.4.0.jar
cat_jam-fabric-mc1.20-1.2.2.jar
cc-tweaked-1.20.4-fabric-1.110.2.jar
Chipped-fabric-1.20.4-3.1.4.jar
cicada-lib-0.8.0+1.20.2-1.20.4.jar
cloth-config-13.0.121-fabric.jar
collective-1.20.4-7.64.jar
continuity-3.0.0-beta.5+1.20.2.jar
Controlify-2.0.0-beta.13+1.20.4-fabric.jar
CopperandTuffBackport-1.0.1.jar
CraftPresence-Flint-2.4.2+0.0.5-flint.jar
CraftTweaker-fabric-1.20.4-17.0.19.jar
crash-pipe-0.1.0.jar
CreativeCore_FABRIC_v2.11.26_mc1.20.4.jar
cristellib-1.2.4-fabric.jar
crockpot-1.14.1+1.20.4.jar
ctLib-0.1.7.jar
ctov-3.4.4.jar
Debugify-1.20.4+1.1.jar
decorative-ladders-1.1.0.jar
DistantHorizonsApi-2.1.0.jar
DnT-stronghold-rework-v1.1.2 [Fabric].jar
DoctorWhoMod-1.20.4-fabric-1.0.9.jar
do_a_barrel_roll-3.6.0+1.20.4-fabric.jar
dynamic-fps-3.5.0+minecraft-1.20.0-fabric.jar
dynamic-torches-v2.jar
eclipsestweakeroo-0.4.5-1.20.4.jar
eden-ring-20.4.20.jar
enchanted-vertical-slabs-1.9.3.jar
enhancedblockentities-0.10.1+1.20.4.jar
EnhancedBookWriting-1.1.1+mc1.20.2.jar
entangled-1.3.18-fabric-mc1.20.jar
entity_model_features_fabric_1.20.4-2.0.2.jar
entity_texture_features_fabric_1.20.4-6.1.jar
EpheroLib-FABRIC-1.2.0-1.20.4.jar
essential_1-3-2-7_fabric_1-20-4.jar
expanded_ecosphere-3.3.1-fabric.jar
fabric-1.0.1.jar
fabric-api-0.97.1+1.20.4.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
fabricskyboxes-0.7.3+mc1.20.2.jar
fastminecart-1.0.0.jar
fastquit-3.0.0+1.20.4.jar
FauxCustomEntityData-fabric-1.20.4-9.0.1.jar
FlightHUD-Fabric-1.20.1-1.1.0.jar
ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar
formations-1.0.2-fabric-mc1.20.4.jar
formationsoverworld-1.0.3.jar
friendsandfoes-beekeeperhut-fabric-mc1.20.4-2.0.0.jar
friendsandfoes-fabric-mc1.20.4-2.0.10.jar
friendsandfoes-flowerymooblooms-fabric-mc1.20.4-2.0.1.jar
fsb-interop-1.3.6+mc1.20.2-build.52.jar
ftb-essentials-fabric-2004.1.2.jar
ftb-library-fabric-2004.2.4.jar
geckolib-fabric-1.20.4-4.4.4.jar
GeckoLibIrisCompat-Fabric-1.0.0.jar
Geophilic v2.4.1 f15-48.jar
GlitchCore-fabric-1.20.4-1.0.0.59.jar
greenscreen-1.0.0.jar
HangGlider-v20.4.2-1.20.4-Fabric.jar
HWGMod-1.20.4-2.1.2.jar
Improved_Animations-fabric-1.20.4-1.0.2.jar
iris-1.7.0+mc1.20.4.jar
kirin-1.17.1+1.20.4.jar
KrystalCraft-fabric-0.0.4.5.jar
Ksyxis-1.3.2.jar
language-reload-1.6.1+1.20.4.jar
lanserverproperties-1.12.1-fabric.jar
laserbridges-1.20.4-2-fabric.jar
letmedespawn-fabric-1.20.x-1.2.1.jar
lightspeedboat-fabric-1.0.2.jar
Linkart-5.4.4-build.133-1.20.2.jar
lithostitched-fabric-1.20.4-1.1.5.jar
main-menu-credits-1.1.2.jar
malilib-fabric-1.20.4-0.18.4-alpha.1.jar
mcw-holidays-1.1.0-mc1.20.4fabric.jar
midnightlib-fabric-1.5.3.jar
mini_tardis-1.0.4+1.20.4.jar
mixintrace-1.1.1+1.17.jar
Mo-Glass-1.7-MC1.20.4.jar
modelfix-1.14-fabric.jar
modmenu-9.2.0.jar
modmenu-badges-lib-2023.6.1.jar
moonlight-1.20.4-2.10.3-fabric.jar
MoreBeautifulButtons-fabric-1.20.4-1.7.0.jar
moreculling-1.20.4-0.24.0.jar
moveboats-1.20.4-3.2.jar
movingelevators-1.4.7-fabric-mc1.20.4.jar
nicemod-1.4.1 - 1.20.jar
noisium-fabric-2.0.3+mc1.20.2-1.20.4.jar
noxesium-1.2.2.jar
nvidium-0.2.6-beta.jar
optigui-2.3.0-beta.2.jar
origins-gravity-skater-4.0.jar
owo-lib-0.12.6+1.20.3.jar
PacketFixer-fabric-1.20.4-1.2.4.jar
paginatedadvancements-2.4.2.jar
Philips-Ruins1.20.4-2.3[Fabric].jar
player-animation-lib-fabric-1.0.2-rc1+1.20.4.jar
playerautoma-v0.4.4+1.20.4.jar
PlentyPlates-v20.4.1-1.20.4-Fabric.jar
plushies-1.4.0-fabric.jar
polylib-2004.0.3-build.151-fabric.jar
Prism-1.20.4-fabric-1.0.6.jar
puzzle-1.6.1+1.20.4.jar
PuzzlesLib-v20.4.52-1.20.4-Fabric.jar
quartz-elevator-2.2.7+1.20.4.jar
quickpaths-1.20.4-3.3.jar
repurposed_structures_friends_and_foes_compat_v7.jar
resourcefulconfig-fabric-1.20.4-2.4.7.jar
resourcefullib-fabric-1.20.4-2.4.10.jar
Resourcify (1.20.2+-fabric)-1.3.1.jar
rrls-4.0.3+mc1.20.4-fabric.jar
Searchables-fabric-1.20.4-1.0.6.jar
servercore-fabric-1.5.0+1.20.4.jar
signed_paintings-1.1.0-mc1.20.4.jar
sit!-1.1.6+1.20.4.jar
SmartBrainLib-fabric-1.20.4-1.14.1.jar
Sniffer+-fabric-1.20.4-0.3.0.jar
snowyspirit-1.20.4-2.3.4-fabric.jar
spawnanimations-v1.9.4-mc1.17x-1.20x-mod.jar
supermartijn642configlib-1.1.8a-fabric-mc1.20.2.jar
supermartijn642corelib-1.1.17-fabric-mc1.20.3.jar
swplanets-fabric-1.20.4-2.4.1.jar
tapestop-3.1.0-fabric1.20.jar
telepistons-1.1.3-1.20.jar
Terra-fabric-6.4.3-BETA+ab60f14ff.jar
TerraBlender-fabric-1.20.4-3.3.0.12.jar
TerracartReloaded-fabric-1.20.4-1.9.0.jar
thecopperrail-0.9.1.jar
threadtweak-fabric-1.20.4-0.1.2.jar
TrampleNoMore-Fabric-1.20.4-16.0.4.jar
trenzalore-fabric-4.0.1+mc1.20.4.jar
trinkets-3.8.1.jar
tweakeroo-fabric-1.20.4-0.19.2.jar
t_and_t-1.13.1b.jar
UndergroundVillages-fabric-1.20.4-3.1.1.jar
vanilla_plus-1.20.4-0.5.8.jar
Waddles-fabric-1.20.4-0.10.1.jar
warp-portals-1.4.0.jar
WilderWild-2.4.5-Fabric+1.20.4.jar
winterly-fabric-0.10.1+1.20.4.jar
wirelessredstone-fabric-1.20.4-1.1.4.jar
yet-another-config-lib-fabric-3.3.2+1.20.4.jar
yosbr-0.1.2.jar
YungsApi-1.20.4-Fabric-4.4.3.jar
YungsExtras-1.20.4-Fabric-4.4.2.jar
Zoomify-2.14.0+1.20.4.jar
[3D皮肤层] skinlayers3d-fabric-1.6.6-mc1.20.4.jar
[C^2M 引擎] c2me-fabric-mc1.20.4-0.2.0+alpha.11.67.jar
[DFU载入优化] lazydfu-0.1.3.jar
[FPS减速器] FpsReducer2-fabric-1.20.4-2.7.jar
[Macaw的家具] mcw-furniture-3.2.2-mc1.20.4fabric.jar
[Macaw的屋顶] mcw-roofs-2.3.0-mc1.20.4fabric.jar
[Macaw的栅栏与墙] mcw-fences-1.1.2-mc1.20.4fabric.jar
[Macaw的桥梁] mcw-bridges-3.0.0-mc1.20.4fabric.jar
[Macaw的活板门] mcw-trapdoors-1.1.3-mc1.20.4fabric.jar
[Macaw的灯] mcw-lights-1.1.1-mc1.20.4fabric.jar
[Macaw的画] mcw-paintings-1.0.5-1.20.4fabric.jar
[Macaw的窗户] mcw-windows-2.2.1-mc1.20.4fabric.jar
[Macaw的门] mcw-doors-1.1.1fabric-mc1.20.4.jar
[Paladin的家具] paladin-furniture-mod-1.2.1-fabric-mc1.20.4.jar
[Reese的钠视频界面] reeses_sodium_options-1.7.2+mc1.20.4-build.102.jar
[REI物品管理器] RoughlyEnoughItems-14.1.727-fabric.jar
[Xaero的世界地图] XaerosWorldMap_1.38.8_Fabric_1.20.4.jar
[Xaero的小地图] Xaeros_Minimap_24.2.0_Fabric_1.20.4.jar
[YUNG的下界要塞优化] YungsBetterNetherFortresses-1.20.4-Fabric-2.4.4.jar
[YUNG的丛林神庙优化] YungsBetterJungleTemples-1.20.4-Fabric-2.4.4.jar
[YUNG的地牢优化] YungsBetterDungeons-1.20.4-Fabric-4.4.4.jar
[YUNG的末地岛屿优化] YungsBetterEndIsland-1.20.4-Fabric-2.4.3.jar
[YUNG的桥] YungsBridges-1.20.4-Fabric-4.4.2.jar
[YUNG的沙漠神殿优化] YungsBetterDesertTemples-1.20.4-Fabric-3.4.4.jar
[YUNG的沼泽小屋优化] YungsBetterWitchHuts-1.20.4-Fabric-3.4.3.jar
[YUNG的海底神殿优化] YungsBetterOceanMonuments-1.20.4-Fabric-3.4.3.jar
[万用皮肤补丁] CustomSkinLoader_Fabric-14.19.1.jar
[任意门] tempad-fabric-1.20.4-2.3.7.jar
[传送石碑／指路石] waystones-fabric-1.20.4-16.0.5.jar
[作物盛景] Croptopia-FABRIC-3.0.1-1.20.4.jar
[内存泄漏修复] memoryleakfix-fabric-1.17+-1.1.5.jar
[冰山] Iceberg-1.20.4-fabric-1.1.18.jar
[凡家物语：重生] minecraft-comes-alive-7.5.12+1.20.4-universal.jar
[创世神] worldedit-mod-7.3.0.jar
[剑之格挡] ClassicSwordBlocking-Fabric-1.20-1.0.6.jar
[动态准星] dynamiccrosshair-7.7+1.20.4-fabric.jar
[动态准星兼容] dynamiccrosshair-compat-3.7.2+1.20.2.jar
[动物喂养槽] animal_feeding_trough-1.0.3+1.20.4.jar
[区块加载器] chunkloaders-1.2.8a-fabric-mc1.20.4.jar
[区块淡入动画] chunksfadein-1.0.0-1.20.3.jar
[双开门] doubledoors-1.20.4-5.8.jar
[可移动的矿车] moveminecarts-1.20.4-3.4.jar
[喷溅牛奶] splash_milk-2.1.0.jar
[围火无怪] nohostilesaroundcampfire-1.20.4-5.9.jar
[地牢浮现之时] DungeonsArise-1.20.x-2.1.58-fabric-release.jar
[地牢浮现之时] DungeonsAriseSevenSeas-1.20.x-1.0.2-fabric.jar
[地雷] landmines-1.0.7a-fabric-mc1.20.jar
[垃圾桶] trashcans-1.0.18-fabric-mc1.20.jar
[城市工艺] City Craft-1.4.1-Fabric-1.20.x.jar
[多段跳] AirHop-v20.4.1-1.20.4-Fabric.jar
[存档置顶] cherishedworlds-fabric-8.0.1+1.20.4.jar
[实体渲染机制优化] entityculling-fabric-1.6.6-mc1.20.4.jar
[客户端微调] clienttweaks-fabric-1.20.4-13.0.2.jar
[平滑滚动] smoothscroll-2.1.2-1.20.4.jar
[幸运方块] LuckyBlocks-1.5.jar
[幽灵方块同步修复] antighost-1.20.4-fabric0.91.2-1.1.5.jar
[我的世界铁路] MTR-fabric-4.0.0-beta-8+1.20.4.jar
[投影] litematica-fabric-1.20.4-0.17.3.jar
[搬运] carryon-fabric-1.20.4-2.1.3.13.jar
[方块实体优化] enhancedblockentities-0.10.1+1.20.4.jar
[旅行者背包] travelers-backpack-1.20.4-9.4.0.jar
[无缝加载界面] seamless-loading-screen-2.1.1+1.20.4-fabric.jar
[时尚玻璃门] modern-glass-doors-5.3.0+1.20.3-and-later.jar
[旷野之息高塔 ：再重制] totw_modded-fabric-1.20.1-1.0.5.jar
[星光] starlight-1.1.3+fabric.f5dcd1a.jar
[更多动画] notenoughanimations-fabric-1.7.4-mc1.20.4.jar
[更好地破坏半砖] kleeslabs-fabric-1.20.4-16.0.1.jar
[更好的三叉戟] BetterTridents-v20.4.0-1.20.4-Fabric.jar
[更好的下界] better-nether-9.30.0.jar
[更好的信标放置] betterbeaconplacement-1.20.4-3.3.jar
[更好的动物动作] BetterAnimationsCollection-v20.4.0-1.20.4-Fabric.jar
[更好的床] betterbeds-1.3.0-1.19.3.jar
[更好的末地] better-end-4.30.1.jar
[更好的运行时资源包] brrp-fabric-1.0.3-1.20.4.jar
[更好的骑乘HUD] bettermounthud-1.2.2.jar
[末影人革新] endermanoverhaul-fabric-1.20.4-1.1.8.jar
[梧桐物语] [梧桐物语] mcopper-fabric-mc1.20.x-beta1.3.2.jar
[森罗万象]kaleidos-1.0.0.jar
[植物盆栽] BotanyPots-Fabric-1.20.4-16.0.4.jar
[氪] krypton-0.2.6.jar
[汤姆的简易存储] toms_storage_fabric-1.20.4-1.6.13.jar
[治愈营火] healingcampfire-1.20.4-5.3.jar
[泥土TNT] DirTNT-1.4.1-1.20.2.jar
[火把弓] TorchBowMod-Fabric-1.20.4-v1.1.0.jar
[火花] spark-1.10.58-fabric.jar
[烟花苦力怕] creepre_firework-2.1.0.jar
[爆炸动画增强] explosive-enhancement-1.2.2-1.20.x.jar
[物品边框] ItemBorders-1.20.2-fabric-1.2.1.jar
[物理声效重制版] sound-physics-remastered-fabric-1.20.4-1.4.2.jar
[玉 🔍] Jade-1.20.4-fabric-13.3.1.jar
[现代化修复] modernfix-fabric-5.17.0+mc1.20.4.jar
[现代化按键绑定] ModernKeyBinding-Fabric-1.20.4-1.3.0.jar
[界面背景模糊] blur-3.2.0.jar
[真实物理Pro]physics-mod-pro-v169-fabric-1.20.4.jar
[真实的蜜蜂] realisticbees-1.20.4-3.8.jar
[神话金属] mythicmetals-0.19.7+1.20.4.jar
[禁用聊天举报] NoChatReports-FABRIC-1.20.4-v2.6.1.jar
[科技复兴] TechReborn-5.10.4.jar
[空无之景] Nullscape_1.20.x_v1.2.6.jar
[竹子制品] BambooEverything-fabric-4.1.0+mc1.20.4.jar
[简单比萨] pizzas-1.1.4.jar
[简单的语音聊天] voicechat-fabric-1.20.4-2.5.17.jar
[结构变体] repurposed_structures-7.3.5+1.20.4-fabric.jar
[美化！Fabric版] beautify-1.2.1+1.20.4.jar
[聊天动画] chatanimation-1.0.5.jar
[聊天头像] chat_heads-0.12.3-fabric-1.20.3.jar
[聊天栏图片显示] ChatImage-1.2.4+1.20.4+fabric.jar
[聊天补丁] chatpatches-204.6.5.jar
[脚步声] PresenceFootsteps-1.11.3.jar
[自动汉化更新] I18nUpdateMod-3.5.5-all.jar
[自动门] automaticdoors-1.20.4-4.6.jar
[自然之灵] naturespirit-1.4.3-1.20.4.jar
[自然音效] AmbientSounds_FABRIC_v5.3.9_mc1.20.4.jar
[自由视角] FreeLook-fabric-1.20.4-1.5.3.jar
[苹果皮] appleskin-fabric-mc1.20.3-2.5.1.jar
[荒芜] desolation-1.5.0.jar
[落叶] fallingleaves-1.15.6+1.20.1.jar
[落苗生根] saplanting-fabric-1.20.4-1.2.6.jar
[蜜蜂领域／黄蜂领域] the_bumblezone-7.5.3+1.20.4-fabric.jar
[装饰方块] Decorative Blocks-Fabric-1.20.4-5.0.2.jar
[超多生物群系] BiomesOPlenty-fabric-1.20.4-19.0.0.89.jar
[越肩视角重制] ShoulderSurfing-Fabric-1.20.4-3.1.3.jar
[输入法冲突修复] IMBlocker_4.0.7+1.20.4.jar
[边拿边走] InvMove-1.20-0.8.6-Fabric.jar
[迷上城建] mishanguc-1.3.0-1.20.4.jar
[重生核心] RebornCore-5.10.4.jar
[钠 · 土径阴影] sodium-shadowy-path-blocks-3.3.0.jar
[钠 · 扩展] sodium-extra-0.5.4+mc1.20.4-build.116.jar
[钠] sodium-fabric-0.5.8+mc1.20.4.jar
[铁氧体磁芯] ferritecore-6.0.3-fabric.jar
[铟] indium-1.0.31+mc1.20.4.jar
[锂] lithium-fabric-mc1.20.4-0.12.1.jar
[键位冲突显示] Controlling-fabric-1.20.4-15.0.5.jar
[防止踩踏] tramplestopper-fabric-6.0.1+mc1.20.4.jar
[附魔描述] EnchantmentDescriptions-Fabric-1.20.4-20.0.4.jar
[陈列柜] displaycase-fabric-1.20.4-1.0.jar
[预生成区块] Chunky-1.4.10.jar
[额外扩展] AdditionalAdditions-6.1.0.jar
[飞行警报] pullup-fabric-1.20.3-0.0.5.jar
[高清截图Fabric] fabrishot-1.12.1.jar
[鼠标手势] MouseTweaks-fabric-mc1.20-2.26.jar

**Comment by jonafanho** [comment]
How many platforms do you have on your 科創園實驗綫路 route?

**Comment by huanyu1919** [comment]
试试新开一个只有MTR模组和它的前置的客户端，重新试一下这个bug是否仍存在。模组太多了不排除会有一些冲突。

**Comment by SadEPa28** [comment]
ssorry
my route is wrong
