### ISSUE TITLE
Tracks and stations on the dashboard are disappearing? Catenaries are still there.

### ISSUE THREAD

**Issue by Fredster7777** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#903]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported in the [Issues page](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exist in the latest version of the MTR Mod.
- [X] I have tested this in the official version of MTR, not a modified/custom/unofficial build.

### Describe the Bug

On "MTR-farbric-1.19.4-3.2.2-hotfix-1.jar" have the following mods and resource packs in photos.
![IMG_5836](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/174936084/6921126f-9f11-4ac9-be57-fe167b6e078a)
![IMG_5837](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/174936084/a32fbc61-9967-4332-9d73-bd09dda17965)

### Reproduction Steps

1. Use rail connectors between nodes
2. Exit game
3. Rejoin game
4. Tracks are gone.

### In-game Log/Crash Report

N/A

### Mod Loader

Fabric

### Minecraft Version

1.19.4

### MTR Version

3.2.2

### Operating System

macOS Ventura 13.6.7

### List of mods/modpack you were using

In photos above

### Extra Informations

N/A

**Comment by Fredster7777** [comment]
It leaves behind invisible rail nodes FYI.

**Comment by jonafanho** [comment]
Can you please attach logs? Thanks.

**Comment by Fredster7777** [comment]
I can’t find where to get the logs. All I can find is a Windows way of doing it…

**Comment by HENSOLO-PSD** [comment]
Definitely having this issue on 1.20.1

**Comment by Fredster7777** [comment]
I’ll add, I did have MTR 4.0.0 earlier, before I replaced it with 3.2.2. I wanted to have all of NTE, JCM, MSD, and those mods…

**Comment by Fredster7777** [comment]
thats kinda long ngl

**Comment by Fredster7777** [comment]
Well I don’t know what os going on so I can’t fix it

**Comment by HENSOLO-PSD** [comment]
> dude, fix it by yourself jesus christ

You don't have to be rude, bro. This is not something you can fix by yourself. This is something going on with the. forge update. because it was working fine before, but now it's not. because it is something that the creator probably has to fix on his side. Or we can just wait for it. A 4.0. update. But other than that, that comment was not necessary.

**Comment by Fredster7777** [comment]
Hi, I am going to close this forum now as I have moved all my buildings to a new mod pack where 4.0.0 wasn't before installed using worldedit. I have put 3.2.2 onto this modpack and I suggest people take inspiration of what I have done to save their worlds. Thanks!

**Comment by Fredster7777** [comment]
Wdym I was actively trying to find a way to fix it and I put this on as I thought I couldn’t do it

**Comment by Citybuilder7711** [comment]
> well youre dumb

*you're
gg
