### ISSUE TITLE
i cant open railway dashboard when i download save from server!

### ISSUE THREAD

**Issue by JiaqiYi** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#910]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

当我从服务器下载存档并在单人模式启动它的时候,发现仪表版无法打开
但是在从未使用过mtr 的存档中无此问题

### Reproduction Steps

1.使用mohist 服务端,开一个1.20.1forge 服务器
2.建点铁路,让车跑起来
3.在单人打开这个存档
4.铁路仪表版坏掉了(这是被先辈雷普了罢,悲

### In-game Log and Crash Report

ふ

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Minecraft Transit Railway Version

4.0.0b8

### Operating System

win11

### List of Mods or Modpack You Were Using

mtr,msd,jcm,and a lot

**Comment by Kenny-Hui** [comment]
Merging into #900
