### ISSUE TITLE
Bug with elevator damage not being nullified

### ISSUE THREAD

**Issue by LaeDev** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#919]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

When the elevator descends from the top down, it should descend without dealing damage to the player as normal, but the fall damage is still applied to the player based on the height.

### Reproduction Steps

1. Create the elevator as you would originally create it.

2. Descend from the top floor of the elevator to the bottom floor.

### In-game Log and Crash Report

https://mclo.gs/HzpbqXN

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Minecraft Transit Railway Version

4.0.0-beta-8

### Operating System

Windows 10

### List of Mods or Modpack You Were Using

Sodium
YetAnotherConfigLib
Memory Leak Fix
FabricSkyBoxes Interop
Iris
Remove Reloading Screen
Animatica
Language Reload
EntityCulling
FerriteCore
Zoomify
Borderless Mining
Mod Menu
Enhanced Block Entities
e4mc
Fabric API
YOSBR
Entity Model Features
AdvancementInfo
Fabric Language Kotlin
Main Menu Credits
Cloth Config v11
More Chat History
Debugify
Reese's Sodium Options
LambDynamicLights
Indium
Puzzle
Capes
Better Mount HUD
Fadeless
FastQuit
Continuity
Entity Texture Features
Fabrishot
OptiGUI
Model Gap Fix
No Chat Reports
Dynamic FPS
Sodium Extra
ImmediatelyFast
More Culling
MixinTrace
Lithium
CIT Resewn
FabricSkyBoxes
ModernFix
Minecraft Transit Railway

### Extra Information

If you put water underneath the elevator, the damage is eliminated, but there is no way to avoid the damage if it is multi-floor.

**Comment by LaeDev** [comment]
https://github.com/user-attachments/assets/a7b850f9-5528-4ef9-8ba9-22953d464583

**Comment by OmicronZed** [comment]
Same problem here, 1.20.1, Fabric, Mod-Version: FABRIC-4.0.0-beta-8+1.20.1

**Comment by georgemcauliffe** [comment]
I have the same issue, 1.20.1, Forge, MTR-forge-4.0.0-beta-8+1.20.1

**Comment by DMB-codegang** [comment]
I have the same issue, 1.20.4, Fabric, MTR-forge-4.0.0-beta-9+1.20.4

**Comment by HALsion86** [comment]
I have the same issue, 1.20.1, Forge, MTR-forge-4.0.0-beta-10+1.20.1

**Comment by DMB-codegang** [comment]
I have found a temporary workaround: placing water beneath the elevator and below the elevator doors to prevent fall damage.  
Hopefully, this bug can be resolved soon.

**Comment by HALsion86** [comment]
What about the Nether, where water cannot be placed?

**Comment by Kenny-Hui** [comment]
Should be fixed in beta-12
