### ISSUE TITLE
Release v4 on Curseforge?

### ISSUE THREAD

**Issue by gund** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#922]
### Suggestion Type

Other

### Suggestion

Hey, I've seen the description of the mod on Curseforge mentions v4 as being a complete rewrite and a lot of improvements which is awesome but there is no v4 version in the files.
Are you planning on releasing v4 update on Curseforge or is it going to be only on Modrinth platform?

**Comment by huanyu1919** [comment]
The version 4 is still in beta now. This version is unstable now. The author will release v4.0 (release version) on Curseforge. This may take a long time. So, just wait.
