### ISSUE TITLE
Game crashing with the mod

### ISSUE THREAD

**Issue by WWWindddows10000** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#926]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

My game crashes after updating the mod to the latest version.

### Reproduction Steps

1.Update the mod from 3.2.2 to 4.0.0 beta 8
2.Start the game
3.

### In-game Log and Crash Report

https://mclo.gs/sUYfe8C

### Mod Loader

Forge

### Minecraft Version

1.19.2

### Minecraft Transit Railway Version

4.0.0 Beta 8

### Operating System

Windows 10

### List of Mods or Modpack You Were Using

		FarmersDelight-1.19.2-1.2.3.jar 
		TerraBlender-forge-1.19.2-2.0.1.166.jar 
		jei-1.19.2-forge-11.6.0.1016.jar 
		simplylight-1.19.2-1.4.5-build.42.jar 
		exlinecopperequipment-forge-1.19.2-v2.0.6.jar
		Mekanism-1.19.2-10.3.9.13.jar
		flywheel-forge-1.19.2-0.6.10-20.jar 
		Patchouli-1.19.2-77.jar
		create-1.19.2-0.5.1.f.jar 
		Xaeros_Minimap_23.6.0_Forge_1.19.1.jar  
		Croptopia-1.19.2-FORGE-2.2.2.jar 
		worldedit-mod-7.2.12.jar
                Filters API                   
		cfm-7.0.0-pre35-1.19.2.jar  
		architectury-6.6.92-forge.jar
		MTR-forge-1.19.2-3.2.2-hotfix-1.jar
		Tianjin-Metro-1.0.0-beta-1+1.19.2.jar
		Joban-Client-Mod-1.19.2-1.2.2.jar 
		MekanismGenerators-1.19.2-10.3.9.13.jar 
		PuzzlesLib-v4.4.3-1.19.2-Forge.jar 
		Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.4.jar 
		CorgiLib-forge-1.19.2-1.0.0.34.jar          
		forge-1.19.2-43.4.2-universal.jar
		MTR-NTE-0.4.1+1.19.2.jar
		geckolib-forge-1.19-3.1.40.jar
		MTR-MSD-Addon-forge-1.19.2-3.2.2-1.3.4-enhancement

### Extra Information

Forge 43.4.2

**Comment by WWWindddows10000** [comment]
new log after deleting NTE mod:https://mclo.gs/856QHdQ
delete nte mod doesn't work

**Comment by Kenny-Hui** [comment]
Please update all MTR addon (Joban Client Mod, MTR MSD) to a version that supports MTR 4

**Comment by WWWindddows10000** [comment]
> Please update all MTR addon (Joban Client Mod, MTR MSD) to a version that supports MTR 4

I updated them.

**Comment by Kenny-Hui** [comment]
The latest version of JCM is 2.0.0-beta-3
Please re-capture the list of mods you are using right now that is causing the crash

**Comment by WWWindddows10000** [comment]
> The latest version of JCM is 2.0.0-beta-3 Please re-capture the list of mods you are using right now that is causing the crash

Oh, thank you, I will try.

**Comment by WWWindddows10000** [comment]
> The latest version of JCM is 2.0.0-beta-3 Please re-capture the list of mods you are using right now that is causing the crash

I updated it, and I believe that the situation has eased somewhat, but the game still crashes: https://mclo.gs/HC6IUDn

**Comment by Kenny-Hui** [comment]
This is likely a bug, please open a new issue with the log above, thanks.
Please note that MTR 4 is still in Beta. If you need a stable experience, you are advised to stay in MTR 3.2.2 until MTR 4 is officially released.
