### ISSUE TITLE
重新进入单人存档时，列车有概率发生极大延迟发车现象，并有概率导致大规模晚点，使得运行混乱

### ISSUE THREAD

**Issue by huanyu1919** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#928]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

创建完一个路线后，离开单人存档再进入，轨道上的某些列车（尤其是停在站台上的列车）会发生长时间不发车的情况，车门也长时间不关闭，奇怪的是，这个bug只影响一部分列车，这就导致了列车运行出现混乱。而且打开铁路仪表板刷新路线或者清除车辆后，屏蔽门并不会回到关闭状态。
![image](https://github.com/user-attachments/assets/35cde34c-254a-4108-9239-edfbcc277d09)
本站应该停靠30秒，但这趟列车在这里停了1分30秒，奇怪的是时刻表也在跟随改变，没有认定这个列车晚点
后续测试中，列车还有概率发生大规模晚点：
![image](https://github.com/user-attachments/assets/5428a10e-8924-458f-870b-69cf3fc3523a)
由于车辆数量限制为31，导致后续列车无法发出，列车时刻表被完全打乱

### Reproduction Steps

1.打开单人存档，创建一条线路并开始运行，一段时间后正常退出游戏
2.重新进入存档，即有概率发生上述事件
3.

### In-game Log and Crash Report

[latest.log](https://github.com/user-attachments/files/16569766/latest.log)

### Mod Loader

Forge

### Minecraft Version

1.19.2

### Minecraft Transit Railway Version

4.0.0beta8hotfix1

### Operating System

windows 10专业版

### List of Mods or Modpack You Were Using

![image](https://github.com/user-attachments/assets/6acbf85a-1c80-49cd-9ab2-9fb4b5af5cea)

### Extra Information

不在站台上的列车也有可能在下一站异常停留过长时间

**Comment by Maxwenyan** [comment]
如果你盯着在线线路图(localhost:8888)的话，你可能会发现这些长时间停站的列车显示为 early xx:xx，且通常早点的时间都是几分钟起步

**Comment by Kenny-Hui** [comment]
Should be resolved in beta-11+
