### ISSUE TITLE
Game crash MTR 4.0.0 1.20.1 Forge

### ISSUE THREAD

**Issue by JackTheDeveloperOG** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#930]
### Before reporting, I have confirmed that

- [x] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

I installed **Minecraft Transit Railway 4.0.0 for Forge (1.20.1)**. When I opened Minecraft  and Lunched the game. **It crashed immediately**. So how do i fix it or it will be pached? 

### Reproduction Steps

1. Install Minecraft Transit Railway 4.0.0
2. Drop java file in the mods file
3. Lunch minecraft

### In-game Log and Crash Report

**Crash report**: 
[crash-2024-08-06_15.50.51-client.txt](https://github.com/user-attachments/files/16570573/crash-2024-08-06_15.50.51-client.txt)

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Minecraft Transit Railway Version

4.0.0

### Operating System

Windows 11

### List of Mods or Modpack You Were Using

**Mods that use in 1.20.1**: Minecraft Transit Railway, Nemo's Transit Expansion, architectury, CCTV Craft, traffic craft, Create, thingamajigs

### Extra Information

**Minecraft  crashes immediately with 4.0.0 version Forge for 1.20.1**

**Comment by Kenny-Hui** [comment]
Nemo Transit Expansion is for MTR 3 only, some features (Though not all) such as OBJ rendering has been merged into MTR 4
