### ISSUE TITLE
Why not add industrial trains?

### ISSUE THREAD

**Issue by tismatis** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#939]
### Suggestion Type

Train simulation mechanics

### Suggestion

Hey,
I know that the mod is a lot in the direction of passengers but I was thinking,
Is it possible to add a train for transports items and being able to insert/get from them using hopper or another block ?

### Assets

.

### Implementation Details and References

.

**Comment by tjshtqwq** [comment]
通过货物装载器。
plz translate

**Comment by huanyu1919** [comment]
By train cargo loader and train cargo un loader.

**Comment by tismatis** [comment]
I never saw this item in the item list sorry, gonna check right now ^^'

**Comment by tismatis** [comment]
Oh I never saw them, thanks ^^'
