### ISSUE TITLE
train dashboard not opening

### ISSUE THREAD

**Issue by 888845** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#946]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

when I click on the train dashboard it does not open and returns java.lang.NullPointerException: null
I tried in other Minecraft launchers and instances and mod 
loaders but it is the same thing

### Reproduction Steps

1. make some routes
2.make depots and assign them
3. make a lot
4. continue
5. dashboard does not open

### In-game Log and Crash Report

[2024-09-07-6.log.gz](https://github.com/user-attachments/files/16919148/2024-09-07-6.log.gz)
[2024-09-07-7.log.gz](https://github.com/user-attachments/files/16919149/2024-09-07-7.log.gz)
[latest.log](https://github.com/user-attachments/files/16919150/latest.log)
I have one on modrinth too and it is the same problem

### Mod Loader

Forge

### Minecraft Version

1.19.4

### Minecraft Transit Railway Version

4.0.0 beta 8

### Operating System

macOS Sonoma 

### List of Mods or Modpack You Were Using

<img width="774" alt="Screenshot 2024-09-07 at 17 03 10" src="https://github.com/user-attachments/assets/cf50c6e1-a5af-404f-9483-304bb725f10b">
<img width="625" alt="Screenshot 2024-09-08 at 11 30 05" src="https://github.com/user-attachments/assets/8a2f09c8-32e6-48c7-9ff1-5309200b1724">

### Extra Information

it was the same in other instances etc
when the bug happens the time it happens is random
when I make a new world with no transport system it works; needs a working transport system(s) to work
other dashboards (boat dashboard etc) has the same problem
I also have another problem with rails disappearing and trains going slower than it should
but after a while the rails are restored and pids are back to normal but the train dashboard problem is still there
when I only use mtr mod and datapacks with dependencies(corgilib geckolib) without resource packs it returns [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: null on opening train dashboard
THIS IS ON THE CLIENT

**Comment by Kenny-Hui** [comment]
Merging into #900
