### ISSUE TITLE
1.20.1 Forge 47.3.7 cannot use dashboards

### ISSUE THREAD

**Issue by somerui** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#957]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

When I held a dashboard item and use it,it not working,and the log has shown:
 `[20:16:13] [Render thread/WARN]: Unknown custom packet identifier: mtr:packet`

### Reproduction Steps

1.Start the instance
2.Open the save.
3.Use the dashboard.
4.The dashboard isn't working.

### In-game Log and Crash Report

[minecraft-exported-logs-2024-09-15T20-24-56.log](https://github.com/user-attachments/files/17005755/minecraft-exported-logs-2024-09-15T20-24-56.log)

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Minecraft Transit Railway Version

4.0.0 Beta9

### Operating System

Windows 11

### List of Mods or Modpack You Were Using

[modlist.txt](https://github.com/user-attachments/files/17005760/modlist.txt)

### Extra Information

The testing is starting in a already loaded in 1.16.5Fabric, 1.19.2Forge and 1.20.1Forge with mtr 3.2.2's world.
The bug isn't appear on fabric 1.20.1,the dashboard is worked successfully.

**Comment by 888845** [comment]
I had this problem consider checking #900

**Comment by 888845** [comment]
hopefully it will be fixed :(

**Comment by somerui** [comment]
> hopefully it will be fixed :( 

ok I'll close this issue :(

**Comment by Kenny-Hui** [comment]
Merging into #900

**Comment by somerui** [comment]
Ha, finally resolved. It fixed on beta11.
