### ISSUE TITLE
My world broken

### ISSUE THREAD

**Issue by Sinkis290** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#958]
I used the latest beta of the MTR mod and my world broke down. Do you know what to do? I don't have a backup (yes I'm stupid)

**Comment by SolDev69** [comment]
Back your world up
Always back your world up
#1 rule of modding 
if you're testing mods on an important world, do not, and if you still want to then back your world up
Check Minecraft's backup folder just encase, if nothing's there then you're out of luck
