### ISSUE TITLE
Key isn't in game

### ISSUE THREAD

**Issue by b0rrajo** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#960]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

Hello everyone
I installed beta 9 of Minecraft Transit Railway but I can't find the key to start the train in the panel where the tracks and the 4 dashboards of the different transport services are.

If they have removed it, is there any way to start the trains?

I would appreciate a response as soon as possible since we are going to implement the mod on a RP server.

Thank you in advance

### Reproduction Steps

1. Load the server with MTR 4.0.0 Beta 9 - 1.19.2
2. Open inventory in creative gamemode
3. In railway panel, the key doesn't appear

### In-game Log and Crash Report

Nothing, game, mods and plugins loads successfull

### Mod Loader

Forge

### Minecraft Version

1.19.2

### Minecraft Transit Railway Version

4.0.0 - BETA 9

### Operating System

Windows 11

### List of Mods or Modpack You Were Using

![image](https://github.com/user-attachments/assets/444e6dad-449b-4a46-afd9-02b7ba43ee07)
![image](https://github.com/user-attachments/assets/de1370c9-392c-4cdf-b483-e39d4b6b7f64)
![image](https://github.com/user-attachments/assets/f517cde6-d539-45b6-8dbe-23efeb7f2fd9)

**Comment by Kenny-Hui** [comment]
MTR is primarily geared towards automated train operations. The manual driving feature is being reworked in 4.0.0, and are therefore not available at the moment.

To setup trains for automated operation, please refer to the YouTube tutorial:
https://www.youtube.com/watch?v=KIsuRxNW3Lc&list=PLp0jZgheSlXv_vjilwnbrOtdbmgvz1VkC

For manual train operation with driver key, please use MTR 3 instead. (Note that downgrade from MTR 4 is not available, and you are advised to backup your world beforehand)
