### ISSUE TITLE
Change name of /mtr forceCopyWorld command

### ISSUE THREAD

**Issue by james5922** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#962]
### Suggestion Type

Other

### Suggestion

Hello there. While trying to nail down a different issue (I was getting a flood of NullPointerExceptions in my server console/log that were seemingly linked to MTR pathfinding), I tried to use the `/mtr forceCopyWorld` command to try and fix the problem. 

Looking at the syntax suggestion, which was `/mtr forceCopyWorld [world directory] [backup directory]`, I made the (incorrect) assumption that it was some kind of backup command. First time I tried it, the directory I used as [backup directory] did not exist, so I created it on the server end afterward. The second time I tried it (the backup directory was empty as I had just created it, and I had assumed it would populate that directory with the "backup"), IT COMPLETELY WIPED MY WORLD. And I hadn't made any actual world backups, so I was S.O.L. and had to restart the server world from scratch.

Turns out `forceCopyWorld` was a restore command! Whoops! **I would like to suggest that the name of the** `forceCopyWorld` **command be changed in some way**, to make it clearer what the command actually does. Perhaps to `forceRestoreWorld`. And maybe add a "are you sure?" response, confirmation would be in the form of `/mtr confirm` or similar.

Looking back, I should have used the `/mtr clear` command in order to just clear the MTR stuff, but as they say hindsight is 20-20.

Thanks. -James5922, aka Kurzov

**Comment by Kenny-Hui** [comment]
Changed in the next version~
