### ISSUE TITLE
How Can You Add "Slidings" To Depots

### ISSUE THREAD

**Issue by Danmccool** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#963]
![image_2024-09-19_224636535](https://github.com/user-attachments/assets/a15d34a9-fedf-4c72-b431-061faa84f588)

**Comment by Danmccool** [comment]
Plus Routes Dont Work

**Comment by Danmccool** [comment]
@octylFractal

**Comment by kettle-7** [comment]
use the siding rail connector between two rail nodes within the depot to make a siding rail. it needs to be long enough for the train you want to use. for an sp1900 this is 26 blocks for one car, plus another 25 for each additional car

**Comment by Kenny-Hui** [comment]
As suggested, you need to make a siding rail.
Please check the [video](https://www.youtube.com/playlist?list=PLp0jZgheSlXv_vjilwnbrOtdbmgvz1VkC) or [text](https://wiki.minecrafttransitrailway.com/mtr:getting_started) tutorial on setting up a railway system in MTR Mod.
