### ISSUE TITLE
modern elevators

### ISSUE THREAD

**Issue by Alcatraz-Funtime** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#969]
### Before reporting, I have confirmed that

- [ ] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

При блокировке дверей лифта на ней появляется отсутствующая текстура
![Снимок экрана (102)](https://github.com/user-attachments/assets/58f9abab-bf86-4a7e-b00c-ee4bc9d893ba)

### Reproduction Steps

Блокировка дверей лифта кистью

### In-game Log and Crash Report

[2024-09-25-1.log.gz](https://github.com/user-attachments/files/17127994/2024-09-25-1.log.gz)

### Mod Loader

Fabric

### Minecraft Version

1.16.5

### Minecraft Transit Railway Version

3.1.6

### Operating System

win 11

### List of Mods or Modpack You Were Using

![Снимок экрана 2024-09-25 113959](https://github.com/user-attachments/assets/82c09211-cf98-4c10-8347-b8b36bb3c03b)

**Comment by Kenny-Hui** [comment]
Modern Elevator is no longer supported, please install Minecraft Transit Railway 3.2.2 which is fully compatible with Modern Elevator, and should have the issue fixed.

**Comment by Alcatraz-Funtime** [comment]
> Minecraft Transit Railway

Могут ли произойти проблемы с моим миром?
