### ISSUE TITLE
customisable resources (PLS I NEED THIS)

### ISSUE THREAD

**Issue by 888845** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#972]
### Suggestion Type

User experience

### Suggestion

it would be good to change tactile map music and etc within the game because I can't open the jar with javalauncher to change it on mac etc and archive utility does nothing
also it would be good for mtr announcements because I wonder how other servers get them
it also makes life so much easier
I tried to change it and the game stopped

### Assets

idk maybe mtr announcements and tactile map music

### Implementation Details and References

when clicking resource such as tactile map with brush you can choose a sound
add mtr announcement sounds and tactile map music to the game if it was not implemented

**Comment by kettle-7** [comment]
You can already do what you're describing with [resource packs](
https://minecraft.wiki/w/Resource_Pack)

**Comment by 888845** [comment]
even if you add a resource pack its it possible to change the tactile map music with it

**Comment by jonafanho** [comment]
Yes

**Comment by 888845** [comment]
how?

**Comment by 888845** [comment]
I dont get it

**Comment by 888845** [comment]
help
