### ISSUE TITLE
MinecraftClientData.getInstance().platformIdMap.get(platformId).routes is always empty

### ISSUE THREAD

**Issue by duduskz** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#973]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

![image](https://github.com/user-attachments/assets/7aaa9e2b-dab6-4a01-b79f-b01a4b3fa689)
This is a simple code that calls mtr core to get the Route list by platformId, but the routes of MinecraftClientData.platformIdMap is always empty

### Reproduction Steps

1. Write a getRouteStream method, as shown above
2. Enter the game test and test that the platform corresponding to platformId has a route
3. Send debugging information: routes is empty.
![image](https://github.com/user-attachments/assets/f3ed99c3-bc51-4ec2-8b82-09a77996d001)

### In-game Log and Crash Report

![image](https://github.com/user-attachments/assets/4613d5b7-8817-4c0d-b677-06ce593f4920)

### Mod Loader

Fabric

### Minecraft Version

1.20.4

### Minecraft Transit Railway Version

4.0.0

### Operating System

Windows 11

### List of Mods or Modpack You Were Using

![image](https://github.com/user-attachments/assets/6b4d0802-a790-44e8-b11f-a1ee3ec4dca5)

**Comment by duduskz** [comment]
This may be because I created the station in advance, but how should I get the Data of the entire map?

**Comment by Kenny-Hui** [comment]
Query `simplifedRoutes` instead of `routes`, which should exist in the client side.
