### ISSUE TITLE
Texture error when using shader

### ISSUE THREAD

**Issue by NXKSP233** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#978]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

When using a shader with **Integrated PBR+** settings, train lights and some signboard textures will display incorrectly. 
Selecting other types of **RP support** will not have this problem.
Tested in both version 4.0.0 and 3.2.2
![09f563485f1318aa3f5bb11b254abbf](https://github.com/user-attachments/assets/9429560d-b06b-4725-ad17-daa862e71c9c)
![161c3bdc86317abfaf0b7407d63db33](https://github.com/user-attachments/assets/99ddad07-8780-4948-95ca-8629a61ede11)
![1127238d88d9f5716c029502440a6e9](https://github.com/user-attachments/assets/7d48498c-86b8-4945-b2b6-6067bee3f044)
![ba2f96b669ea2e487b8aa2ac01cd6b9](https://github.com/user-attachments/assets/2ef35530-471e-4cd0-8971-d48b9136dc01)
![c38355653fd75023871153aa8e20c00](https://github.com/user-attachments/assets/b63faa8e-2437-434f-a032-9192af1c8cf6)

### Reproduction Steps

1.Install MTR (3.x.x or 4.x.x)
2.Enable Shader with Integrated PBR Setting on
![be00bae316080642402306edc20573f](https://github.com/user-attachments/assets/5ef361d9-6734-4601-999d-81ebe4495266)

### In-game Log and Crash Report

N/A

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Minecraft Transit Railway Version

3.2.2

### Operating System

Windows 11

### List of Mods or Modpack You Were Using

Architectury API 
Embeddium
Oculus
Minecraft Transit Railway
Shader: ComplementaryUnbound_r5.2.2

### Extra Information

Cause by RP texture setting

**Comment by Kenny-Hui** [comment]
Should be resolved in the upcoming MTR 4 beta
