### ISSUE TITLE
i cant enter the train?

### ISSUE THREAD

**Issue by TonyTeardown** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#983]
### Suggestion Type

Train simulation mechanics

### Suggestion

i cant enter the train i just go trough it like collision off

### Assets

i cant enter the train i just go trough it like collision off

### Implementation Details and References

i cant enter the train i just go trough it like collision off

**Comment by jonafanho** [comment]
Please provide more details and reopen if needed. Are the train doors open? Are you boarding through the doors?
